import { chromium } from 'playwright-core';
import { spawn } from 'node:child_process';
import { readdirSync } from 'node:fs';
const root='/opt/pw-browsers'; const dir=readdirSync(root).find(d=>d.startsWith('chromium-'));
const srv=spawn('npx',['vite','preview','--port','4392','--strictPort'],{stdio:'ignore'});
await new Promise(r=>setTimeout(r,2500));
const b=await chromium.launch({executablePath:`${root}/${dir}/chrome-linux/chrome`,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const p=await (await b.newContext({viewport:{width:1280,height:800}})).newPage();
const errs=[]; p.on('pageerror',e=>errs.push(String(e))); p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
await p.addInitScript(()=>localStorage.setItem('codequest.e2e','1'));
await p.goto('http://localhost:4392');
await p.getByTestId('name-input').fill('Ada'); await p.getByTestId('begin').click();
await p.locator('[data-testid=play][data-ready="1"]').waitFor();
await p.evaluate(()=>window.__cq3d.travel('garage'));
await p.evaluate(()=>window.__cq3d.drive());
await p.getByTestId('drive-hud').waitFor();
await p.evaluate(()=>window.__cq3d.autopilot(true, 5));
const t0=Date.now();
for (let i=0;i<60;i++){ await p.waitForTimeout(2000); const h=await p.evaluate(()=>window.__cq3dHud); if(i%3==0) console.log(i*2,'s', JSON.stringify({kmh:h.kmh,lap:h.lap,t:h.lapTime.toFixed(1),gate:h.checkpoint,surf:h.surface})); if (h.lap>=1) { console.log('LAP DONE', h.best, 'real s', (Date.now()-t0)/1000); break; } }
await p.screenshot({path:'/tmp/drv-lap.png'});
const s=await p.evaluate(()=>JSON.parse(localStorage.getItem('codequest.save')).play.seen);
console.log('seen', Object.keys(s));
console.log('errors', errs.slice(0,5));
await b.close(); srv.kill();
