import type { Challenge } from '../schema';
import { script } from '../daily/helpers';
import type { Check } from '../schema';
import { bossChallenge } from './helpers';

const db = { databases: ['works'] };
const dbScript = (name: string, code: string): Check => ({ kind: 'script', name, code, databases: ['works'], visible: false });

/** Data-engineering mastery boss and the final capstone (Python + SQLite together, unfamiliar contexts). */
export const dataEngBossChallenges: Challenge[] = [
  bossChallenge({
    id: 'boss-de-mastery-a', title: 'Mastery Trial: The Sensor Feed', language: 'python', skillIds: ['de.pipelines', 'de.cleaning', 'db.integrity'], difficulty: 5, context: 'environmental monitoring', project: true,
    boss: { bossId: 'mastery-data-eng', version: 'a' },
    prompt: 'A weather-station network sends `readings.csv` with the header `sensor,time,value`. A row is valid when the sensor name is not blank, `time` is exactly `YYYY-MM-DD HH:MM` and a real date and time, and `value` is a finite number. Everything else is rejected, must never stop the run and must never be stored.\n\nWrite `ingest(csv_path, db_path)` that stores valid rows in a table `readings` (columns `sensor`, `time`, `value`) in the SQLite file, with one row per sensor and time: when the same sensor and time appear again (in this file or a later one) the **latest** value wins. Return a dictionary `{"accepted": n, "rejected": m}` counting the valid and rejected data rows **of this file** (a repeated sensor and time still counts each time it is valid). Running the same file twice must leave the table unchanged.',
    checks: [
      script('Good and bad rows', "import sqlite3\nopen('r.csv','w').write('sensor,time,value\\nA1,2024-05-01 10:00,12.5\\n,2024-05-01 10:00,3\\nA1,2024-05-01 10:10,x\\nA1,2024-5-1 10:20,4\\nB2,2024-02-30 10:00,4\\nB2,2024-05-01 11:00,7\\nA1,2024-05-01 10:00,13\\n')\nr = ingest('r.csv','t.db')\nassert r == {'accepted': 3, 'rejected': 4}, 'Got %r.' % (r,)\nrows = sqlite3.connect('t.db').execute('select sensor, time, value from readings order by sensor, time').fetchall()\nassert rows == [('A1','2024-05-01 10:00',13.0),('B2','2024-05-01 11:00',7.0)], 'Got %r.' % (rows,)"),
      script('Repeat runs and later files', "import sqlite3\nopen('r.csv','w').write('sensor,time,value\\nA1,2024-05-01 10:00,1\\nA1,2024-05-01 10:10,2\\n')\nopen('s.csv','w').write('sensor,time,value\\nA1,2024-05-01 10:10,9\\nA2,2024-05-01 10:10,5\\n')\ningest('r.csv','t.db'); ingest('r.csv','t.db'); ingest('s.csv','t.db')\nrows = sqlite3.connect('t.db').execute('select sensor, time, value from readings order by sensor, time').fetchall()\nassert rows == [('A1','2024-05-01 10:00',1.0),('A1','2024-05-01 10:10',9.0),('A2','2024-05-01 10:10',5.0)], 'Got %r.' % (rows,)"),
      script('Special numbers and boundary times', "import sqlite3\nopen('r.csv','w').write('sensor,time,value\\nA,2024-05-01 23:59,nan\\nB,2024-05-01 24:00,1\\nC,2024-05-01 00:00,-3.5\\nD,2024-05-01 10:60,1\\nE,2024-05-01 10:00,inf\\nF,2024-02-29 08:15,0\\n')\nr = ingest('r.csv','t.db')\nrows = sqlite3.connect('t.db').execute('select sensor, value from readings order by sensor').fetchall()\nassert rows == [('C',-3.5),('F',0.0)], 'Got %r.' % (rows,)\nassert r == {'accepted': 2, 'rejected': 4}, 'Got %r.' % (r,)"),
      script('An empty feed still creates the table', "import sqlite3\nopen('e.csv','w').write('sensor,time,value\\n')\nassert ingest('e.csv','t.db') == {'accepted': 0, 'rejected': 0}\nassert sqlite3.connect('t.db').execute('select count(*) from readings').fetchone()[0] == 0"),
    ],
  }),
  bossChallenge({
    id: 'boss-de-mastery-b', title: 'Mastery Trial: The Orders Export', language: 'python', skillIds: ['de.pipelines', 'de.integration', 'db.integrity'], difficulty: 5, context: 'e-commerce', project: true,
    boss: { bossId: 'mastery-data-eng', version: 'b' },
    prompt: 'A shop exports orders as a JSON file: a list of objects like `{"id": 7, "customer": "Ada", "lines": [{"sku": "X1", "qty": 2, "price": 4.5}]}`.\n\nWrite `load_orders(json_path, db_path)` that stores them in two tables of the SQLite file: `orders` (`id` primary key, `customer`) and `order_lines` (`order_id`, `sku`, `qty`, `price`). An order is rejected **as a whole** (none of its lines are stored) when its id is not an integer, its customer is blank, it has no lines, or any line has a blank sku, a `qty` that is not a positive integer, or a negative price. Running it again with the same or an updated file must not duplicate anything: an order that appears again replaces the old version, including its lines. Return the list of the **three customers with the highest total spend** (quantity × price over all stored lines) as `(customer, total)` pairs with the total rounded to 2 places, biggest first, ties by customer name.',
    checks: [
      script('Typical export', "import json, sqlite3\njson.dump([{'id':1,'customer':'Ada','lines':[{'sku':'X1','qty':2,'price':4.5},{'sku':'Y2','qty':1,'price':10}]},{'id':2,'customer':'Bo','lines':[{'sku':'X1','qty':10,'price':4.5}]},{'id':3,'customer':'Cy','lines':[{'sku':'Z','qty':1,'price':1}]},{'id':4,'customer':'Di','lines':[{'sku':'Z','qty':3,'price':2}]}], open('o.json','w'))\nr = load_orders('o.json','t.db')\nassert r == [('Bo',45.0),('Ada',19.0),('Di',6.0)], 'Got %r.' % (r,)\ncon = sqlite3.connect('t.db')\nassert con.execute('select count(*) from orders').fetchone()[0] == 4\nassert con.execute('select count(*) from order_lines').fetchone()[0] == 5"),
      script('An invalid order is rejected whole', "import json, sqlite3\njson.dump([{'id':1,'customer':'Ada','lines':[{'sku':'X','qty':1,'price':5},{'sku':'','qty':1,'price':5}]},{'id':'2','customer':'Bo','lines':[{'sku':'X','qty':1,'price':5}]},{'id':3,'customer':' ','lines':[{'sku':'X','qty':1,'price':5}]},{'id':4,'customer':'Di','lines':[]},{'id':5,'customer':'Ed','lines':[{'sku':'X','qty':0,'price':5}]},{'id':6,'customer':'Flo','lines':[{'sku':'X','qty':1,'price':-1}]},{'id':7,'customer':'Gus','lines':[{'sku':'X','qty':1.5,'price':2}]},{'id':8,'customer':'Hal','lines':[{'sku':'X','qty':2,'price':0}]}], open('o.json','w'))\nr = load_orders('o.json','t.db')\ncon = sqlite3.connect('t.db')\nassert [x[0] for x in con.execute('select id from orders order by id')] == [8], 'Only order 8 is valid. Got %r.' % (con.execute('select id from orders').fetchall(),)\nassert con.execute('select count(*) from order_lines').fetchone()[0] == 1\nassert r == [('Hal',0.0)], 'Got %r.' % (r,)"),
      script('Reloading replaces old versions', "import json, sqlite3\njson.dump([{'id':1,'customer':'Ada','lines':[{'sku':'X','qty':1,'price':5},{'sku':'Y','qty':1,'price':5}]},{'id':2,'customer':'Bo','lines':[{'sku':'X','qty':1,'price':1}]}], open('o.json','w'))\nload_orders('o.json','t.db'); load_orders('o.json','t.db')\njson.dump([{'id':1,'customer':'Ada','lines':[{'sku':'Z','qty':4,'price':2.5}]}], open('p.json','w'))\nr = load_orders('p.json','t.db')\ncon = sqlite3.connect('t.db')\nassert con.execute('select sku, qty from order_lines where order_id = 1').fetchall() == [('Z',4)], 'The new version of order 1 replaces the old lines.'\nassert con.execute('select count(*) from order_lines').fetchone()[0] == 2\nassert r == [('Ada',10.0),('Bo',1.0)], 'Got %r.' % (r,)"),
      script('Fewer than three customers, and ties', "import json\njson.dump([{'id':1,'customer':'Zed','lines':[{'sku':'X','qty':1,'price':5}]},{'id':2,'customer':'Amy','lines':[{'sku':'X','qty':1,'price':5}]},{'id':3,'customer':'Amy','lines':[{'sku':'X','qty':1,'price':0.1}]},{'id':4,'customer':'Ben','lines':[{'sku':'X','qty':1,'price':5.1}]}], open('o.json','w'))\nr = load_orders('o.json','t.db')\nassert r == [('Amy',5.1),('Ben',5.1),('Zed',5.0)], 'Got %r (round to two places, ties by name).' % (r,)\njson.dump([], open('e.json','w'))\nassert load_orders('e.json','t2.db') == []"),
    ],
  }),
  // ---- the Summit capstone: an open brief on the factory database, Python and SQL together
  bossChallenge({
    id: 'boss-summit-a', title: 'The Summit: The Maintenance Ledger', language: 'python', db: 'works', fixtures: db, skillIds: ['de.integration', 'sql.advanced', 'py.functions', 'py.dicts'], difficulty: 5, context: 'manufacturing', project: true,
    boss: { bossId: 'summit', version: 'a' },
    prompt: 'The factory database is `works.db`. The plant manager needs a report of the machines that lose the most time to maintenance.\n\nWrite `worst_machines(db_path, n)` returning a list of `(machine_name, total_downtime_hours, total_cost)` tuples for the `n` machines with the most total downtime, most first (ties by machine name A to Z). Machines with no maintenance events are not included. An event with an unknown cost counts as 0 cost. `n` of zero or less gives an empty list, and asking for more machines than exist just returns them all.\n\nNo structure is provided. Decide how to query, where to compute, and test your own work.',
    checks: [
      dbScript('The report', "import sqlite3\ncon = sqlite3.connect('works.db')\ndef ref(n):\n    rows = con.execute('select m.name, sum(e.downtime_hours), sum(coalesce(e.cost,0)) from machines m join maintenance_events e on e.machine_id = m.id group by m.id order by sum(e.downtime_hours) desc, m.name').fetchall()\n    return [(a, b, c) for a, b, c in rows][:max(n, 0)]\nfor n in (1, 3, 100, 0, -2):\n    got = worst_machines('works.db', n)\n    exp = ref(n)\n    assert len(got) == len(exp) and all(g[0] == e[0] and abs(g[1]-e[1]) < 1e-6 and abs(g[2]-e[2]) < 1e-6 for g, e in zip(got, exp)), 'For n=%d expected %r, got %r.' % (n, exp, got)"),
      { kind: 'script', name: 'Different data', visible: false, databases: ['works-b:works'], code: "import sqlite3\ncon = sqlite3.connect('works.db')\nrows = con.execute('select m.name, sum(e.downtime_hours), sum(coalesce(e.cost,0)) from machines m join maintenance_events e on e.machine_id = m.id group by m.id order by sum(e.downtime_hours) desc, m.name').fetchall()\ngot = worst_machines('works.db', 4)\nexp = rows[:4]\nassert len(got) == len(exp) and all(g[0] == e[0] and abs(g[1]-e[1]) < 1e-6 and abs(g[2]-e[2]) < 1e-6 for g, e in zip(got, exp)), 'Expected %r, got %r.' % (exp, got)" },
      dbScript('Ties and missing costs', "import sqlite3\ncon = sqlite3.connect('works.db')\ncon.execute('delete from maintenance_events')\nms = con.execute('select id, name from machines order by id limit 3').fetchall()\nfor mid, _ in ms:\n    con.execute(\"insert into maintenance_events (machine_id, technician_id, event_date, kind, downtime_hours, cost) values (?, 1, '2024-01-01', 'repair', 5, null)\", (mid,))\ncon.commit(); con.close()\ngot = worst_machines('works.db', 2)\nexp = sorted(m[1] for m in ms)[:2]\nassert [g[0] for g in got] == exp, 'Tied machines are ordered by name. Got %r.' % (got,)\nassert all(g[2] == 0 for g in got), 'A missing cost counts as zero.'"),
    ],
  }),
  bossChallenge({
    id: 'boss-summit-b', title: 'The Summit: The Technician Roster', language: 'python', db: 'works', fixtures: db, skillIds: ['de.integration', 'sql.advanced', 'py.functions', 'py.dicts'], difficulty: 5, context: 'manufacturing', project: true,
    boss: { bossId: 'summit', version: 'b' },
    prompt: 'The factory database is `works.db`. Maintenance wants to see who carries the load.\n\nWrite `technician_load(db_path)` returning a list of `(technician_name, events, machines, hours)` tuples, one for every technician with **three or more** maintenance events: `events` is how many events they handled, `machines` how many **different** machines those events were on, and `hours` the total downtime of their events. Busiest first by `events`, then by `hours` (more first), then by name A to Z. \n\nNo structure is provided. Decide how to query, where to compute, and test your own work.',
    checks: [
      dbScript('The roster', "import sqlite3\ncon = sqlite3.connect('works.db')\nexp = con.execute('select e.name, count(*), count(distinct m.machine_id), sum(m.downtime_hours) from maintenance_events m join employees e on e.id = m.technician_id group by e.id having count(*) >= 3 order by count(*) desc, sum(m.downtime_hours) desc, e.name').fetchall()\ngot = technician_load('works.db')\nassert len(exp) > 0 and len(got) == len(exp) and all(g[0] == x[0] and g[1] == x[1] and g[2] == x[2] and abs(g[3]-x[3]) < 1e-6 for g, x in zip(got, exp)), 'Expected %r, got %r.' % (exp, got)"),
      { kind: 'script', name: 'Different data', visible: false, databases: ['works-b:works'], code: "import sqlite3\ncon = sqlite3.connect('works.db')\nexp = con.execute('select e.name, count(*), count(distinct m.machine_id), sum(m.downtime_hours) from maintenance_events m join employees e on e.id = m.technician_id group by e.id having count(*) >= 3 order by count(*) desc, sum(m.downtime_hours) desc, e.name').fetchall()\ngot = technician_load('works.db')\nassert len(got) == len(exp) and all(g[0] == x[0] and g[1] == x[1] and g[2] == x[2] and abs(g[3]-x[3]) < 1e-6 for g, x in zip(got, exp)), 'Expected %r, got %r.' % (exp, got)" },
      dbScript('The threshold and the tie-breaks', "import sqlite3\ncon = sqlite3.connect('works.db')\ncon.execute('delete from maintenance_events')\ndef ev(t, m, h):\n    con.execute(\"insert into maintenance_events (machine_id, technician_id, event_date, kind, downtime_hours, cost) values (?, ?, '2024-01-01', 'repair', ?, null)\", (m, t, h))\nts = [r[0] for r in con.execute('select id from employees order by name limit 4')]\nfor _ in range(3): ev(ts[0], 1, 1)\nfor m in (1, 2, 3): ev(ts[1], m, 1)\nfor _ in range(2): ev(ts[2], 1, 50)\nfor _ in range(3): ev(ts[3], 1, 2)\ncon.commit(); con.close()\ngot = technician_load('works.db')\nassert len(got) == 3, 'Two events is below the threshold. Got %r.' % (got,)\nassert [g[3] for g in got] == [6, 3, 3], 'Most hours first among equal event counts, then by name. Got %r.' % (got,)\nassert sorted(g[2] for g in got) == [1, 1, 3], 'Count distinct machines.'"),
    ],
  }),
];
