import type { TrainingNote } from '../trainingNotes';

/**
 * Refresher cards for the Phase 5 worlds (R, spreadsheets, Git, statistics, analytics). Each one names the idea from a DIFFERENT angle than
 * the lesson and lists the traps learners actually fall into. They explain, they never solve a challenge.
 */
const n = (skillId: string, title: string, body: string, pitfalls: string[], example?: string): TrainingNote => ({ skillId, title, body, example, pitfalls });

export const proNotes: TrainingNote[] = [
  // --------------------------------------------------------------- R
  n('r.basics', 'R: values and files', 'In R you name a value with `<-`, ask for it with `print`, and pull inputs from files. `readLines` gives text; nothing calculates until the text becomes numbers with `as.numeric`. The `[1]` in front of a printed value is an index, not part of the answer.', ['Doing arithmetic on text read from a file.', 'Using `cat` when the task says print (or the other way round): the output format differs.', 'Rounding before the final step.'], 'x <- as.numeric(readLines("temp.txt"))\nprint(round(x * 9 / 5 + 32, 1))'),
  n('r.vectors', 'R: think in whole columns', 'Every value in R is a vector, and operations work on all elements at once. A comparison gives TRUE/FALSE per element; used as an index it keeps the TRUE positions; added up it counts them. If you reach for a loop to touch every element, look for the vector form first.', ['Using `if` where the data is a vector (see the functions card).', 'Forgetting that TRUE counts as 1 inside `sum`.', 'Off-by-one on a boundary: `>` versus `>=`.'], 'x <- c(4, 8, 6, 50)\nprint(x[x > mean(x)])\nprint(sum(x > 5))'),
  n('r.functions', 'R: one value or many?', 'A function should say whether it accepts one value or a whole vector. `if` and `else` need exactly one TRUE/FALSE; `ifelse` decides every element and returns a vector of the same length. Test each function on a single value and on a vector with values on the boundaries.', ['A plain `if` inside a function that will receive a vector.', 'Nesting `ifelse` in the wrong order so a higher band never fires.', 'Forgetting the empty case: what should the function return for nothing?'], 'band <- function(x) ifelse(x >= 70, "high", ifelse(x >= 40, "mid", "low"))\nprint(band(c(10, 40, 70)))'),
  n('r.dataframes', 'R: a table is a list of columns', 'A data frame holds one vector per column. `d$col` takes a column; `d[condition, ]` takes rows (rows before the comma, columns after). Look before you calculate: `nrow`, `names`, `str`. Numbers that look like numbers may still be text if the file had stray characters.', ['Forgetting the comma: `d[d$x > 5]` picks columns, not rows.', 'Using `&&`/`||` where the vectorised `&`/`|` is needed.', 'Treating a missing value like a zero.'], 'd <- read.csv("staff.csv")\nprint(nrow(d))\ncat(d$name[d$salary > 50000], sep = "\\n")'),
  n('r.manipulation', 'R: split, apply, combine', 'Per-group questions have one shape: split the rows by a key, summarise each group, put the results in a table. `aggregate` does it in one call; `order` sorts; `merge` joins two tables on a key and needs a decision about rows with no match. State the columns and row order your function must return, and produce exactly that.', ['Joining without `all.x = TRUE` and silently losing rows.', 'Averaging per-row rates instead of dividing group totals.', 'Sorting descending by negating the wrong column, or forgetting the tie-break.'], 'means <- aggregate(pay ~ dept, data = d, FUN = mean)\nmeans[order(-means$pay, means$dept), ]'),
  n('r.analysis', 'R: from file to verdict', 'An analysis reads the data, summarises each group, quantifies uncertainty and states a verdict the data supports. Use the tool that matches the question (two means: a t-test; two proportions: a proportion test) and report both the numbers and the decision rule you used.', ['Reporting a p-value without saying what was compared.', 'Treating “not significant” as “no difference”.', 'Printing numbers with the wrong number of decimals.'], 'p <- t.test(seconds ~ machine, data = d)$p.value\ncat(sprintf("p-value: %.4f\\n", p))'),

  // --------------------------------------------------------------- Spreadsheets
  n('xl.formulas', 'Spreadsheets: formulas follow the data', 'A formula should stay right when an input changes. Put inputs in labelled cells, refer to them, and lock the ones every row shares with `$`. If a number is typed inside a formula, ask whether it could ever change.', ['Typing a rate into a formula instead of referring to its cell.', 'Copying a formula whose shared cell was not locked.', 'Dividing by the wrong base (profit over cost versus over price).'], '=B2*(1+$F$1)'),
  n('xl.functions', 'Spreadsheets: let functions do the work', 'Ranges feed functions: `SUM`, `AVERAGE`, `MEDIAN`, `LARGE`. Text is built with `&` and cut with `LEFT`/`MID`. Decide what the function sees: does the range include blanks or text, and does your answer need rounding at the end?', ['Averaging a range that includes the total row.', 'Rounding a value that later formulas need exact.', 'Joining text without the space or separator.'], '=ROUND(AVERAGE(B2:B6),1)'),
  n('xl.logic', 'Spreadsheets: decisions and boundaries', 'A nested `IF` checks one band after another, so order matters. Write the boundary you mean (`>=` or `>`), then test the values exactly on it. `AND`/`OR` combine tests; `IFERROR` replaces an error with a fallback you choose.', ['Testing the larger band second so it is never reached.', 'Off-by-one on the boundary value.', 'Using `IFERROR` to hide a mistake instead of a missing value.'], '=IF(B2<=1,5,IF(B2<=5,9,15))'),
  n('xl.lookup', 'Spreadsheets: look it up, do not copy it', 'A lookup finds a row by its key and returns another column. Exact match (`FALSE`/0) for codes and names; approximate match (`TRUE`/1) for bands, and only on sorted data. When the key is not in the first column, use INDEX/MATCH or XLOOKUP. Decide what a missing key should show.', ['Approximate match on unsorted data.', 'Forgetting `$` so the table range slides down the rows.', 'Returning the wrong column number.'], '=IFERROR(VLOOKUP(A2,Catalog!$A$2:$C$6,3,FALSE),"unknown")'),
  n('xl.conditional', 'Spreadsheets: totals with conditions', '`SUMIFS`, `COUNTIFS` and `AVERAGEIFS` answer “how much of this kind?” without filtering by hand. The sum range comes first in `SUMIFS`; every condition must hold. A share is one conditional total divided by another.', ['Putting the sum range last in `SUMIFS`.', 'Averaging the whole column instead of the group.', 'A test like ">100" when the boundary should be included.'], '=SUMIFS(D2:D7,A2:A7,"East",C2:C7,"Tools")'),
  n('xl.cleaning', 'Spreadsheets: clean before you trust', 'Real data arrives with stray spaces, odd capitals, numbers stored as text and codes of varying length. Clean into a new column, find pieces relative to a separator with `FIND` rather than counting characters, and convert with `VALUE`. Build dates with `DATE` rather than joining text.', ['Counting characters when the lengths vary.', 'Leaving numbers as text so totals skip them.', 'Numbering weekdays from Sunday when the task means Monday first.'], '=VALUE(MID(A2,FIND("-",A2)+1,4))'),
  n('xl.pivot', 'Spreadsheets: summarise, then chart the summary', 'A pivot groups rows and aggregates one field; choose the aggregation that matches the question (sum, count, average) and a source range that includes the header and every row. A chart answers one question: line for change over time, column for comparison, pie only for parts of a whole.', ['A source range that stops short of the last row.', 'Summing when the question asks for a count or an average.', 'Charting raw rows instead of the summary.'], 'Pivot: rows Region, values sum of Revenue'),
  n('xl.modeling', 'Spreadsheets: a model follows its inputs', 'A model has inputs, calculations and outputs. Change any input and every output should update correctly; if one does not, a number was typed where a reference belonged. For projections, each row builds on the previous one, with locked assumption cells. Test with extreme inputs.', ['Assumptions typed into formulas.', 'Unlocked references that drift when copied.', 'Letting quantities go negative when they cannot.'], '=MAX(0,B6-$B$2+$B$3)'),

  // --------------------------------------------------------------- Git
  n('git.basics', 'Git: a commit is a snapshot you can name', 'Git records snapshots. Files move through three places: your working folder, the staging area (`git add`), and history (`git commit`). Always look with `git status` before you commit, and write a message that says what changed and why.', ['Committing without staging, or staging too much.', 'Vague messages such as “fix”.', 'Forgetting to check status first.'], 'git status\ngit add notes.txt\ngit commit -m "Add notes"'),
  n('git.history', 'Git: history is for reading and safe undo', '`git log` and `git diff` let you read what happened. To undo, choose by whether the commit is shared: `restore` for uncommitted changes, `reset` for private commits, `revert` for anything others may have. `revert` adds a new commit; it never rewrites.', ['Using `reset --hard` on shared history.', 'Discarding changes with `restore` that you meant to keep.', 'Reading only the latest commit.'], 'git log --oneline\ngit revert HEAD --no-edit'),
  n('git.branches', 'Git: a branch is a movable label', 'Branches let you try things without touching `main`. Know where HEAD is before you change anything: `git branch` shows it. `switch -c` creates and moves in one step. A branch only holds what you committed on it.', ['Committing on the wrong branch.', 'Switching with uncommitted changes you meant to bring along.', 'Forgetting which branch you are on.'], 'git switch -c experiment\ngit branch'),
  n('git.merging', 'Git: a conflict is a decision', 'When both branches changed the same lines, Git cannot choose for you. The file shows both versions between markers. Decide what the file should say, edit it, delete every marker, then `git add` and commit. `git merge --abort` goes back to before.', ['Leaving a `<<<<<<<` marker in the file.', 'Keeping one side without reading the other.', 'Forgetting to `git add` the resolved file.'], 'git merge feature'),
  n('git.collaboration', 'Git: share through a remote, with review', 'A remote (`origin`) is a copy everyone pushes to. `fetch` downloads without changing your work; `pull` fetches and merges. A rejected push means someone else pushed first: pull, resolve, push again. Changes reach `main` through a reviewed pull request.', ['Force-pushing a shared branch.', 'Pushing to `main` directly.', 'Pulling with uncommitted work.'], 'git fetch\ngit pull'),
  n('git.workflow', 'Git: the professional loop', 'Small branches, clear messages, frequent commits, review before merge, and never rewrite what others have seen. Start from up-to-date `main`, branch, work, push, open a pull request, address feedback, merge, delete the branch.', ['Huge branches that live for weeks.', 'Mixing unrelated changes in one commit.', 'Rewriting published history.'], 'git switch -c fix-alarm\ngit commit -m "Fix alarm threshold"'),

  // --------------------------------------------------------------- Statistics
  n('stat.descriptive', 'Statistics: which “typical”?', 'The mean uses every value, so one extreme value drags it; the median ignores how extreme the extremes are; the mode is the most common value (there can be several). Choose by the question and say which you used. Missing values are missing, not zero.', ['Reporting the mean of a skewed set as “typical”.', 'Treating missing values as zeros.', 'Returning one mode when several tie.'], 'import statistics\nprint(statistics.median([4, 8, 6, 5, 3, 50]))'),
  n('stat.spread', 'Statistics: how much do values vary?', 'Two sets with the same mean can behave completely differently. The standard deviation is the typical distance from the mean: divide by n for a whole population, by n − 1 for a sample. Outliers sit outside the IQR fences (1.5 × IQR beyond the quartiles): treat them as questions, not errors.', ['Using n when the data is a sample.', 'Rounding before the final step.', 'Flagging values exactly on a fence.'], 'import math\nmath.sqrt(sum((v - m) ** 2 for v in values) / (len(values) - 1))'),
  n('stat.distributions', 'Statistics: shape, bins and percentiles', 'Count values per bin with integer division (`v // width`). The last bin must reach the largest value, and empty bins still exist. A nearest-rank percentile sorts the data and takes the value at rank ceil(p/100 × n), counting from 1.', ['Dropping empty bins.', 'Counting ranks from 0.', 'Letting a value on a boundary fall in the wrong bin.'], 'counts[int(v // width)] += 1'),
  n('stat.visualization', 'Statistics: a chart is a claim', 'Start bar charts at zero; label the axes with units; give the chart a title; do not draw a trendline through a handful of points; avoid dual axes. Choose the chart by the question (trend: line, comparison: bar, parts of a whole: a few-slice pie).', ['Truncated bar axes.', 'Too many pie slices.', 'Missing units.'], 'bar axis: (0, next multiple of 10)'),
  n('stat.correlation', 'Statistics: moving together is not causing', 'Pearson’s r measures straight-line association from −1 to +1. It is undefined when one side does not vary. One outlier can create or destroy a correlation, and a strong r says nothing about why. Report r together with how many points it came from.', ['Forgetting the undefined cases.', 'Comparing r values by sign instead of size.', 'Reading causation into a correlation.'], 'import statistics\nstatistics.correlation(x, y)'),
  n('stat.sampling', 'Statistics: how you sample matters more than how much', 'A random sample gives every member the same chance; a stratified sample samples each group separately so small groups are not lost. Seed the generator so the sample can be audited. The 95% margin of error of a proportion is 1.96 × √(p(1 − p)/n): quadruple n to halve it.', ['Taking the first k records and calling it random.', 'Forgetting to cap a small group.', 'Expecting a bigger sample to fix a biased one.'], 'import random\nrandom.Random(42).sample(items, 3)'),
  n('stat.probability', 'Statistics: chance and expected value', 'Probabilities multiply for independent events. “At least one” is easiest as 1 − P(none). Expected value is Σ value × probability, and the probabilities must add to 1. A seeded simulation should agree with the exact answer; if they disagree, one is wrong.', ['Adding probabilities for “at least one”.', 'Comparing floats with `==` for a sum of 1.', 'Forgetting to seed the simulation.'], '1 - (1 - p) ** n'),
  n('stat.inference', 'Statistics: signal or noise?', 'A sample mean wobbles by about s/√n. A 95% interval is mean ± 1.96 standard errors. If two groups’ intervals do not overlap the difference is clear; if they do, the honest answer is “no clear difference”, which is not the same as “the same”. A real difference may still be too small to matter.', ['Claiming a winner from overlapping intervals.', 'Using n instead of n − 1 for the standard deviation.', 'Ignoring direction when the question asks about improvement.'], 'mean ± 1.96 * s / sqrt(n)'),
  n('stat.analysis', 'Statistics: question, data, describe, quantify, conclude', 'Start from the decision the analysis supports. Read and look at the data, describe each group, quantify the uncertainty, and state a verdict the data can carry, with its limits. Format the report so someone else can read it.', ['Comparing two averages with no uncertainty.', 'Skipping a look at the raw data.', 'A verdict stronger than the evidence.'], 'per group: n, mean, interval, then verdict'),
  n('de.analytics', 'Analytics: the unit of analysis', 'Decide what one row means (per machine? per customer? per order?) before you aggregate. Let SQL produce exactly one row per unit, then judge the numbers in Python. Every filter (status, missing events) changes the question: state your choices.', ['Aggregating per order when the question is per customer.', 'Letting idle groups change the quartiles.', 'Counting cancelled orders.'], 'SELECT customer, SUM(amount) ... GROUP BY customer'),
];
