/**
 * End-to-end tests of the PLAYABLE 3D WORLD (real Chromium, software WebGL, the production build). Run: node e2e/play.mjs   (after npm run build)
 * Movement uses real key presses; long walks use the e2e-only teleport hook (enabled by localStorage 'codequest.e2e').
 * Usage: E2E_ONLY='substr|substr' node e2e/play.mjs
 */
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync } from 'node:fs';
import { chromium } from 'playwright-core';
import { solutions as solutionsPhase1 } from '../src/content/python/solutions.testdata.ts';
import { solutionsPhase2Python } from '../src/content/python/solutions.phase2.testdata.ts';
import { solutionsPhase3Python } from '../src/content/python/solutions.phase3.testdata.ts';
import { solutionsPhase4Python } from '../src/content/python/solutions.phase4.testdata.ts';
import { trainingSolutions } from '../src/content/training/solutions.testdata.ts';
import { solutionsSql } from '../src/content/sql/solutions.testdata.ts';
import { solutionsPhase3Sql } from '../src/content/sql/solutions.phase3.testdata.ts';
import { solutionsPhase4Sql } from '../src/content/sql/solutions.phase4.testdata.ts';
import { bossSolutions } from '../src/content/boss/solutions.testdata.ts';
import { sheetSolutions } from '../src/content/sheet/solutions.testdata.ts';
import { simulateGame, ourTeam, opposingTeam } from '../src/play/logic/baseballSim.ts';
import { readFileSync } from 'node:fs';

const solutions = { ...solutionsPhase1, ...solutionsPhase2Python, ...solutionsPhase3Python, ...solutionsPhase4Python, ...trainingSolutions, ...solutionsSql, ...solutionsPhase3Sql, ...solutionsPhase4Sql, ...bossSolutions };
/** Reference web solutions (generated by scripts/e2e-fixtures.ts) and saves prepared with the real game actions. */
const fixtures = JSON.parse(readFileSync(new URL('./.fixtures.json', import.meta.url), 'utf8'));
const saves = JSON.parse(readFileSync(new URL('./.saves.json', import.meta.url), 'utf8'));
const PORT = 4181;
const BASE = `http://localhost:${PORT}/`;
const SHOTS = new URL('./screenshots/', import.meta.url).pathname;
mkdirSync(SHOTS, { recursive: true });
const assert = (c, m) => { if (!c) throw new Error('assertion failed: ' + m); };
const eq = (a, b, m) => { if (a !== b) throw new Error(`${m}: expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`); };
function chromiumPath() {
  if (process.env.CHROMIUM_PATH) return process.env.CHROMIUM_PATH;
  const root = process.env.PLAYWRIGHT_BROWSERS_PATH || '/opt/pw-browsers';
  const dir = existsSync(root) ? readdirSync(root).find((d) => d.startsWith('chromium-')) : undefined;
  return dir ? `${root}/${dir}/chrome-linux/chrome` : undefined;
}
let passed = 0; const failures = [];
async function test(name, fn) {
  if (process.env.E2E_ONLY && !process.env.E2E_ONLY.split('|').some((k) => name.includes(k))) return;
  const t = Date.now();
  try { await fn(); passed++; console.log(`  ✓ ${name} (${Date.now() - t}ms)`); } catch (e) { failures.push(name); try { await lastPage?.screenshot({ path: SHOTS + 'play-FAILED.png' }); } catch { /* page already closed */ } console.log(`  ✗ ${name}\n      ${String(e.message).split('\n').slice(0, 5).join('\n      ')}${lastPage?.errors?.length ? '\n      page errors: ' + lastPage.errors.slice(0, 3).join(' | ').slice(0, 600) : ''}`); try { await lastPage?.context().close(); } catch { /* already closed */ } }
}
let browser; let lastPage = null;
const tid = (p, id) => p.getByTestId(id);

/** A new player in the 3D world. */
async function newGame(opts = {}) {
  const ctx = await browser.newContext({ viewport: { width: 1100, height: 700 }, reducedMotion: opts.reduced ? 'reduce' : 'no-preference' });
  const page = await ctx.newPage();
  page.errors = []; lastPage = page;
  page.on('pageerror', (e) => page.errors.push(String(e)));
  page.on('console', (m) => { if (m.type() === 'error') page.errors.push(m.text()); if (process.env.E2E_DEBUG && m.text().startsWith('DBG')) console.log('   ', m.text()); });
  await page.addInitScript(() => { try { localStorage.setItem('codequest.e2e', '1'); } catch { /* sandboxed iframe */ } });
  if (opts.save) await page.addInitScript((s) => { if (!localStorage.getItem('codequest.save')) localStorage.setItem('codequest.save', s); }, opts.save);
  await page.goto(BASE);
  if (!opts.save) { await tid(page, 'name-input').fill(opts.name ?? 'Ada'); await tid(page, 'begin').click(); }
  await page.locator('[data-testid=play][data-ready="1"]').waitFor({ timeout: 30000 });
  if (!opts.welcome && await tid(page, 'welcome-start').count()) { await tid(page, 'welcome-start').click(); await page.waitForTimeout(600); } // input is re-enabled one render after the card closes
  // software WebGL renders this scene at a few frames per second; the game caps a frame at 0.1 s, so run it faster to keep the timing-based checks meaningful
  await page.evaluate(() => { window.__cq3d.stage.timeScale = 4; });
  return page;
}
const st = (p) => p.evaluate(() => window.__cq3d.state());
const save = (p) => p.evaluate(() => JSON.parse(localStorage.getItem('codequest.save')));
const tp = (p, x, z, ry = 0) => p.evaluate(([x, z, ry]) => window.__cq3d.teleport(x, z, ry), [x, z, ry]);
const go = (p, scene, spawn) => p.evaluate(([s, sp]) => window.__cq3d.travel(s, sp), [scene, spawn]);
/** A cinematic (letterbox, subtitles) locks the controls: skip it (Space) as a player may, and wait until the world is theirs again. */
async function skipCine(p) {
  await p.waitForTimeout(350);
  for (let i = 0; i < 20; i++) {
    if ((await tid(p, 'cine').getAttribute('data-active').catch(() => '0')) !== '1') return;
    await p.keyboard.press('Space'); await p.waitForTimeout(350);
  }
}
/** After a pass: the world may answer by itself (the terminal steps aside, a cinematic plays); wait until the lesson is back and the world is quiet. */
async function waitTerminalBack(p, timeout = 90000) {
  await p.waitForTimeout(1300);
  await p.waitForFunction(() => { const t = document.querySelector('[data-testid=play-terminal]'); const c = document.querySelector('[data-testid=cine]'); return !!t && !t.hidden && c?.getAttribute('data-active') !== '1'; }, null, { timeout });
}
/** Wait for a cinematic to start and play to its end without skipping (the real thing). */
async function watchCine(p, timeout = 60000) {
  await p.waitForFunction(() => document.querySelector('[data-testid=cine]')?.getAttribute('data-active') === '1', null, { timeout: 15000 });
  await p.waitForFunction(() => document.querySelector('[data-testid=cine]')?.getAttribute('data-active') === '0', null, { timeout });
}
/** Press E in the world and wait for the prompt target to be the one we expect. */
async function interact(p, target) {
  await skipCine(p);
  await p.locator(`[data-testid=play-prompt][data-target="${target}"]`).waitFor({ timeout: 8000 });
  await p.keyboard.press('e');
}
async function talkThrough(p, { accept = false } = {}) {
  await tid(p, 'play-dialogue').waitFor();
  for (let i = 0; i < 12; i++) {
    if (await tid(p, 'dialogue-accept').count()) { await tid(p, accept ? 'dialogue-accept' : 'dialogue-decline').click(); break; }
    if (await tid(p, 'dialogue-close').count()) { await tid(p, 'dialogue-close').click(); break; }
    await tid(p, 'dialogue-next').click();
  }
  await tid(p, 'play-dialogue').waitFor({ state: 'detached' });
}
async function stepKind(p, n) { const b = p.locator(`.lesson-body[data-step="${n}"]`); await b.waitFor(); return b.getAttribute('data-kind'); }


/** Types a web project into the HTML/CSS/JS editors (skipping locked tabs). */
async function setWebFiles(p, files) {
  for (const tab of ['html', 'css', 'js']) {
    const button = tid(p, `web-tab-${tab}`);
    if ((await button.innerText()).includes('🔒')) continue;
    await button.click();
    await setCode(p, files[tab] ?? '');
  }
}
/** Enters a spreadsheet solution through the real grid (click a cell, type in the formula bar). */
async function setSheet(p, sol) {
  for (const [ref, v] of Object.entries(sol.cells ?? {})) {
    await p.locator(`td[data-cell="${ref}"]`).click();
    await tid(p, 'formula-bar').fill(String(v));
    await tid(p, 'formula-bar').press('Enter');
  }
}
/** Solves whatever challenge is on screen with its reference solution, in whichever editor it uses. */
async function solve(p, cid, index = 0) {
  if (cid.startsWith('web-')) return setWebFiles(p, fixtures.web[cid]);
  if (cid.startsWith('xl-')) return setSheet(p, sheetSolutions[cid].valid[index] ?? sheetSolutions[cid].valid[0]);
  return setCode(p, (solutions[cid].valid[index] ?? solutions[cid].valid[0]));
}
async function submitPass(p, cid) { await solve(p, cid); await tid(p, 'submit').click(); await tid(p, 'result').waitFor({ timeout: 60000 }); assert(await p.locator('.result.pass').count() === 1, `challenge ${cid} should pass`); }
async function runDemo(p) { await tid(p, 'run').click(); await p.locator('[data-testid=stdout], [data-testid=stderr], [data-testid=sql-results], [data-testid=web-preview] iframe, [data-testid=sheet], [data-testid=terminal]').first().waitFor({ timeout: 60000 }); }

/** Play the open lesson from its first step to "Complete lesson", solving challenges with the reference solutions. */
async function playLesson(p) {
  for (let step = 0; step < 30; step++) {
    const kind = await stepKind(p, step);
    if (kind === 'challenge') { const cid = await tid(p, 'briefing').getAttribute('data-challenge'); await submitPass(p, cid); if (await p.locator('[data-testid=play-terminal]').count()) await waitTerminalBack(p); }
    else if (kind === 'demo') await runDemo(p);
    if (await tid(p, 'finish').count()) { await tid(p, 'finish').click(); return; }
    await tid(p, 'continue').click();
  }
  throw new Error('lesson did not finish');
}


async function setCode(p, code) { await p.locator('.cm-content').first().click(); await p.keyboard.press('Control+A'); if (code === '') await p.keyboard.press('Delete'); else await p.keyboard.insertText(code); }
/** Writes completed lessons into the real save and reloads (fast route to later steps). */
async function seedLessons(p, ids) {
  // applied by an init script AFTER the page's own pagehide flush has saved, so the flush cannot overwrite the seeded lessons
  const tag = 'seed-' + Math.random();
  await p.addInitScript(([ids, tag]) => { if (sessionStorage.getItem(tag)) return; sessionStorage.setItem(tag, '1'); const s = JSON.parse(localStorage.getItem('codequest.save')); for (const id of ids) s.learning.lessons[id] = { stepIndex: 99, completed: true }; localStorage.setItem('codequest.save', JSON.stringify(s)); }, [ids, tag]);
  await p.reload();
  await p.locator('[data-testid=play][data-ready="1"]').waitFor({ timeout: 30000 }); await p.evaluate(() => { window.__cq3d.stage.timeScale = 4; });
  if (await tid(p, 'welcome-start').count()) await tid(p, 'welcome-start').click(); // a save seeded before the card was dismissed still lacks the flag
}
async function advanceToChallengeId(p, id) {
  for (let i = 0; i < 14; i++) {
    const kind = await stepKind(p, i);
    if (kind === 'challenge') {
      const cid = await tid(p, 'briefing').getAttribute('data-challenge');
      if (cid === id) return;
      await setCode(p, solutions[cid].valid[0]); await tid(p, 'submit').click(); await p.locator('.result.pass').waitFor({ timeout: 30000 });
    } else if (kind === 'demo') { await tid(p, 'run').click(); await p.locator('[data-testid=stdout], [data-testid=stderr]').first().waitFor({ timeout: 30000 }); }
    await tid(p, 'continue').click();
  }
  throw new Error('challenge ' + id + ' not reached');
}
/** Plays a whole training plan with the reference solutions until the completion panel appears. */
async function playTraining(p) {
  for (let guard = 0; guard < 120; guard++) {
    if (await tid(p, 'training-complete').count()) return;
    if (await tid(p, 'training-predict').count()) { for (let i = 0; i < 4 && !(await tid(p, 'predict-right').count()); i++) await tid(p, `predict-${i}`).click(); await tid(p, 'training-read').click(); continue; }
    if (await tid(p, 'training-read').count()) { await tid(p, 'training-read').click(); continue; }
    if (await tid(p, 'training-start-step').count()) await tid(p, 'training-start-step').click();
    await tid(p, 'briefing').or(tid(p, 'training-read')).or(tid(p, 'training-predict')).or(tid(p, 'training-complete')).first().waitFor({ timeout: 15000 });
    if (!(await tid(p, 'briefing').count())) continue; // a reading/prediction card or the end arrived while we looked: handle it on the next pass
    const cid = await tid(p, 'briefing').getAttribute('data-challenge');
    await setCode(p, solutions[cid].valid[0]);
    await tid(p, 'submit').click();
    await tid(p, 'result').or(tid(p, 'training-intro')).or(tid(p, 'training-read')).or(tid(p, 'training-complete')).first().waitFor({ timeout: 60000 });
    if (await tid(p, 'result').count() && await p.locator('.result.fail').count()) throw new Error('the reference solution for ' + cid + ' failed in training');
    await p.waitForTimeout(150);
  }
  throw new Error('training did not finish');
}

async function main() {
  const server = spawn('npx', ['vite', 'preview', '--port', String(PORT), '--strictPort'], { stdio: 'ignore' });
  await new Promise((r) => setTimeout(r, 2500));
  browser = await chromium.launch({ executablePath: chromiumPath(), args: ['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
  try {
    console.log('3D world: robotics vertical slice');

    await test('A new player lands in the 3D world and can walk with WASD and the arrow keys (collision stops them at the wall)', async () => {
      const p = await newGame();
      eq((await st(p)).scene, 'robotics-atrium', 'a new player starts in the Robotics Academy atrium');
      // they are told what to do and where, and the world shows the way
      await tid(p, 'objective-title').waitFor();
      assert((await tid(p, 'objective-text').innerText()).includes('Repair Console'), 'the objective names the Python lesson\'s console, from the learning record');
      assert((await tid(p, 'objective-where').innerText()).includes('Maintenance Bay'), 'and where: the door to take');
      assert((await st(p)).markers.length >= 0, 'markers exist');
      await go(p, 'maintenance-bay');
      const a = await st(p);
      await p.keyboard.down('w'); await p.waitForTimeout(1200); await p.keyboard.up('w');
      const b = await st(p);
      assert(b.z < a.z - 0.4, `W moves forward (north): ${a.z} -> ${b.z}`);
      await p.keyboard.down('ArrowRight'); await p.waitForTimeout(1000); await p.keyboard.up('ArrowRight');
      assert((await st(p)).x > b.x + 0.3, 'the right arrow moves right');
      // run into the north wall: position is clamped inside the room
      await tp(p, 0, -6); await p.keyboard.down('w'); await p.keyboard.down('Shift'); await p.waitForTimeout(6000); await p.keyboard.up('Shift'); await p.keyboard.up('w');
      assert((await st(p)).z >= -9 + 0.3, 'cannot leave the room');
      assert((await st(p)).z <= -8, 'and stopped at the wall, not somewhere in the middle');
      await p.screenshot({ path: SHOTS + 'play-01-bay.png' });
      await p.context().close();
    });

    await test('Lesson flow: guided to the console, solve the lesson, the world answers by itself (no button, no errand), the lesson comes back, the quest is taken up by doing the work', async () => {
      const p = await newGame();
      await p.evaluate(() => { window.__tl = []; const t0 = performance.now(); new MutationObserver(() => { const c = document.querySelector('[data-testid=cine]'); const b = document.querySelector('[data-testid=cine-banner]'); const term = document.querySelector('[data-testid=play-terminal]'); window.__tl.push([Math.round(performance.now() - t0), c?.getAttribute('data-active'), b ? b.textContent.slice(0, 40) : '', term ? (term.hidden ? 'hid' : 'vis') : 'none']); }).observe(document.body, { subtree: true, childList: true, attributes: true }); });
      // the guide names the Python lesson and the console, no NPC needed
      assert((await tid(p, 'play-tracker').getAttribute('data-objective')) === 'lesson', 'the objective is the next lesson');
      assert((await tid(p, 'objective-text').innerText()).includes('Repair Console'), 'it names the console');
      await go(p, 'maintenance-bay');
      eq(JSON.stringify(await p.evaluate(() => window.__cq3d.dynStates('bolt'))), '[]', 'Bolt is still dead');
      await tp(p, 1.5, -5.4, 0);
      await interact(p, 'bolt-console');
      await tid(p, 'play-terminal').waitFor();
      await p.screenshot({ path: SHOTS + 'play-02-terminal.png' });
      await tid(p, 'terminal-next').click();
      await tid(p, 'lesson').waitFor();
      // everything up to the final challenge; then the pass itself is the trigger
      for (let step = 0; step < 30; step++) {
        const kind = await stepKind(p, step);
        if (kind === 'challenge') { const cid = await tid(p, 'briefing').getAttribute('data-challenge'); await solve(p, cid); await tid(p, 'submit').click(); await tid(p, 'result').waitFor({ timeout: 60000 }); if (await tid(p, 'finish').count() || await p.evaluate(() => document.querySelector('[data-testid=cine]')?.getAttribute('data-active') === '1')) break; }
        else if (kind === 'demo') await runDemo(p);
        if (await tid(p, 'finish').count()) break;
        await tid(p, 'continue').click();
      }
      // no click: the terminal steps aside and the world answers
      await p.waitForFunction(() => document.querySelector('[data-testid=cine]')?.getAttribute('data-active') === '1', null, { timeout: 15000 });
      assert(await tid(p, 'play-terminal').isHidden(), 'the terminal stepped aside by itself');
      assert((await tid(p, 'terminal-look').count()) === 0, 'there is no "watch" button');
      await tid(p, 'cine-subtitle').waitFor({ timeout: 15000 });
      await p.screenshot({ path: SHOTS + 'play-03-bolt-eyes.png' });
      await p.waitForFunction(() => window.__cq3d.dynStates('bolt').includes('eyes'), null, { timeout: 15000 });
      await tid(p, 'cine-banner').waitFor({ timeout: 30000 }).catch(async (e) => { console.log('DEBUG', JSON.stringify((await p.evaluate(() => window.__tl)).filter((x, i, a) => i === 0 || a[i - 1].slice(1).join() !== x.slice(1).join())), await p.evaluate(() => document.querySelector('[data-testid=cine]')?.outerHTML.slice(0, 600))); throw e; });
      assert((await tid(p, 'cine-banner').innerText()).includes('Silent in the Bay'), 'the quest completion is celebrated (it was taken up by the work)');
      await p.screenshot({ path: SHOTS + 'play-03b-quest-complete.png' });
      // straight back into the lesson, where it was
      await waitTerminalBack(p);
      assert(await tid(p, 'lesson').count() === 1, 'the lesson is still open, not a room and not an NPC');
      assert((await p.evaluate(() => !!document.querySelector('[data-testid=play-dialogue]'))) === false, 'no conversation was needed');
      let s = await save(p);
      eq(s.quests['q-bay-briefing']?.status, 'complete', 'the quest completes through code');
      assert(s.stats.xp > 0, 'reward paid');
      if (await tid(p, 'finish').count()) await tid(p, 'finish').click();
      await tid(p, 'terminal-close').click();
      // persistence: reload; Bolt's eyes are still on, instantly
      await p.reload();
      await p.locator('[data-testid=play][data-ready="1"]').waitFor({ timeout: 30000 }); await p.evaluate(() => { window.__cq3d.stage.timeScale = 4; });
      assert((await p.evaluate(() => window.__cq3d.dynStates('bolt'))).includes('eyes'), 'the repair persists across a reload');
      await p.context().close();
    });

    await test('Failure: wrong code costs Focus and plays no world reaction, sends the player to the Simulation Room; training returns them to the same console with a NEW problem, and the fix then works', async () => {
      const p = await newGame();
      await go(p, 'maintenance-bay');
      await seedLessons(p, ['py-01-first-program', 'py-02-fixing-errors', 'py-03-variables', 'py-04-strings']);
      await go(p, 'maintenance-bay');
      await tp(p, 1.5, -5.4, 0);
      await interact(p, 'bolt-console');
      await tid(p, 'terminal-next').click();
      await tid(p, 'lesson').waitFor();
      await advanceToChallengeId(p, 'py-05-crates');
      const first = await tid(p, 'briefing').getAttribute('data-challenge');
      await setCode(p, 'print("nope")');
      await tid(p, 'submit').click();
      await tid(p, 'result').waitFor({ timeout: 30000 });
      assert((await tid(p, 'focus').innerText()).includes('50/100'), 'Focus dropped');
      // a failure is not acted out in the world: no cinematic, no malfunction, the terminal stays
      await p.waitForTimeout(2000);
      assert(await tid(p, 'play-terminal').isVisible(), 'the lesson stays on screen');
      assert((await p.evaluate(() => document.querySelector('[data-testid=cine]')?.getAttribute('data-active'))) !== '1', 'no cinematic after a failed answer');
      assert(!(await p.evaluate(() => window.__cq3d.dynStates('bolt'))).includes('servo'), 'a failure repairs nothing');
      await tid(p, 'terminal-close').click();
      // the Mentor's single button leads to the Simulation Room
      await tp(p, 1.5, -5.4, 0);
      await interact(p, 'bolt-console');
      await tid(p, 'terminal-blocked').waitFor();
      await tid(p, 'go-training').click();
      // arriving plays the training scene by itself, with no click: the camera is taken, then the console opens
      await tid(p, 'cine').waitFor({ state: 'attached' });
      await p.waitForFunction(() => document.querySelector('[data-testid=cine]')?.getAttribute('data-active') === '1', null, { timeout: 8000 });
      await tid(p, 'play-training').waitFor({ timeout: 30000 });
      eq((await st(p)).scene, 'sim-room', 'the player is in the Simulation Room');
      await tid(p, 'start-training').click();
      await tid(p, 'training-run').waitFor();
      await playTraining(p);
      await tid(p, 'focus-restored').waitFor();
      assert((await tid(p, 'focus').innerText()).includes('100/100'), 'Focus is back');
      await tid(p, 'training-return-btn').click();
      // back at the same console, same lesson, a DIFFERENT problem
      await tid(p, 'play-terminal').waitFor();
      eq((await st(p)).scene, 'maintenance-bay', 'returned to the bay');
      await tid(p, 'lesson').waitFor();
      const second = await tid(p, 'briefing').getAttribute('data-challenge');
      assert(second !== first, 'a new variant: ' + first + ' -> ' + second);
      await setCode(p, solutions[second].valid[0]);
      await tid(p, 'submit').click();
      await p.locator('.result.pass').waitFor({ timeout: 30000 });
      await p.context().close();
    });

    console.log('3D world: the hub, the map and the settings');

    await test('Menu bar: pushing the mouse up reveals the clickable top bar; going back over the world captures the mouse again', async () => {
      const p = await newGame();
      const state = () => p.evaluate(() => [!!document.pointerLockElement, document.querySelector('[data-testid=play]').className]);
      const push = async () => { await p.mouse.move(550, 400); for (let i = 0; i < 9; i++) await p.mouse.move(550, 400 - (i + 1) * 60); await p.waitForTimeout(600); };
      await p.mouse.move(550, 400); await p.mouse.down(); await p.mouse.up(); await p.waitForTimeout(400);
      let [locked, cls] = await state(); assert(locked && cls.includes('mouse-captured'), 'the mouse is captured while playing');
      await push();
      [locked, cls] = await state(); assert(!locked && cls.includes('bar-revealed'), 'pushing up gives the cursor back');
      await p.mouse.move(900, 40); await p.waitForTimeout(200);
      await p.mouse.move(700, 300); await p.waitForTimeout(300);
      [locked] = await state(); assert(locked, 'back over the world the mouse is captured again');
      await push(); await p.mouse.move(1000, 40); await p.waitForTimeout(200);
      await p.getByText('Skills').click({ timeout: 5000 });
      await tid(p, 'play-panel').waitFor({ timeout: 5000 }).catch(() => p.getByText('Adventurer').waitFor({ timeout: 5000 }));
      await p.context().close();
    });

    await test('First visit: the welcome card appears once; the Field Manual opens with H; the dispatch board shows the Daily in-world', async () => {
      const p = await newGame({ welcome: true });
      await tid(p, 'play-welcome').waitFor();
      await tid(p, 'welcome-start').click();
      await tid(p, 'play-welcome').waitFor({ state: 'detached' });
      await p.waitForTimeout(400); // input is re-enabled one render after the card closes
      await p.keyboard.press('h');
      await tid(p, 'play-manual').waitFor();
      await tid(p, 'manual-close').click();
      await go(p, 'plaza');
      await tp(p, -5, 5.4, Math.PI);
      await interact(p, 'daily-board');
      await tid(p, 'play-daily').waitFor();
      assert((await tid(p, 'dispatch-line').innerText()).includes('Dispatch'), 'the Daily is framed as a dispatch');
      await tid(p, 'daily-overlay-close').click();
      await p.reload();
      await p.locator('[data-testid=play][data-ready="1"]').waitFor({ timeout: 30000 }); await p.evaluate(() => { window.__cq3d.stage.timeScale = 4; });
      assert((await tid(p, 'play-welcome').count()) === 0, 'the welcome is not shown again');
      await p.context().close();
    });
    await test('Hub: walk through a gate to another world, open the world map, see every world with its state, and fast-travel', async () => {
      const p = await newGame();
      await go(p, 'plaza');
      await tp(p, -19, 0, Math.PI / 2);
      await interact(p, 'exit:to-robotics');
      await p.waitForFunction(() => window.__cq3d.state().scene === 'robotics-atrium');
      await go(p, 'plaza');
      await p.keyboard.press('m');
      await tid(p, 'play-map').waitFor();
      for (const w of ['robotics', 'academy', 'ballpark', 'racing', 'summit']) await tid(p, `map-${w}`).waitFor();
      eq(await tid(p, 'map-robotics').getAttribute('data-state'), 'open', 'every foundation world is open from the start');
      assert((await tid(p, 'map-gate-summit').innerText()).length > 10, 'the Summit says what it needs');
      assert(await tid(p, 'travel-summit').isDisabled(), 'and cannot be travelled to yet');
      await p.screenshot({ path: SHOTS + 'play-05-map.png' });
      await tid(p, 'travel-ballpark').click();
      await p.waitForFunction(() => window.__cq3d.state().scene === 'ballpark');
      await p.context().close();
    });

    await test('Settings: the pause menu saves sound, motion and quality; the classic view is one button away; the position survives a reload', async () => {
      const p = await newGame();
      await go(p, 'lantern-courtyard');
      await tp(p, 6, 5, 1);
      await p.keyboard.press('Escape');
      await tid(p, 'play-pause').waitFor();
      await p.getByLabel(/Sound on/).uncheck();
      await tid(p, 'pause-quality').selectOption('low');
      const sv = await save(p);
      eq(sv.play.settings.muted, true, 'mute saved'); eq(sv.play.settings.quality, 'low', 'quality saved');
      await tid(p, 'pause-resume').click();
      await tid(p, 'play-pause').waitFor({ state: 'detached' });
      await p.waitForTimeout(3500); // the position is saved every few seconds
      await p.reload();
      await p.locator('[data-testid=play][data-ready="1"]').waitFor({ timeout: 30000 }); await p.evaluate(() => { window.__cq3d.stage.timeScale = 4; });
      const after = await st(p);
      eq(after.scene, 'lantern-courtyard', 'back in the same place');
      assert(Math.hypot(after.x - 6, after.z - 5) < 1.5, `at the same spot: ${after.x},${after.z}`);
      await p.keyboard.press('Escape');
      await tid(p, 'play-pause').waitFor();
      assert((await tid(p, 'pause-classic').count()) === 0, 'the classic view is not a player-facing option');
      await p.context().close();
    });

    console.log('3D world: Lanternhollow Academy (HTML, CSS, JavaScript)');

    await test('Fantasy: explore the academy, talk to the Warden, accept a quest, write HTML at the Rune Lectern and the banner unfurls', async () => {
      const p = await newGame();
      await go(p, 'lantern-courtyard');
      await tp(p, 4.6, 2.2, 0);
      await interact(p, 'talk-teselle');
      await talkThrough(p, { accept: true });
      eq((await save(p)).quests['q-lantern-briefing']?.status, 'active', 'quest accepted');
      await tp(p, -3.5, 5.2, 0);
      await interact(p, 'dark-lantern');
      await talkThrough(p);
      await tp(p, 0, -11, 0);
      await interact(p, 'exit:to-hall');
      await p.waitForFunction(() => window.__cq3d.state().scene === 'spell-classroom');
      await tp(p, -5, 4.6, 0);
      await interact(p, 'rune-lectern');
      await tid(p, 'play-terminal').waitFor();
      await tid(p, 'terminal-next').click();
      await tid(p, 'lesson').waitFor();
      await playLesson(p);
      await tid(p, 'terminal-close').click();
      await p.waitForFunction(() => window.__cq3d.dynStates('banner').includes('unfurl'), null, { timeout: 15000 });
      await p.screenshot({ path: SHOTS + 'play-06-banner.png' });
      await p.context().close();
    });

    await test('Fantasy duel: an incantation that works wakes the orb; one that does not costs Focus and nothing happens in the world (no hint or answer is shown)', async () => {
      const p = await newGame({ save: JSON.stringify(saves.academy) });
      await go(p, 'arena');
      await tp(p, -7, 4.6, 0);
      await interact(p, 'spell-lectern');
      await tid(p, 'terminal-next').click();
      await tid(p, 'lesson').waitFor();
      // play web-15 up to its first graded (challenge-mode) problem and get it wrong on purpose
      for (let step = 0; step < 8; step++) {
        const kind = await stepKind(p, step);
        if (kind === 'challenge') {
          const cid = await tid(p, 'briefing').getAttribute('data-challenge');
          if (cid === 'web-15-parcel-class') break;
          await submitPass(p, cid);
        } else if (kind === 'demo') await runDemo(p);
        await tid(p, 'continue').click();
      }
      await setWebFiles(p, { html: '', css: '', js: '' });
      await tid(p, 'submit').click();
      await tid(p, 'result').waitFor({ timeout: 60000 });
      assert((await tid(p, 'focus').innerText()).includes('50/100'), 'a graded failure costs Focus');
      await p.waitForTimeout(1500);
      assert(await tid(p, 'play-terminal').isVisible(), 'a failed spell is not acted out: the lesson stays');
      await p.screenshot({ path: SHOTS + 'play-07-misfire.png' });
      assert(!(await p.evaluate(() => window.__cq3d.dynStates('hound'))).length, 'the Gloomhound is not hurt by a failed spell');
      await p.context().close();
    });

    console.log('3D world: Harborview Park (SQL, a lineup, a simulated game)');

    await test('Baseball: the analysis already done puts nine players on the field in your lineup, and the game that follows is the one the model predicts', async () => {
      const p = await newGame({ save: JSON.stringify(saves.baseball) });
      await go(p, 'ballpark');
      await p.waitForFunction(() => window.__cq3d.dynStates('team').includes('set'));
      await tp(p, 9.2, 0.6, Math.PI);
      await interact(p, 'talk-reyes');
      await talkThrough(p, { accept: true });
      await tp(p, 0, 8.6, 0);
      await interact(p, 'home-plate');
      await tid(p, 'sim-play').waitFor();
      await p.screenshot({ path: SHOTS + 'play-08-baseball-ready.png' });
      await tid(p, 'sim-play').click();
      await tid(p, 'sim-scoreboard').waitFor();
      await p.screenshot({ path: SHOTS + 'play-09-baseball-playing.png' });
      await tid(p, 'sim-result').waitFor({ timeout: 360000 });
      const expected = simulateGame(ourTeam(6, true), opposingTeam, 101);
      const text = await tid(p, 'sim-result').innerText();
      assert(text.includes(`${expected.us}–${expected.them}`), `the result is the model's: ${expected.us}-${expected.them} vs ${text}`);
      eq(await tid(p, 'sim-result').getAttribute('data-won'), expected.won ? '1' : '0', 'win or loss as predicted');
      await p.screenshot({ path: SHOTS + 'play-10-baseball-result.png' });
      await p.context().close();
    });

    await test('Cutaway: a passed SQL lesson shows the play at the ballpark and brings the player back to the same console, lesson open', async () => {
      const p = await newGame();
      await go(p, 'analytics-office');
      await tp(p, 0, -0.3, 0);
      const before = await st(p);
      await interact(p, 'analytics-console');
      await tid(p, 'play-terminal').waitFor();
      await tid(p, 'terminal-next').click();
      await tid(p, 'lesson').waitFor();
      // everything up to the last challenge: the pass is the trigger
      const scenes = []; await p.exposeFunction('__seen', (sc) => scenes.push(sc));
      await p.evaluate(() => { let last = ''; setInterval(() => { const sc = window.__cq3d.state().scene; if (sc !== last) { last = sc; window.__seen(sc); } }, 100); });
      for (let step = 0; step < 30; step++) {
        const kind = await stepKind(p, step);
        if (kind === 'challenge') { const cid = await tid(p, 'briefing').getAttribute('data-challenge'); await solve(p, cid); await tid(p, 'submit').click(); await tid(p, 'result').waitFor({ timeout: 60000 }); if (await tid(p, 'finish').count() || await p.evaluate(() => !!document.querySelector('[data-testid=cine]')?.getAttribute('data-active') && document.querySelector('[data-testid=cine]').getAttribute('data-active') === '1')) break; }
        else if (kind === 'demo') await runDemo(p);
        if (await tid(p, 'finish').count()) break;
        await tid(p, 'continue').click();
      }
      await p.waitForFunction(() => window.__cq3d.state().scene === 'ballpark', null, { timeout: 60000 });
      await p.screenshot({ path: SHOTS + 'play-11-cutaway-ballpark.png' });
      assert((await p.evaluate(() => window.__cq3d.dynStates('team'))).length >= 0, 'the team is on the field');
      await p.waitForFunction(() => window.__cq3d.state().scene === 'analytics-office', null, { timeout: 90000 });
      await waitTerminalBack(p);
      assert(await tid(p, 'lesson').count() === 1, 'the lesson is open again, where it was');
      const after = await st(p);
      assert(Math.hypot(after.x - before.x, after.z - before.z) < 0.5, `the player is back where they stood (${before.x},${before.z}) vs (${after.x},${after.z})`);
      assert(scenes.includes('ballpark') && scenes[scenes.length - 1] === 'analytics-office', 'office -> ballpark -> office: ' + scenes.join(', '));
      await p.context().close();
    });

    await test('Pack: buy gear at the plaza kiosk, it is worn at once, the I key opens the Pack to change it, and J opens the Journal', async () => {
      const seed = structuredClone(saves.baseball); seed.stats.coins = 500;
      const p = await newGame({ save: JSON.stringify(seed) });
      await go(p, 'plaza');
      await tp(p, -8.7, 8.2, Math.PI / 2);
      await interact(p, 'shop-kiosk');
      await tid(p, 'play-shop').waitFor();
      await tid(p, 'buy-lucky-cap').click();
      await p.waitForFunction(() => JSON.parse(localStorage.getItem('codequest.save')).play.gear.head === 'lucky-cap');
      let s = await save(p);
      eq(s.play.gear.head, 'lucky-cap', 'bought gear is worn');
      eq(s.stats.coins, 440, 'it cost coins');
      assert(!(await tid(p, 'buy-lucky-cap').isEnabled()), 'owned: cannot be bought twice');
      await tid(p, 'shop-close').click();
      await p.waitForTimeout(700);
      await p.keyboard.press('i');
      await tid(p, 'pack').waitFor();
      eq(await tid(p, 'slot-head').getAttribute('data-worn'), 'lucky-cap', 'the Pack shows what is worn');
      await p.screenshot({ path: SHOTS + 'play-13-pack.png' });
      await tid(p, 'takeoff-head').click();
      eq((await save(p)).play.gear.head, null, 'taken off');
      await p.keyboard.press('i');
      await tid(p, 'pack').waitFor({ state: 'detached' });
      await p.keyboard.press('j');
      await tid(p, 'quest-log').waitFor();
      assert((await p.locator('[data-testid^=journal-toggle-]').count()) >= 6, 'the journal lists every world');
      await p.keyboard.press('j');
      await tid(p, 'quest-log').waitFor({ state: 'detached' });
      assert(p.errors.length === 0, 'no page errors: ' + p.errors.join('|'));
      await p.context().close();
    });

    await test('Source data: a SQL lesson shows its own database (tables, links, real sample rows) and never a hidden twin', async () => {
      const p = await newGame();
      await go(p, 'analytics-office');
      await tp(p, 0, -0.3, 0);
      await interact(p, 'analytics-console');
      await tid(p, 'play-terminal').waitFor();
      await tid(p, 'terminal-next').click();
      await tid(p, 'lesson').waitFor();
      for (let step = 0; step < 6 && !(await tid(p, 'data-viewer').count()); step++) { const kind = await stepKind(p, step); if (kind === 'demo') await runDemo(p); await tid(p, 'continue').click(); }
      await tid(p, 'data-viewer').waitFor();
      const ids = await p.locator('[data-testid^=dv-db-]').evaluateAll((els) => els.map((e) => e.getAttribute('data-testid')));
      assert(ids.length >= 1 && ids.every((i) => !/-(b|boss|edge)$/.test(i)), 'only visible databases: ' + ids.join());
      await p.locator('.dv-table tbody tr').first().waitFor({ timeout: 60000 });
      assert((await p.locator('.dv-table tbody tr').count()) >= 3, 'sample rows are shown');
      assert((await tid(p, 'data-viewer').innerText()).includes('rows'), 'row counts are shown');
      await p.screenshot({ path: SHOTS + 'play-12-source-data.png' });
      await p.context().close();
    });

    await test('Baseball: without analysis the lineup is not set, the field is empty of a lineup, and the game is played with the jersey-number order', async () => {
      const p = await newGame();
      await go(p, 'ballpark');
      assert(!(await p.evaluate(() => window.__cq3d.dynStates('team'))).includes('set'), 'no lineup yet');
      await tp(p, 0, 8.6, 0);
      await interact(p, 'home-plate');
      assert((await tid(p, 'play-sim').innerText()).includes('0 of 6'), 'Coach says how much analysis is done');
      await tid(p, 'sim-notyet').click();
      await p.context().close();
    });

    console.log('3D world: Redline Raceway (spreadsheets become a setup you can feel)');

    await test('Racing: the telemetry spreadsheet changes the car; the car is drivable; a lap is timed through checkpoints', async () => {
      const p = await newGame();
      await go(p, 'garage');
      // before: the baseline setup
      await tp(p, 0, 3, 0);
      await interact(p, 'drive-car');
      await tid(p, 'drive-hud').waitFor();
      await p.waitForFunction(() => document.querySelector('[data-testid=drive-hud]')?.textContent?.includes('Grip 62%'), null, { timeout: 8000 }); // baseline grip is shown
      // the timer waits at the grid: it starts when the start/finish line is crossed, not when the car moves or the scene opens
      eq(await tid(p, 'drive-time').getAttribute('data-phase'), 'waiting', 'the timer is waiting on the grid');
      await p.waitForTimeout(1500);
      eq(await tid(p, 'drive-time').getAttribute('data-phase'), 'waiting', 'time passing does not start it');
      await p.keyboard.down('w'); await p.waitForTimeout(2500);
      const v1 = parseInt(await tid(p, 'drive-speed').innerText(), 10);
      assert(v1 > 40, `W accelerates the car: ${v1} km/h`);
      eq(await tid(p, 'drive-time').getAttribute('data-phase'), 'running', 'crossing the line started the timer');
      await p.keyboard.down('d'); await p.waitForTimeout(600); await p.keyboard.up('d'); await p.keyboard.up('w');
      // S brakes first; only once the car has nearly stopped does it go backwards
      await p.keyboard.down('s'); await p.waitForTimeout(120);
      assert(parseInt(await tid(p, 'drive-speed').innerText(), 10) > 5 && (await tid(p, 'drive-reverse').count()) === 0, 'S slows the car before it reverses');
      await p.waitForSelector('[data-testid=drive-reverse]', { timeout: 20000 });
      await p.waitForTimeout(1200);
      const vr = parseInt(await tid(p, 'drive-speed').innerText(), 10);
      assert(vr > 3 && vr < 60, `the car reverses at a modest speed: ${vr} km/h`);
      await p.keyboard.down('a'); await p.waitForTimeout(500); await p.keyboard.up('a'); // steering while reversing
      await p.keyboard.up('s');
      await p.screenshot({ path: SHOTS + 'play-11-driving.png' });
      await p.keyboard.press('e');
      await tid(p, 'drive-hud').waitFor({ state: 'detached' });
      assert((await st(p)).scene === 'track', 'got out on the track');
      // the code: telemetry in a spreadsheet, graded on hidden data, changes the car
      await go(p, 'garage');
      await tp(p, -8, -4.8, 0);
      await interact(p, 'telemetry-console');
      await tid(p, 'terminal-next').click();
      await tid(p, 'lesson').waitFor();
      await playLesson(p);
      await tid(p, 'terminal-close').click();
      await p.waitForFunction(() => window.__cq3d.dynStates('car').includes('tyres'), null, { timeout: 8000 });
      await tp(p, 0, 3, 0);
      await interact(p, 'drive-car');
      await tid(p, 'drive-hud').waitFor();
      await p.waitForFunction(() => document.querySelector('[data-testid=drive-hud]')?.textContent?.includes('Grip 100%'), null, { timeout: 8000 }); // the tyres your formulas found now show in the setup
      // a whole lap, driven by the autopilot test hook (it holds the same keys a player does)
      await p.evaluate(() => window.__cq3d.autopilot(true, 6));
      await p.waitForFunction(() => (window.__cq3dHud?.lap ?? 0) >= 1, null, { timeout: 120000 });
      await p.evaluate(() => window.__cq3d.autopilot(false));
      assert((await save(p)).play.seen['lap-done'], 'the finished lap is recorded');
      await p.screenshot({ path: SHOTS + 'play-12-lap.png' });
      await p.context().close();
    });

    console.log('3D world: the Summit and the end of the campaign');

    await test('Campaign: three guardians open the Summit; the final trial is solved with real code; the great beacon ignites and the campaign completes', async () => {
      const p = await newGame({ save: JSON.stringify(saves.campaign) });
      await go(p, 'summit');
      await tp(p, 0, 5.4, 0);
      await interact(p, 'outage-console');
      await tid(p, 'play-boss').waitFor();
      await tid(p, 'boss-open-summit').click();
      await tid(p, 'boss-routes').waitFor();
      await tid(p, 'boss-route-data').check();
      await tid(p, 'boss-begin').click();
      await tid(p, 'boss-run').waitFor();
      const cid = await tid(p, 'boss-run').getAttribute('data-challenge');
      await setCode(p, solutions[cid].valid[0]);
      await tid(p, 'submit').click();
      await tid(p, 'boss-victory').waitFor({ timeout: 120000 });
      await tid(p, 'boss-overlay-close').click();
      await p.waitForFunction(() => window.__cq3d.dynStates('b-great').includes('lit'), null, { timeout: 10000 });
      await p.screenshot({ path: SHOTS + 'play-13-beacon.png' });
      await tid(p, 'finale').waitFor({ timeout: 20000 });
      assert((await tid(p, 'finale-title').innerText()).includes('Summit'), 'the ending is shown');
      assert((await tid(p, 'finale-skills').innerText()).includes('demonstrated'), 'it lists what the player showed, from evidence');
      await p.screenshot({ path: SHOTS + 'play-14-finale.png' });
      assert((await save(p)).campaign.completedAt, 'the campaign is complete in the save');
      await tid(p, 'finale-continue').click();
      await p.reload();
      await p.locator('[data-testid=play][data-ready="1"]').waitFor({ timeout: 30000 }); await p.evaluate(() => { window.__cq3d.stage.timeScale = 4; });
      assert((await p.evaluate(() => window.__cq3d.dynStates('b-great'))).includes('lit'), 'the beacon is lit again after a reload (the world is derived from evidence)');
      await p.context().close();
    });
  } finally { await browser.close(); server.kill(); }
  console.log(`\n${passed} passed, ${failures.length} failed`);
  if (failures.length) { console.log('FAILED: ' + failures.join('; ')); process.exit(1); }
}
main().catch((e) => { console.error(e); process.exit(1); });
