/**
 * End-to-end tests: drive the REAL built game in a REAL browser (Chromium via playwright-core).
 * Usage: npm run e2e   (builds, serves `vite preview`, runs everything, writes screenshots to e2e/screenshots/)
 * Set CHROMIUM_PATH to use a specific browser binary.
 */
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync } from 'node:fs';
import { chromium } from 'playwright-core';
import { solutions as solutionsPhase1 } from '../src/content/python/solutions.testdata.ts';
import { solutionsPhase2Python } from '../src/content/python/solutions.phase2.testdata.ts';
import { solutionsSql } from '../src/content/sql/solutions.testdata.ts';
import { solutionsPhase3Python } from '../src/content/python/solutions.phase3.testdata.ts';
import { solutionsPhase3Sql } from '../src/content/sql/solutions.phase3.testdata.ts';
import { solutionsPhase4Python } from '../src/content/python/solutions.phase4.testdata.ts';
import { solutionsPhase4Sql } from '../src/content/sql/solutions.phase4.testdata.ts';
import { bossSolutions } from '../src/content/boss/solutions.testdata.ts';
import { trainingSolutions } from '../src/content/training/solutions.testdata.ts';

const solutions = { ...solutionsPhase1, ...solutionsPhase2Python, ...solutionsSql, ...solutionsPhase3Python, ...solutionsPhase3Sql, ...solutionsPhase4Python, ...solutionsPhase4Sql, ...bossSolutions, ...trainingSolutions };
/** First reference solution of every web challenge and daily (generated by scripts/e2e-fixtures.ts). */
const fixtures = JSON.parse(readFileSync(new URL('./.fixtures.json', import.meta.url), 'utf8'));

const PORT = 4179;
const BASE = `http://localhost:${PORT}/`;
const SHOTS = new URL('./screenshots/', import.meta.url).pathname;
mkdirSync(SHOTS, { recursive: true });

function findChromium() {
  if (process.env.CHROMIUM_PATH) return process.env.CHROMIUM_PATH;
  const root = process.env.PLAYWRIGHT_BROWSERS_PATH || '/opt/pw-browsers';
  if (existsSync(root)) {
    const dir = readdirSync(root).find((d) => d.startsWith('chromium-'));
    if (dir) return `${root}/${dir}/chrome-linux/chrome`;
  }
  return undefined; // fall back to playwright's default lookup
}

let passed = 0;
const failures = [];
async function test(name, fn) {
  if (process.env.E2E_ONLY && !name.includes(process.env.E2E_ONLY)) return; // e.g. E2E_ONLY=focus
  const t = Date.now();
  try {
    await fn();
    passed++;
    console.log(`  ✓ ${name} (${Date.now() - t}ms)`);
  } catch (e) {
    failures.push(name);
    console.log(`  ✗ ${name}\n      ${String(e.message).split('\n').slice(0, 4).join('\n      ')}`);
  }
}
function assert(cond, msg) { if (!cond) throw new Error(msg); }
const eq = (a, b, msg) => assert(a === b, `${msg}: expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`);

/* ---------------- helpers ---------------- */
let browser;
async function newPage(viewport = { width: 1280, height: 900 }) {
  // reducedMotion: the game honours it, and Playwright cannot click elements with endless CSS animations.
  const ctx = await browser.newContext({ viewport, reducedMotion: 'reduce' });
  const page = await ctx.newPage();
  const errors = [];
  page.on('pageerror', (e) => errors.push(String(e)));
  page.on('console', (m) => m.type() === 'error' && errors.push(m.text()));
  page.errors = errors;
  await page.goto(BASE);
  return page;
}
const tid = (page, id) => page.getByTestId(id);
async function startGame(page, name = 'Tester') {
  await tid(page, 'name-input').fill(name);
  await tid(page, 'begin').click();
}
async function introAndAccept(page) {
  await tid(page, 'dialogue').waitFor();
  for (let i = 0; i < 5; i++) await tid(page, 'dialogue-next').click();
  await tid(page, 'accept-quest').click();
  await tid(page, 'grounds').waitFor();
}
async function setCode(page, code) {
  await page.locator('.cm-content').first().click();
  await page.keyboard.press('Control+A');
  if (code === '') await page.keyboard.press('Delete');
  else await page.keyboard.insertText(code);
}
async function run(page) {
  await tid(page, 'run').click();
  await page.locator('[data-testid=stdout], [data-testid=stderr], [data-testid=sql-results], [data-testid=web-preview] iframe').first().waitFor({ timeout: 30000 });
}
async function xp(page) { return parseInt((await tid(page, 'xp').innerText()).replace(/\D/g, ''), 10); }
async function openLesson(page, id) {
  await tid(page, `lesson-${id}`).locator('button').click();
  await tid(page, 'lesson').waitFor();
}
async function stepKind(page, n) {
  const body = page.locator(`.lesson-body[data-step="${n}"]`);
  await body.waitFor();
  return body.getAttribute('data-kind');
}
/** Plays a whole lesson with the reference solutions (no hints, so evidence is independent). */
/** Types a web project into the HTML/CSS/JS editors (skipping locked tabs). */
async function setWebFiles(page, files) {
  for (const tab of ['html', 'css', 'js']) {
    const button = tid(page, `web-tab-${tab}`);
    if ((await button.innerText()).includes('🔒')) continue;
    await button.click();
    await setCode(page, files[tab] ?? '');
  }
}
/** From the start of an open lesson, runs demos and continues until the first challenge step. */
async function advanceToChallenge(page) {
  for (let i = 0; i < 8; i++) {
    const kind = await stepKind(page, i);
    if (kind === 'challenge') return;
    if (kind === 'demo') await run(page);
    await tid(page, 'continue').click();
  }
  throw new Error('no challenge step found');
}
/** Plays the lesson forward (demos run, guided exercises solved) until the given challenge is on screen. */
async function advanceToChallengeId(page, id) {
  for (let i = 0; i < 14; i++) {
    const kind = await stepKind(page, i);
    if (kind === 'challenge') {
      const cid = await tid(page, 'briefing').getAttribute('data-challenge');
      if (cid === id) return;
      await setCode(page, solutions[cid].valid[0]);
      await tid(page, 'submit').click();
      await page.locator('.result.pass').waitFor({ timeout: 30000 });
    } else if (kind === 'demo') await run(page);
    await tid(page, 'continue').click();
  }
  throw new Error('challenge ' + id + ' not reached');
}
/** Solves the challenge on screen with its reference solution (Python, SQL or web). */
async function solveCurrent(page, cid) {
  if (cid.startsWith('web-')) await setWebFiles(page, fixtures.web[cid]);
  else await setCode(page, solutions[cid].valid[0]);
}
async function playLesson(page, id, { solutionIndex = 0 } = {}) {
  await openLesson(page, id);
  for (let guard = 0; guard < 20; guard++) {
    const kind = await stepKind(page, guard);
    if (kind === 'challenge') {
      const cid = await tid(page, 'briefing').getAttribute('data-challenge');
      await setCode(page, solutions[cid].valid[solutionIndex] ?? solutions[cid].valid[0]);
      await tid(page, 'submit').click();
      await tid(page, 'result').waitFor({ timeout: 30000 });
      assert(await page.locator('.result.pass').count() === 1, `challenge ${cid} should pass`);
    } else if (kind === 'demo') {
      await run(page);
    }
    if (await tid(page, 'finish').count()) {
      await tid(page, 'finish').click();
      await page.locator('[data-testid=grounds], [data-testid^=area-screen-]').first().waitFor();
      return;
    }
    await tid(page, 'continue').click();
  }
  throw new Error('lesson did not finish: ' + id);
}
/** Continues an OPEN lesson from its current step to the end, solving challenges with the reference solutions. */
async function playLessonFrom(page, startStep = 0) {
  for (let step = startStep; step < 30; step++) {
    const kind = await stepKind(page, step);
    if (kind === 'challenge') {
      const cid = await tid(page, 'briefing').getAttribute('data-challenge');
      await solveCurrent(page, cid);
      await tid(page, 'submit').click();
      await tid(page, 'result').waitFor({ timeout: 30000 });
      assert(await page.locator('.result.pass').count() === 1, `challenge ${cid} should pass`);
    } else if (kind === 'demo') {
      await run(page);
    }
    if (await tid(page, 'finish').count()) {
      await tid(page, 'finish').click();
      await page.locator('[data-testid=grounds], [data-testid^=area-screen-]').first().waitFor();
      return;
    }
    await tid(page, 'continue').click();
  }
  throw new Error('lesson did not finish');
}
async function openPanel(page, tab) {
  await page.getByRole('button', { name: /Menu|Skills|Trophies|Pack|Quests/ }).first(); // ensure HUD
  const label = { quests: 'Quest log', pack: 'Inventory', skills: 'Skills and evidence', trophies: 'Achievements', menu: 'Menu' }[tab];
  await page.locator(`button[title="${label}"]`).click();
  await page.getByRole('dialog').waitFor();
}


/** Writes completed lessons straight into the real save, then reloads (fast route to later areas). */
async function seed(page, lessonIds) {
  await page.evaluate((ids) => {
    const s = JSON.parse(localStorage.getItem('codequest.save'));
    for (const id of ids) s.learning.lessons[id] = { stepIndex: 99, completed: true };
    s.flags['mentor-intro'] = true;
    s.quests['wake-the-robot'] = s.quests['wake-the-robot'] ?? { status: 'active', acceptedAt: new Date().toISOString() };
    localStorage.setItem('codequest.save', JSON.stringify(s));
  }, lessonIds);
  await page.reload();
  await tid(page, 'hud').waitFor();
}
async function gotoArea(page, id) {
  await page.locator('button[title="World map"]').click();
  await tid(page, 'worldmap').waitFor();
  await tid(page, `area-${id}`).click();
}
const readSave = (page) => page.evaluate(() => JSON.parse(localStorage.getItem('codequest.save')));

/* ---------------- tests ---------------- */
async function main() {
  const server = spawn('npx', ['vite', 'preview', '--port', String(PORT), '--strictPort'], { stdio: 'ignore' });
  await new Promise((r) => setTimeout(r, 2500));
  browser = await chromium.launch({ executablePath: findChromium(), args: ['--no-sandbox'] });
  try {
    console.log('Startup & character creation');
    await test('app starts, renders title screen, no console errors', async () => {
      const page = await newPage();
      await tid(page, 'begin').waitFor();
      assert(await page.locator('h1.logo').innerText() === 'CodeQuest', 'logo');
      await page.screenshot({ path: SHOTS + '01-title.png' });
      eq(page.errors.length, 0, 'console errors: ' + page.errors.join('|'));
      await page.context().close();
    });

    await test('create character, meet the mentor, accept the quest', async () => {
      const page = await newPage();
      await startGame(page, 'Tester');
      eq(await tid(page, 'player-name').innerText(), 'Tester', 'name in HUD');
      await tid(page, 'dialogue').waitFor();
      await page.screenshot({ path: SHOTS + '02-academy-intro.png' });
      const first = await tid(page, 'dialogue-text').innerText();
      assert(first.includes('Juno'), 'mentor introduces self');
      for (let i = 0; i < 5; i++) await tid(page, 'dialogue-next').click();
      assert((await tid(page, 'dialogue-text').innerText()).includes('Bolt-7'), 'last line mentions quest');
      await tid(page, 'accept-quest').click();
      await tid(page, 'grounds').waitFor();
      await page.screenshot({ path: SHOTS + '03-training-grounds.png' });
      eq(await tid(page, 'robot-power').innerText(), 'Power 0%', 'robot power');
      await page.context().close();
    });

    await test('world map: locked/unlocked areas and reasons', async () => {
      const page = await newPage();
      await startGame(page);
      await introAndAccept(page);
      await page.locator('button[title="World map"]').click();
      await tid(page, 'worldmap').waitFor();
      await page.screenshot({ path: SHOTS + '04-map.png' });
      // Library and Shop are locked at first; the Database District needs cleaning skills; the Web District needs the robot finished; the Observatory is a future area.
      await tid(page, 'area-library').click();
      await tid(page, 'locked-screen').waitFor();
      assert((await tid(page, 'lock-reason').innerText()).includes('first lesson'), 'library reason');
      await page.locator('button:has-text("Back to the map")').click();
      await tid(page, 'area-data-center').click();
      assert((await tid(page, 'lock-reason').innerText()).includes('Messy Data'), 'database district reason');
      await page.locator('button:has-text("Back to the map")').click();
      await tid(page, 'area-web-district').click();
      assert((await tid(page, 'lock-reason').innerText()).includes('Wake the Training Robot'), 'web district reason');
      await page.locator('button:has-text("Back to the map")').click();
      await tid(page, 'area-observatory').click();
      assert((await tid(page, 'lock-reason').innerText()).includes('Phase 4'), 'future area reason');
      await page.screenshot({ path: SHOTS + '05-locked.png' });
      await page.locator('button:has-text("Back to the map")').click();
      await tid(page, 'area-training-grounds').click();
      await tid(page, 'grounds').waitFor();
      await page.context().close();
    });

    console.log('Learning loop: real Python');
    await test('lesson 1: demo runs real Python, challenge fails then passes, XP granted', async () => {
      const page = await newPage();
      await startGame(page);
      await introAndAccept(page);
      await openLesson(page, 'py-01-first-program');
      await page.screenshot({ path: SHOTS + '06-lesson-teach.png' });
      await tid(page, 'continue').click(); // teach -> demo
      assert(await tid(page, 'continue').isDisabled(), 'cannot continue before running the demo');
      await run(page);
      eq((await tid(page, 'stdout').innerText()).trim().split('\n')[0], 'Hello, adventurer!', 'real output');
      await tid(page, 'notice').waitFor();
      await page.screenshot({ path: SHOTS + '07-demo.png' });
      await tid(page, 'continue').click();
      // challenge (learning mode)
      eq(await tid(page, 'mode-badge').innerText(), 'LEARNING MODE', 'mode badge'.toLowerCase() && 'mode badge');
      const xp0 = await xp(page);
      // wrong answer first
      await setCode(page, 'print("wrong")');
      await tid(page, 'submit').click();
      await tid(page, 'result').waitFor({ timeout: 30000 });
      assert(await page.locator('.result.fail').count() === 1, 'fails');
      assert((await page.locator('.diff').innerText()).includes('BOLT-7 ONLINE'), 'shows expected on visible check');
      eq(await xp(page), xp0, 'no XP for failure');
      assert((await tid(page, 'focus').innerText()).includes('90/100'), 'focus dropped');
      await page.screenshot({ path: SHOTS + '08-challenge-fail.png' });
      // correct
      await setCode(page, 'print("BOLT-7 ONLINE")');
      await run(page);
      eq((await tid(page, 'stdout').innerText()).trim(), 'BOLT-7 ONLINE', 'output');
      await tid(page, 'submit').click();
      await page.locator('.result.pass').waitFor({ timeout: 30000 });
      assert(await xp(page) > xp0, 'xp increased');
      assert((await tid(page, 'evidence-note').innerText()).includes('guided'), 'learning mode must be recorded as guided, never independent');
      await page.screenshot({ path: SHOTS + '09-challenge-pass.png' });
      assert(await tid(page, 'toasts').locator('.toast').count() > 0, 'toasts shown');
      eq(page.errors.length, 0, 'console errors: ' + page.errors.join('|'));
      await page.context().close();
    });

    await test('errors: player sees real NameError/SyntaxError and can debug', async () => {
      const page = await newPage();
      await startGame(page);
      await introAndAccept(page);
      await playLesson(page, 'py-01-first-program');
      await openLesson(page, 'py-02-fixing-errors');
      await tid(page, 'continue').click(); // teach -> demo1
      await run(page);
      const err = await tid(page, 'stderr').innerText();
      assert(err.includes('NameError') && err.includes('line 2') && err.includes('battery_level'), 'NameError shown: ' + err);
      await page.screenshot({ path: SHOTS + '10-error.png' });
      await tid(page, 'continue').click(); // demo2 (syntax)
      await run(page);
      assert((await tid(page, 'stderr').innerText()).includes('SyntaxError'), 'SyntaxError shown');
      await tid(page, 'continue').click(); await tid(page, 'continue').click(); // -> challenge
      await run(page); // starter is broken
      assert((await tid(page, 'stderr').innerText()).includes('SyntaxError'), 'starter code errors');
      await page.context().close();
    });

    await test('hints are progressive, cost reward, and are recorded as evidence', async () => {
      const page = await newPage();
      await startGame(page);
      await introAndAccept(page);
      await playLesson(page, 'py-01-first-program');
      await playLesson(page, 'py-02-fixing-errors');
      await playLesson(page, 'py-03-variables');
      await playLesson(page, 'py-04-strings');
      await playLesson(page, 'py-05-numbers');
      await openLesson(page, 'py-06-input-conversion');
      for (let i = 0; i < 3; i++) { await tid(page, 'continue').click(); if (i < 2) await run(page); }
      await page.waitForTimeout(100);
      // now on first challenge (learning). Continue past to a challenge-mode one by solving.
      let cid = await tid(page, 'briefing').getAttribute('data-challenge');
      await setCode(page, solutions[cid].valid[0]); await tid(page, 'submit').click(); await page.locator('.result.pass').waitFor({ timeout: 30000 });
      await tid(page, 'continue').click();
      cid = await tid(page, 'briefing').getAttribute('data-challenge');
      eq(cid, 'py-06-ticket-total', 'challenge-mode challenge');
      eq(await page.locator('[data-testid=hint-list] li').count(), 0, 'no hints yet');
      await tid(page, 'hint').click();
      eq(await page.locator('[data-testid=hint-list] li').count(), 1, 'one hint');
      await tid(page, 'hint').click();
      eq(await page.locator('[data-testid=hint-list] li').count(), 2, 'two hints');
      assert((await tid(page, 'hint').innerText()).includes('2/3'), 'counter');
      const before = await xp(page);
      await setCode(page, solutions[cid].valid[0]);
      await tid(page, 'submit').click();
      await page.locator('.result.pass').waitFor({ timeout: 30000 });
      const gained = (await xp(page)) - before;
      eq(gained, 27, 'hinted reward is reduced (45 * 0.6)');
      const save = JSON.parse(await page.evaluate(() => localStorage.getItem('codequest.save')));
      const rec = save.evidence.find((r) => r.challengeId === cid);
      eq(rec.hintsUsed, 2, 'hints in evidence'); eq(rec.support, 'hinted', 'support level'); eq(rec.executed, true, 'executed');
      // A hinted pass of a challenge means guided evidence: the Mentor sends the player to train (one proof replaces "replay")
      await tid(page, 'diagnosis').waitFor();
      eq(await tid(page, 'replay').count(), 0, 'no replay shortcut while training is required');
      await page.context().close();
    });

    await test('infinite loop is stopped with a helpful message and Python recovers', async () => {
      const page = await newPage();
      await startGame(page);
      await introAndAccept(page);
      await openLesson(page, 'py-01-first-program');
      await tid(page, 'continue').click(); await run(page); await tid(page, 'continue').click();
      await setCode(page, 'while True:\n    pass');
      await tid(page, 'run').click();
      await tid(page, 'stderr').waitFor({ timeout: 30000 });
      assert((await tid(page, 'stderr').innerText()).includes('ran for more than'), 'timeout message');
      await page.screenshot({ path: SHOTS + '11-timeout.png' });
      await setCode(page, 'print("still alive")');
      await run(page);
      assert((await tid(page, 'stdout').innerText()).includes('still alive'), 'python restarted and works');
      await page.context().close();
    });

    await test('runaway output is stopped, not frozen', async () => {
      const page = await newPage();
      await startGame(page);
      await introAndAccept(page);
      await openLesson(page, 'py-01-first-program');
      await tid(page, 'continue').click(); await run(page); await tid(page, 'continue').click();
      await setCode(page, 'while True:\n    print("spam")');
      await tid(page, 'run').click();
      await tid(page, 'stderr').waitFor({ timeout: 30000 });
      assert((await tid(page, 'stderr').innerText()).includes('too much output'), 'output limit message');
      await page.context().close();
    });

    console.log('Progression, quests, unlocks, persistence');
    let fullPlaythroughState;
    await test('full playthrough: all lessons, quest completes, unlocks, mastery evidence, trial', async () => {
      const page = await newPage();
      await startGame(page, 'Hero');
      await introAndAccept(page);
      const lessonIds = ['py-01-first-program', 'py-02-fixing-errors', 'py-03-variables', 'py-04-strings', 'py-05-numbers', 'py-06-input-conversion', 'py-07-logic', 'py-08-if-else', 'py-09-elif', 'py-10-while', 'py-11-for-range', 'py-12-functions', 'py-13-wake-robot'];
      for (const id of lessonIds) {
        await playLesson(page, id);
        if (id === 'py-01-first-program') assert(await page.evaluate(() => JSON.parse(localStorage.getItem('codequest.save')).unlockedAreas.includes('library')), 'library unlocked after lesson 1');
        if (id === 'py-02-fixing-errors') assert(await page.evaluate(() => JSON.parse(localStorage.getItem('codequest.save')).unlockedAreas.includes('shop')), 'shop unlocked after lesson 2');
        // keep Focus healthy: rest is free, but all solutions pass first time so no loss
      }
      eq(await tid(page, 'robot-power').innerText(), 'Power 100%', 'robot power');
      await page.screenshot({ path: SHOTS + '12-robot-awake.png' });
      // Independent trial: no hints, no starter, no concepts
      await openLesson(page, 'py-14-independent-trial');
      eq(await tid(page, 'mode-badge').innerText(), 'INDEPENDENT TRIAL', 'independent mode badge');
      eq(await tid(page, 'hint').count(), 0, 'no hint button in independent mode');
      const brief = await tid(page, 'briefing').innerText();
      for (const forbidden of ['while', 'for loop', 'int(', 'max(', 'Python']) assert(!brief.includes(forbidden), `independent prompt must not name "${forbidden}"`);
      await page.screenshot({ path: SHOTS + '13-independent.png' });
      await setCode(page, solutions['py-14-warehouse-audit'].wrong[0]);
      await tid(page, 'submit').click(); await tid(page, 'result').waitFor({ timeout: 30000 });
      assert(await page.locator('.result.fail').count() === 1, 'wrong trial answer fails hidden cases');
      await setCode(page, solutions['py-14-warehouse-audit'].valid[1]);
      await tid(page, 'submit').click(); await page.locator('.result.pass').waitFor({ timeout: 30000 });
      await tid(page, 'finish').click();
      await tid(page, 'grounds').waitFor();

      const save = JSON.parse(await page.evaluate(() => localStorage.getItem('codequest.save')));
      eq(save.quests['wake-the-robot'].status, 'complete', 'quest complete');
      assert(save.inventory['robot-bolt'] === 1, 'quest item');
      for (const a of ['first-run', 'first-pass', 'bug-squasher', 'own-two-feet', 'hat-trick', 'robot-awake', 'blank-page', 'level-5']) assert(save.achievements[a], 'achievement ' + a);
      assert(!save.unlockedAreas.includes('data-center') && !save.unlockedAreas.includes('web-workshop'), 'future areas remain locked');
      assert(save.evidence.length >= 30, 'evidence recorded for every submission');
      assert(save.evidence.every((r) => r.executed), 'all evidence executed');
      // Skills view: shows evidence, not XP
      await openPanel(page, 'skills');
      const skills = await tid(page, 'skills-view').innerText();
      assert(skills.includes('Demonstrated independently'), 'some skills demonstrated');
      assert(!/\bXP\b/.test(skills.replace('XP and level never appear here', '')), 'skills view shows no XP');
      await page.screenshot({ path: SHOTS + '14-skills.png' });
      fullPlaythroughState = await page.evaluate(() => localStorage.getItem('codequest.save'));
      const level = await tid(page, 'level').innerText();
      console.log('      final:', level, '| xp', save.stats.xp, '| coins', save.stats.coins, '| evidence records', save.evidence.length);
      eq(page.errors.length, 0, 'console errors: ' + page.errors.join('|'));
      await page.context().close();
    });

    await test('save persists across reload; XP != mastery is visible', async () => {
      const page = await newPage();
      await page.evaluate((s) => localStorage.setItem('codequest.save', s), fullPlaythroughState);
      await page.reload();
      await tid(page, 'hud').waitFor();
      eq(await tid(page, 'player-name').innerText(), 'Hero', 'name persisted');
      assert(await xp(page) > 1000, 'xp persisted');
      await page.context().close();
    });

    await test('level-up: overlay shown, and HUD level rises', async () => {
      const page = await newPage();
      await startGame(page);
      await introAndAccept(page);
      await playLesson(page, 'py-01-first-program'); // 20 + 30*? enough to reach level 2 at 100xp? checked below
      await playLesson(page, 'py-02-fixing-errors');
      await playLesson(page, 'py-03-variables');
      assert(!(await tid(page, 'level').innerText()).includes('Level 1'), 'left level 1');
      await page.context().close();
    });

    await test('focus: exhausting it disables Submit; resting at the Academy restores it', async () => {
      const page = await newPage();
      await startGame(page);
      await introAndAccept(page);
      await openLesson(page, 'py-01-first-program');
      await tid(page, 'continue').click(); await run(page); await tid(page, 'continue').click();
      await setCode(page, 'print("nope")');
      for (let i = 0; i < 10; i++) {
        await tid(page, 'submit').click();
        await tid(page, 'result').waitFor({ timeout: 30000 });
        await page.waitForTimeout(80);
      }
      assert((await tid(page, 'focus').innerText()).includes('0/100'), 'focus at 0');
      assert(await tid(page, 'submit').isDisabled(), 'submit disabled');
      await tid(page, 'focus-warning').waitFor();
      await tid(page, 'run').click(); // running is still allowed
      await page.locator('.focus-warning button').click();
      await tid(page, 'rest').click();
      assert((await tid(page, 'focus').innerText()).includes('100/100'), 'rested');
      await page.context().close();
    });

    await test('shop: buy items, use them; inventory and cosmetics', async () => {
      const page = await newPage();
      await startGame(page);
      await introAndAccept(page);
      // give coins via a real save edit (as if earned)
      await page.evaluate(() => { const s = JSON.parse(localStorage.getItem('codequest.save')); s.stats.coins = 200; s.stats.focus = 30; s.learning.lessons['py-02-fixing-errors'] = { stepIndex: 9, completed: true }; localStorage.setItem('codequest.save', JSON.stringify(s)); });
      await page.reload();
      await page.locator('button[title="World map"]').click();
      await tid(page, 'area-shop').click();
      await tid(page, 'shop').waitFor();
      await page.screenshot({ path: SHOTS + '15-shop.png' });
      await tid(page, 'buy-focus-tea').click();
      eq(await tid(page, 'coins').innerText(), '🪙 175', 'coins spent');
      await tid(page, 'buy-explorer-cape').click();
      assert(await tid(page, 'buy-explorer-cape').isDisabled(), 'cosmetic owned once');
      await openPanel(page, 'pack');
      await tid(page, 'use-focus-tea').click();
      assert((await tid(page, 'focus').innerText()).includes('80/100'), 'tea restored 50 focus');
      await page.screenshot({ path: SHOTS + '16-pack.png' });
      await page.context().close();
    });

    await test('library: notebook and training log; menu: export/import/reset', async () => {
      const page = await newPage();
      await page.evaluate((s) => localStorage.setItem('codequest.save', s), fullPlaythroughState);
      await page.reload();
      await page.locator('button[title="World map"]').click();
      await tid(page, 'area-library').click();
      await tid(page, 'library').waitFor();
      assert((await tid(page, 'notes').innerText()).includes('print()'), 'reference cards');
      await tid(page, 'tab-log').click();
      await tid(page, 'skills-view').waitFor();
      await page.screenshot({ path: SHOTS + '17-library-log.png' });
      // export / import round trip
      await openPanel(page, 'menu');
      await tid(page, 'export').click();
      const exported = await tid(page, 'save-text').inputValue();
      assert(exported.includes('"version":5'), 'exported');
      await tid(page, 'import').click();
      assert((await page.getByRole('status').innerText()).includes('restored'), 'import ok');
      // reset
      await tid(page, 'reset').click();
      await tid(page, 'reset-confirm').click();
      await tid(page, 'begin').waitFor();
      assert(await page.evaluate(() => JSON.parse(localStorage.getItem('codequest.save')).player === null), 'save reset');
      await page.context().close();
    });


    console.log('Phase 2: SQL, retry, manual, pipelines');
    await test('Database District: opens after Messy Data; SQL runs on real SQLite; lesson completes', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, ['py-21-cleaning']);
      await gotoArea(page, 'data-center');
      await tid(page, 'area-screen-data-center').waitFor();
      await tid(page, 'npc-vex').waitFor();
      await page.screenshot({ path: SHOTS + '30-database-district.png' });
      await openLesson(page, 'sql-01-select');
      await tid(page, 'continue').click(); // teach -> demo
      await run(page);
      await tid(page, 'sql-results').waitFor();
      assert((await page.locator('.sql-table tbody tr').count()) > 0, 'a result table with rows is shown');
      await page.screenshot({ path: SHOTS + '31-sql-demo.png' });
      await playLessonFrom(page, 1);
      const save = await readSave(page);
      assert(save.learning.lessons['sql-01-select'].completed, 'SQL lesson completed');
      assert(save.evidence.some((r) => r.challengeId.startsWith('sql-01') && r.passed), 'SQL evidence recorded');
      eq(page.errors.length, 0, 'console errors: ' + page.errors.join('|'));
      await page.context().close();
    });

    await test('failing a SQL challenge is recorded, blocks an immediate retry, and points to the Training Grounds', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, ['py-21-cleaning', 'sql-01-select']);
      await gotoArea(page, 'data-center');
      await openLesson(page, 'sql-02-sort-limit');
      let seenChallenges = 0; // the first challenge is a guided one with no alternates; the second has variants
      for (let i = 0; i < 20; i++) {
        const kind = await stepKind(page, i);
        if (kind === 'challenge' && seenChallenges === 1) break;
        if (kind === 'demo') await run(page);
        if (kind === 'challenge') {
          seenChallenges++;
          const cid0 = await tid(page, 'briefing').getAttribute('data-challenge');
          await setCode(page, solutions[cid0].valid[0]);
          await tid(page, 'submit').click();
          await page.locator('.result.pass').waitFor({ timeout: 30000 });
        }
        await tid(page, 'continue').click();
      }
      const first = await tid(page, 'briefing').getAttribute('data-challenge');
      await setCode(page, 'SELECT 1;');
      await tid(page, 'submit').click();
      await tid(page, 'result').waitFor({ timeout: 30000 });
      assert(await page.locator('.result.fail').count() === 1, 'wrong SQL fails');
      eq(await tid(page, 'other-variant').count(), 0, 'no swapping to another problem instead of training');
      await tid(page, 'diagnosis').waitFor();
      assert(await tid(page, 'submit').isDisabled(), 'no immediate retry');
      const save = await readSave(page);
      assert(save.evidence.filter((r) => r.challengeId === first && !r.passed).length === 1, 'the failure is recorded');
      await page.context().close();
    });

    await test('Field Manual: search, open an entry, lookup recorded as research evidence', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, ['py-21-cleaning']);
      await gotoArea(page, 'data-center');
      await openLesson(page, 'sql-01-select');
      for (let i = 0; i < 20 && (await stepKind(page, i)) !== 'challenge'; i++) {
        if ((await stepKind(page, i)) === 'demo') await run(page);
        await tid(page, 'continue').click();
      }
      const cid = await tid(page, 'briefing').getAttribute('data-challenge');
      await tid(page, 'open-manual').click();
      await tid(page, 'manual-search').fill('order by');
      await page.locator('[data-testid^=manual-]:not([data-testid=manual-search])').first().click();
      await page.locator('.manual-entry').waitFor();
      const save = await readSave(page);
      assert((save.learning.challenges[cid]?.lookups ?? 0) >= 1, 'lookup recorded on the challenge');
      await page.context().close();
    });

    await test('SQL sandbox: changes persist across reloads; reset restores the original data', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, ['py-21-cleaning']);
      await gotoArea(page, 'data-center');
      await tid(page, 'tab-sandbox').click();
      await tid(page, 'sandbox').waitFor();
      await setCode(page, "DELETE FROM order_items; SELECT COUNT(*) AS n FROM order_items;");
      await tid(page, 'sandbox-run').click();
      await page.locator('.sql-table td').first().waitFor({ timeout: 30000 });
      eq((await page.locator('.sql-table td').first().innerText()).trim(), '0', 'rows deleted in the sandbox');
      await page.reload();
      await gotoArea(page, 'data-center');
      await tid(page, 'tab-sandbox').click();
      assert((await tid(page, 'sandbox-state').innerText()).includes('changes'), 'state remembered after reload');
      await setCode(page, 'SELECT COUNT(*) AS n FROM order_items;');
      await tid(page, 'sandbox-run').click();
      await page.locator('.sql-table td').first().waitFor({ timeout: 30000 });
      eq((await page.locator('.sql-table td').first().innerText()).trim(), '0', 'still empty after reload');
      await tid(page, 'sandbox-reset').click();
      await tid(page, 'sandbox-run').click();
      await page.locator('.sql-table td').first().waitFor({ timeout: 30000 });
      assert(parseInt(await page.locator('.sql-table td').first().innerText(), 10) > 0, 'reset restores the data');
      const save = await readSave(page);
      assert(!save.evidence.length, 'the sandbox never writes evidence');
      await page.context().close();
    });

    await test('Data Pipeline Works: locked until Safe and Fast; a Python + database lesson completes', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, ['py-21-cleaning']);
      await gotoArea(page, 'pipeline-works');
      await tid(page, 'locked-screen').waitFor();
      assert((await tid(page, 'lock-reason').innerText()).includes('Safe and Fast'), 'pipeline reason');
      await seed(page, ['sql-13-integrity-performance']);
      await gotoArea(page, 'pipeline-works');
      await tid(page, 'area-screen-pipeline-works').waitFor();
      await tid(page, 'npc-sana').waitFor();
      await openLesson(page, 'de-01-pipelines');
      await tid(page, 'continue').click();
      await playLessonFrom(page, 1);
      const save = await readSave(page);
      assert(save.learning.lessons['de-01-pipelines'].completed, 'pipeline lesson completed');
      await page.context().close();
    });

    await test('Phase 2 screens: phone layout has no horizontal scroll', async () => {
      const page = await newPage({ width: 390, height: 800 });
      await startGame(page);
      await seed(page, ['py-21-cleaning']);
      const noOverflow = async (label) => {
        const over = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
        assert(over <= 1, `${label}: horizontal overflow ${over}px`);
      };
      await gotoArea(page, 'data-center'); await noOverflow('district');
      await tid(page, 'tab-sandbox').click(); await noOverflow('sandbox');
      await page.screenshot({ path: SHOTS + '32-mobile-sandbox.png', fullPage: true });
      await page.locator('button[title="World map"]').click();
      await tid(page, 'area-data-center').click();
      await openLesson(page, 'sql-01-select');
      await tid(page, 'continue').click(); await run(page); await noOverflow('sql demo');
      await page.screenshot({ path: SHOTS + '33-mobile-sql-demo.png', fullPage: true });
      await page.context().close();
    });


    console.log('Phase 3: Daily Challenge');
    const PY_EARLY = ['py-01-first-program', 'py-02-fixing-errors', 'py-03-variables', 'py-04-strings', 'py-05-numbers', 'py-06-input-conversion', 'py-07-logic', 'py-08-if-else', 'py-09-elif', 'py-10-while', 'py-11-for-range', 'py-12-functions', 'py-13-wake-robot'];
    const openDaily = async (page) => {
      await tid(page, 'hud-daily').click();
      await tid(page, 'daily-card').waitFor();
    };
    await test('Daily Challenge: offered after learning, transparent, timer persists across reload, no hints', async () => {
      const page = await newPage();
      await startGame(page);
      await tid(page, 'dialogue').waitFor();
      await openDaily(page);
      eq(await tid(page, 'daily-card').getAttribute('data-state'), 'none', 'nothing on offer before anything is learned');
      await seed(page, PY_EARLY);
      await openDaily(page);
      eq(await tid(page, 'daily-card').getAttribute('data-state'), 'open', 'a daily is on offer');
      for (const id of ['daily-title', 'daily-meta', 'daily-reason', 'daily-reward', 'daily-timer']) assert((await tid(page, id).innerText()).length > 3, id + ' has text');
      assert(/\d+h|\d+m/.test(await tid(page, 'daily-timer').innerText()), 'the timer shows time remaining');
      const before = (await readSave(page)).daily.current;
      assert(before && before.status === 'open' && Date.parse(before.expiresAt) - Date.parse(before.issuedAt) === 12 * 3600 * 1000, 'a 12-hour window');
      await page.reload();
      await tid(page, 'hud').waitFor();
      await openDaily(page);
      const after = (await readSave(page)).daily.current;
      eq(after.challengeId, before.challengeId, 'the same challenge after a reload');
      eq(after.expiresAt, before.expiresAt, 'the same expiry after a reload (reload never re-rolls or extends)');
      await tid(page, 'daily-start').click();
      await tid(page, 'daily-run').waitFor();
      eq(await tid(page, 'hint').count(), 0, 'no hint button in a Daily Challenge');
      await page.screenshot({ path: SHOTS + '40-daily.png' });
      eq(page.errors.length, 0, 'console errors: ' + page.errors.join('|'));
      await page.context().close();
    });

    await test('Daily Challenge: ONE attempt. A failure costs no Focus, is recorded, and cannot be retried', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, PY_EARLY);
      await openDaily(page);
      await tid(page, 'daily-start').click();
      await tid(page, 'daily-run').waitFor();
      const before = await readSave(page);
      await setCode(page, 'pass');
      await tid(page, 'daily-submit').click();
      await tid(page, 'daily-confirm').click();
      await tid(page, 'daily-result').waitFor({ timeout: 30000 });
      assert(await page.locator('.result.fail').count() === 1, 'the wrong answer fails');
      const s = await readSave(page);
      eq(s.stats.coins, before.stats.coins, 'no coins for a failure');
      eq(s.stats.focus, before.stats.focus, 'a failed daily costs no Focus');
      eq(s.daily.current.status, 'failed', 'the attempt is closed');
      eq(s.daily.history.length, 1, 'history recorded');
      assert(s.evidence.at(-1).passed === false && s.evidence.at(-1).support === 'independent', 'the failure is evidence');
      await page.reload();
      await tid(page, 'hud').waitFor();
      await openDaily(page);
      eq(await tid(page, 'daily-card').getAttribute('data-state'), 'failed', 'still closed after a reload');
      eq(await tid(page, 'daily-start').count(), 0, 'no retry offered');
      await page.context().close();
    });

    await test('Daily Challenge: a solve pays coins/XP/Focus, is independent evidence, never sells a hint', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, PY_EARLY);
      await openDaily(page);
      await tid(page, 'daily-start').click();
      await tid(page, 'daily-run').waitFor();
      const cid = await tid(page, 'daily-briefing').getAttribute('data-challenge');
      const sol = fixtures.dailies[cid];
      assert(sol !== undefined, 'a reference solution exists for ' + cid);
      const before = await readSave(page);
      if (typeof sol === 'string') await setCode(page, sol);
      else await setWebFiles(page, sol);
      await tid(page, 'daily-submit').click();
      await tid(page, 'daily-confirm').click();
      await tid(page, 'daily-result').waitFor({ timeout: 60000 });
      assert(await page.locator('.result.pass').count() === 1, 'the reference solution passes');
      const s = await readSave(page);
      assert(s.stats.coins > before.stats.coins, 'coins paid');
      assert(s.evidence.at(-1).passed && s.evidence.at(-1).hintsUsed === 0 && ['independent', 'transfer'].includes(s.evidence.at(-1).support), 'independent evidence, no hints');
      assert(s.achievements['first-daily'], 'First Daily earned');
      eq(s.daily.history.at(-1).outcome, 'passed', 'history says passed');
      await page.context().close();
    });

    console.log('Phase 3: Web District');
    const WEB_PREREQ = ['web-01-html-basics', 'web-02-links-lists', 'web-03-tables', 'web-04-semantics', 'web-05-forms', 'web-06-html-debugging', 'web-07-independent-html', 'web-08-css-selectors', 'web-09-box-model', 'web-10-flexbox', 'web-11-grid', 'web-12-responsive', 'web-13-css-projects', 'web-14-independent-css', 'web-15-js-basics', 'web-16-js-data', 'web-17-js-errors', 'web-18-dom', 'web-19-events', 'web-20-forms-js', 'web-21-storage-json', 'web-22-async'];
    await test('Web District: locked until the robot is finished, then NPCs, quests and an HTML lesson pass in the sandbox', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, PY_EARLY);
      await page.evaluate(() => {
        const st = JSON.parse(localStorage.getItem('codequest.save'));
        st.quests['wake-the-robot'] = { status: 'complete', acceptedAt: new Date().toISOString() };
        localStorage.setItem('codequest.save', JSON.stringify(st));
      });
      await page.reload();
      await tid(page, 'hud').waitFor();
      await gotoArea(page, 'web-district');
      await tid(page, 'area-screen-web-district').waitFor();
      for (const id of ['npc-nia']) await tid(page, id).waitFor();
      await tid(page, 'quest-build-the-web').waitFor();
      await page.screenshot({ path: SHOTS + '41-web-district.png' });
      await openLesson(page, 'web-01-html-basics');
      await tid(page, 'continue').click(); // teach -> next
      let kind = await stepKind(page, 1);
      if (kind === 'demo') { await run(page); await tid(page, 'web-preview').waitFor(); }
      await playLessonFrom(page, 1);
      const save = await readSave(page);
      assert(save.learning.lessons['web-01-html-basics'].completed, 'web lesson completed');
      assert(save.evidence.some((r) => r.challengeId.startsWith('web-01') && r.passed), 'web evidence recorded');
      assert(save.achievements['first-page'], 'First Page earned');
      eq(page.errors.length, 0, 'console errors: ' + page.errors.join('|'));
      await page.context().close();
    });

    await test('Web sandbox in the real app: no access to the game, no network, private storage', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, [...PY_EARLY, ...WEB_PREREQ.slice(0, 14)]);
      await gotoArea(page, 'web-district');
      await openLesson(page, 'web-15-js-basics');
      await advanceToChallenge(page);
      await tid(page, 'briefing').waitFor();
      await setWebFiles(page, { html: '<p>probe</p>', css: '', js: [
        'try { console.log("parent:" + String(parent.document.title)); } catch (e) { console.log("parent-blocked:" + e.name); }',
        'console.log("save:" + String(localStorage.getItem("codequest.save")));',
        'console.log("origin:" + window.origin);',
        'fetch("https://example.com/").then(() => console.log("network:open"), () => console.log("network:blocked"));',
        'try { new XMLHttpRequest(); console.log("xhr:open"); } catch (e) { console.log("xhr:blocked"); }',
      ].join('\n') });
      await run(page);
      await page.locator('[data-testid=console]').filter({ hasText: 'network:' }).waitFor({ timeout: 15000 });
      const out = await tid(page, 'console').innerText();
      assert(out.includes('parent-blocked:SecurityError'), 'the page cannot read the game: ' + out);
      assert(out.includes('save:null'), 'the page cannot see the game save: ' + out);
      assert(out.includes('origin:null'), 'opaque origin: ' + out);
      assert(out.includes('network:blocked'), 'no network: ' + out);
      assert(out.includes('xhr:blocked'), 'no XMLHttpRequest: ' + out);
      const attr = await page.locator('[data-testid=web-preview] iframe').getAttribute('sandbox');
      assert(attr.includes('allow-scripts') && !attr.includes('allow-same-origin'), 'iframe sandbox attribute: ' + attr);
      assert((await readSave(page)).player.name === 'Tester', 'the game save is intact');
      await page.context().close();
    });

    await test('Web page with an endless loop: the game stays responsive and grading ends with an explanation', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, [...PY_EARLY, ...WEB_PREREQ.slice(0, 14)]);
      await gotoArea(page, 'web-district');
      await openLesson(page, 'web-15-js-basics');
      await advanceToChallenge(page);
      await tid(page, 'web-tab-js').click();
      await setCode(page, 'while (true) {}');
      await tid(page, 'run').click();
      await page.waitForTimeout(1200);
      const alive = await Promise.race([page.evaluate(() => 40 + 2), new Promise((r) => setTimeout(() => r('frozen'), 5000))]);
      eq(alive, 42, 'the game page is still responsive while the sandboxed page loops');
      await tid(page, 'submit').click();
      await tid(page, 'result').waitFor({ timeout: 40000 });
      assert(await page.locator('.result.fail').count() === 1, 'it does not pass');
      await page.context().close();
    });

    await test('Web APIs: the network log shows requests, and fetch lessons pass against the in-game API', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, [...PY_EARLY, ...WEB_PREREQ]);
      await gotoArea(page, 'web-district');
      await openLesson(page, 'web-23-fetch');
      await tid(page, 'continue').click(); // teach -> demo
      await run(page);
      await page.waitForFunction(() => document.querySelectorAll('[data-testid=request-line]').length > 0, null, { timeout: 15000 });
      const line = await tid(page, 'request-line').first().innerText();
      assert(/GET \/api\/machines.*200/.test(line), 'a request line is shown: ' + line);
      await playLessonFrom(page, 1);
      const save = await readSave(page);
      assert(save.learning.lessons['web-23-fetch'].completed, 'fetch lesson completed');
      assert(save.evidence.some((r) => r.skillIds.includes('web.http') && r.passed), 'web.http evidence');
      assert(save.achievements['first-request'], 'First Request earned');
      await page.context().close();
    });

    await test('Field Manual: web entries are searchable from a web challenge', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, PY_EARLY);
      await gotoArea(page, 'web-district');
      await openLesson(page, 'web-01-html-basics');
      await advanceToChallenge(page);
      await tid(page, 'open-manual').click();
      await tid(page, 'manual-search').fill('semantic');
      await tid(page, 'manual-web-html-semantic').click();
      assert((await page.locator('.manual-entry').innerText()).includes('main'), 'the entry explains landmarks');
      await tid(page, 'manual-search').fill('cascade');
      await tid(page, 'manual-web-css-cascade').waitFor();
      const save = await readSave(page);
      assert(Object.values(save.learning.challenges).some((c) => (c.lookups ?? 0) > 0), 'lookup recorded as research evidence');
      await page.context().close();
    });

    await test('Retention: a skill quiet for a week is shown as due for review, with the reason', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, PY_EARLY);
      await page.evaluate(() => {
        const s = JSON.parse(localStorage.getItem('codequest.save'));
        s.evidence.push({ at: new Date(Date.now() - 12 * 86400000).toISOString(), challengeId: 'py-05-savings', objectiveId: 'py-05-savings', skillIds: ['py.numbers'], concepts: [], mode: 'challenge', difficulty: 3, passed: true, support: 'independent', hintsUsed: 0, attemptNumber: 1, timeMs: 1000, executed: true, context: 'finance', lookups: 0, priorFailures: 0, project: false });
        localStorage.setItem('codequest.save', JSON.stringify(s));
      });
      await page.reload();
      await tid(page, 'hud').waitFor();
      await openPanel(page, 'skills');
      const note = tid(page, 'review-py.numbers');
      await note.waitFor();
      assert(/12 days/.test(await note.innerText()), 'the reason names the days: ' + (await note.innerText()));
      await page.keyboard.press('Escape');
      await page.context().close();
    });

    await test('Phone layout: web lesson and daily have no horizontal scroll', async () => {
      const page = await newPage({ width: 390, height: 800 });
      await startGame(page);
      await seed(page, PY_EARLY);
      const noOverflow = async (label) => {
        const over = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
        assert(over <= 1, `${label}: horizontal overflow ${over}px`);
      };
      await gotoArea(page, 'web-district'); await noOverflow('web district');
      await openLesson(page, 'web-01-html-basics');
      await tid(page, 'continue').click(); await noOverflow('web lesson');
      await page.screenshot({ path: SHOTS + '42-mobile-web-lesson.png', fullPage: true });
      await page.locator('button[title="Daily Challenge"]').click();
      await tid(page, 'daily-card').waitFor(); await noOverflow('daily');
      await page.context().close();
    });


    console.log('Phase 4: adaptive training, bosses, campaign');
    /** Types the reference solution for ANY challenge (lesson, daily or boss) into the editor. */
    const solveAny = async (page, cid) => {
      if (solutions[cid]) return setCode(page, solutions[cid].valid[0]);
      const d = fixtures.dailies[cid] ?? fixtures.bosses?.[cid];
      if (d !== undefined) return typeof d === 'string' ? setCode(page, d) : setWebFiles(page, d);
      if (fixtures.web[cid]) return setWebFiles(page, fixtures.web[cid]);
      throw new Error('no reference solution for ' + cid);
    };
    /** Plays a whole training plan with reference solutions until the completion panel appears. */
    const playTraining = async (page) => {
      for (let guard = 0; guard < 120; guard++) {
        if (await tid(page, 'training-complete').count()) return;
        if (await tid(page, 'training-read').count()) { await tid(page, 'training-read').click(); continue; }
        if (await tid(page, 'training-start-step').count()) await tid(page, 'training-start-step').click();
        await tid(page, 'briefing').waitFor({ timeout: 15000 });
        const cid = await tid(page, 'briefing').getAttribute('data-challenge');
        await solveAny(page, cid);
        await tid(page, 'submit').click();
        // A finished step is replaced at once by the next one (or by the completion panel), so wait for whatever comes first.
        await tid(page, 'result').or(tid(page, 'training-intro')).or(tid(page, 'training-read')).or(tid(page, 'training-complete')).first().waitFor({ timeout: 60000 }).catch((e) => { throw new Error('nothing happened after submitting ' + cid + ': ' + e.message.split('\n')[0]); });
        if (await tid(page, 'result').count() && await page.locator('.result.fail').count()) throw new Error('the reference solution for ' + cid + ' failed in training');
        await page.waitForTimeout(150);
      }
      throw new Error('training did not finish');
    };

    /** Fails the current lesson challenge once on purpose (a wrong program), returning when the result is shown. */
    const failOnce = async (page) => {
      await setCode(page, 'print("nope")');
      await tid(page, 'submit').click();
      await tid(page, 'result').waitFor({ timeout: 30000 });
    };

    await test('Training Grounds: a failure sends the player to a separate place, blocks the lesson, and the return is to the SAME step', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, PY_EARLY.slice(0, 4));
      await gotoArea(page, 'training-grounds');
      await openLesson(page, 'py-05-numbers');
      await advanceToChallengeId(page, 'py-05-crates');
      const stepBefore = await page.locator('.lesson-body').first().getAttribute('data-step');
      const lessonBefore = (await readSave(page)).learning.lessons['py-05-numbers'];
      await failOnce(page);
      // The Mentor diagnoses and directs: ONE button, no retry, no second training interface.
      await tid(page, 'diagnosis').waitFor();
      const mentor = await tid(page, 'diagnosis').innerText();
      assert(/You struggled with/.test(mentor) && /train this skill before continuing/.test(mentor), 'mentor wording: ' + mentor);
      eq(await tid(page, 'diagnosis').locator('button').count(), 1, 'the Mentor has exactly one action');
      eq(await tid(page, 'go-training').count(), 1, 'the single action is Go to the Training Grounds');
      eq(await tid(page, 'train-now').count(), 0, 'no duplicate train button');
      eq(await tid(page, 'other-variant').count(), 0, 'no "try a different problem" while training is required');
      assert(await tid(page, 'submit').isDisabled(), 'the failed challenge cannot be retried');
      assert(await tid(page, 'continue').isDisabled() || await tid(page, 'back').isDisabled(), 'the lesson controls are held');
      await page.screenshot({ path: SHOTS + '49-mentor-diagnosis.png' });
      const held = await readSave(page);
      assert(held.training.weaknesses.some((w) => w.required && w.status !== 'resolved'), 'a required weakness is saved');
      // Leaving and coming straight back to the lesson (or reloading the page) still shows the block, never the challenge.
      await tid(page, 'go-training').click();
      await tid(page, 'training-yard').waitFor();
      eq(await tid(page, 'training-yard').getAttribute('data-required'), 'yes', 'the Training Grounds knows training is required');
      await page.screenshot({ path: SHOTS + '50a-training-grounds-required.png' });
      await page.reload();
      await tid(page, 'hud').waitFor();
      const saved = await readSave(page);
      assert(saved.training.weaknesses.some((w) => w.required && w.status !== 'resolved') && saved.training.plans.some((p) => p.status === 'active' && p.required), 'required training survives a reload');
      await tid(page, 'required-banner').waitFor(); // every screen outside the lesson says what is pending, with one button
      eq(await tid(page, 'required-banner').locator('button').count(), 1, 'the banner has one action');
      await page.locator('button[title="World map"]').click();
      await tid(page, 'worldmap').waitFor();
      assert((await tid(page, 'area-training-yard').getAttribute('class')).includes('required'), 'the map highlights the Training Grounds');
      await page.screenshot({ path: SHOTS + '50c-map-required.png' });
      await tid(page, 'area-training-grounds').click();
      await openLesson(page, 'py-05-numbers');
      await tid(page, 'lesson-blocked').waitFor();
      eq(await page.locator('.cm-content').count(), 0, 'no code editor in the blocked lesson');
      eq(await tid(page, 'submit').count(), 0, 'the blocked lesson has no Submit button');
      await tid(page, 'go-training').click();
      await tid(page, 'start-training').click();
      await tid(page, 'training-run').waitFor();
      assert((await tid(page, 'training-return').innerText()).includes('exactly where you left off'), 'the header promises the return point');
      const during = await readSave(page);
      eq(JSON.stringify(during.learning.lessons['py-05-numbers']), JSON.stringify(lessonBefore), 'training does not touch lesson progress');
      await playTraining(page);
      await page.screenshot({ path: SHOTS + '50b-training-complete.png' });
      await tid(page, 'training-return-btn').click();
      await tid(page, 'lesson').waitFor();
      eq(await tid(page, 'lesson-blocked').count(), 0, 'training done: nothing blocks the lesson any more');
      eq(await page.locator('.lesson-body').first().getAttribute('data-step'), stepBefore, 'back on the same lesson step');
      const after = await readSave(page);
      assert(after.training.plans.some((p) => p.status === 'complete'), 'the plan is complete');
      assert(after.evidence.some((r) => r.source === 'training' && r.passed), 'training left evidence');
      assert(after.evidence.filter((r) => r.source !== 'training').every((r) => r.executed !== false), 'earlier evidence is untouched');
      eq(after.training.plans.at(-1).steps.filter((x) => x.kind === 'independent' && x.passed).length, 1, 'exactly one fresh proof was passed');
      await page.screenshot({ path: SHOTS + '50-training-return.png' });
      eq(page.errors.length, 0, 'console errors: ' + page.errors.join('|'));
      await page.context().close();
    });

    await test('Training content: reframing and a prediction come first, the proof is one hint-free problem in another context', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, PY_EARLY.slice(0, 4));
      await gotoArea(page, 'training-grounds');
      await openLesson(page, 'py-05-numbers');
      await advanceToChallengeId(page, 'py-05-crates');
      const lessonChallenge = await tid(page, 'briefing').getAttribute('data-challenge');
      await failOnce(page);
      await tid(page, 'go-training').click();
      await tid(page, 'start-training').click();
      await tid(page, 'training-run').waitFor();
      assert((await tid(page, 'training-progress').innerText()).includes('A different way to see it'), 'the first step is a different way to see the idea');
      await tid(page, 'training-read').click();
      // walk to the proof, making sure no step is the failed lesson's own problem
      for (let guard = 0; guard < 30; guard++) {
        if (await tid(page, 'training-complete').count()) break;
        const kind = await tid(page, 'training-run').getAttribute('data-step-kind');
        if (kind === 'predict') {
          await tid(page, 'predict-0').click();
          if (await tid(page, 'predict-wrong').count()) { for (let i = 1; i < 4 && !(await tid(page, 'predict-right').count()); i++) await tid(page, `predict-${i}`).click(); }
          await tid(page, 'training-read').click();
          continue;
        }
        if (await tid(page, 'training-read').count()) { await tid(page, 'training-read').click(); continue; }
        if (await tid(page, 'training-start-step').count()) await tid(page, 'training-start-step').click();
        await tid(page, 'briefing').waitFor();
        const cid = await tid(page, 'briefing').getAttribute('data-challenge');
        assert(cid !== lessonChallenge, 'training never re-serves the failed challenge');
        if (kind === 'independent') { eq(await tid(page, 'hint').count(), 0, 'the fresh proof has no hints'); assert(/independent trial/i.test(await tid(page, 'mode-badge').innerText()), 'the proof is an independent trial'); }
        await solveAny(page, cid);
        await tid(page, 'submit').click();
        await tid(page, 'result').or(tid(page, 'training-intro')).or(tid(page, 'training-read')).or(tid(page, 'training-complete')).first().waitFor({ timeout: 60000 });
        await page.waitForTimeout(150);
      }
      await tid(page, 'training-complete').waitFor();
      await page.context().close();
    });

    await test('Hint flow: a hinted challenge pass leads to short training and one fresh proof', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, PY_EARLY.slice(0, 4));
      await gotoArea(page, 'training-grounds');
      await openLesson(page, 'py-05-numbers');
      await advanceToChallengeId(page, 'py-05-crates');
      await tid(page, 'hint').click();
      const cid = await tid(page, 'briefing').getAttribute('data-challenge');
      await solveAny(page, cid);
      await tid(page, 'submit').click();
      await page.locator('.result.pass').waitFor({ timeout: 30000 });
      await tid(page, 'diagnosis').waitFor();
      eq(await tid(page, 'diagnosis').locator('button').count(), 1, 'the Mentor has one action after a hinted pass too');
      await tid(page, 'go-training').click();
      await tid(page, 'start-training').click();
      const plan = (await readSave(page)).training.plans.at(-1);
      eq(plan.steps.map((x) => x.kind).join(','), 'review,independent', 'a hint means short reinforcement, then one fresh proof');
      await page.context().close();
    });

    const PY_THROUGH_14 = [...PY_EARLY, 'py-14-independent-trial'];
    await test('Summit: locked until the first independent trial; then bosses show honest status and reasons', async () => {
      const page = await newPage();
      await startGame(page);
      await tid(page, 'dialogue').waitFor();
      await seed(page, PY_EARLY);
      await gotoArea(page, 'summit');
      await tid(page, 'locked-screen').waitFor();
      await seed(page, PY_THROUGH_14);
      await gotoArea(page, 'summit');
      await tid(page, 'boss-hall').waitFor();
      eq(await tid(page, 'boss-mini-python-functions').getAttribute('data-status'), 'ready', 'the first guardian can be faced');
      eq(await tid(page, 'boss-mastery-python').getAttribute('data-status'), 'locked', 'the mastery trial is locked');
      assert((await tid(page, 'boss-mastery-python').locator('[data-testid=boss-lock-reason]').innerText()).length > 10, 'the lock says why');
      eq(await tid(page, 'boss-summit').getAttribute('data-status'), 'locked', 'the capstone is locked');
      assert((await tid(page, 'campaign-progress').innerText()).includes('0 of'), 'progress line');
      await page.screenshot({ path: SHOTS + '51-boss-hall.png' });
      await page.context().close();
    });

    await test('Boss: a miss is diagnosed and sealed, training returns to the gate, and the retry is a NEW problem that can be won', async () => {
      const page = await newPage();
      await startGame(page);
      await tid(page, 'dialogue').waitFor();
      await seed(page, PY_THROUGH_14);
      await gotoArea(page, 'summit');
      await tid(page, 'boss-open-mini-python-functions').click();
      await tid(page, 'boss-begin').click();
      await tid(page, 'briefing').waitFor();
      const first = await tid(page, 'briefing').getAttribute('data-challenge');
      eq(await tid(page, 'hint').count(), 0, 'a boss has no hints');
      const focusBefore = (await readSave(page)).stats.focus;
      await setCode(page, 'def first_repeat(badges):\n    return None\n');
      await tid(page, 'submit').click();
      await tid(page, 'boss-defeat').waitFor({ timeout: 30000 });
      const failed = await readSave(page);
      eq(failed.stats.focus, focusBefore, 'failing a boss costs no Focus');
      eq(failed.bosses['mini-python-functions'].attempts.length, 1, 'the attempt is recorded');
      assert(failed.evidence.at(-1).source === 'boss' && failed.evidence.at(-1).passed === false, 'boss failure is evidence');
      // SEALED -> DIAGNOSIS (Mentor, one button) -> TRAINING GROUNDS -> training -> new version; there is no "try again" here
      eq(await tid(page, 'boss-defeat').locator('[data-testid=diagnosis] button').count(), 1, 'the boss diagnosis has one action');
      eq(await tid(page, 'boss-begin').count() + await tid(page, 'boss-open-mini-python-functions').count(), 0, 'no immediate retry after a boss miss');
      await tid(page, 'go-training').click();
      await tid(page, 'training-yard').waitFor();
      await tid(page, 'start-training').click();
      await tid(page, 'training-run').waitFor();
      assert((await tid(page, 'training-return').innerText()).includes('boss gate'), 'the return point is the boss gate');
      await playTraining(page);
      await tid(page, 'training-return-btn').click();
      await tid(page, 'boss-hall').waitFor();
      eq(await tid(page, 'boss-mini-python-functions').getAttribute('data-status'), 'ready', 'training completed: the gate opens again');
      await tid(page, 'boss-open-mini-python-functions').click();
      await tid(page, 'boss-begin').click();
      await tid(page, 'briefing').waitFor();
      const second = await tid(page, 'briefing').getAttribute('data-challenge');
      assert(second !== first, 'a different problem: ' + first + ' vs ' + second);
      await solveAny(page, second);
      await tid(page, 'submit').click();
      await tid(page, 'boss-victory').waitFor({ timeout: 30000 });
      const won = await readSave(page);
      assert(won.bosses['mini-python-functions'].passedAt, 'the boss is recorded as defeated');
      assert(won.achievements['first-boss'] && won.achievements['back-stronger'], 'boss achievements');
      await page.screenshot({ path: SHOTS + '52-boss-victory.png' });
      eq(page.errors.length, 0, 'console errors: ' + page.errors.join('|'));
      await page.context().close();
    });

    await test('Skills: the evidence view shows history next to mastery, never a score', async () => {
      const page = await newPage();
      await startGame(page);
      await seed(page, PY_EARLY.slice(0, 4));
      await gotoArea(page, 'training-grounds');
      await openLesson(page, 'py-05-numbers');
      await advanceToChallengeId(page, 'py-05-crates');
      await failOnce(page);
      await openPanel(page, 'skills');
      assert(await page.locator('[data-testid^=history-]').count() >= 1, 'a history note is shown for the skill with recent trouble');
      const text = await tid(page, 'skills-view').innerText();
      assert(!/\bXP\b|\blevel\b/i.test(text.replace(/XP and level never appear here because they do not prove skill\./i, '')), 'no XP or level in the evidence view');
      await page.context().close();
    });

    console.log('Robustness');
    await test('corrupt save is backed up, not destroyed', async () => {
      const page = await newPage();
      await page.evaluate(() => localStorage.setItem('codequest.save', '{corrupt'));
      await page.reload();
      await tid(page, 'begin').waitFor();
      eq(await page.evaluate(() => localStorage.getItem('codequest.save.backup')), '{corrupt', 'backup kept');
      await page.context().close();
    });

    await test('responsive: phone layout has no horizontal scroll on key screens', async () => {
      const page = await newPage({ width: 390, height: 800 });
      const noOverflow = async (label) => {
        const over = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
        assert(over <= 1, `${label}: horizontal overflow ${over}px`);
      };
      await noOverflow('title');
      await page.screenshot({ path: SHOTS + '20-mobile-title.png' });
      await startGame(page);
      await tid(page, 'dialogue').waitFor(); await noOverflow('academy');
      await page.screenshot({ path: SHOTS + '21-mobile-academy.png' });
      await introAndAccept(page); await noOverflow('grounds');
      await page.locator('button[title="World map"]').click(); await noOverflow('map');
      await page.screenshot({ path: SHOTS + '22-mobile-map.png' });
      await tid(page, 'area-training-grounds').click();
      await openLesson(page, 'py-01-first-program');
      await tid(page, 'continue').click(); await noOverflow('lesson demo');
      await page.screenshot({ path: SHOTS + '23-mobile-lesson.png', fullPage: true });
      await page.context().close();
    });
  } finally {
    await browser.close();
    server.kill();
  }
  console.log(`\n${passed} passed, ${failures.length} failed`);
  if (failures.length) { console.log('FAILED:', failures.join('; ')); process.exit(1); }
}
main().catch((e) => { console.error(e); process.exit(1); });
