import type { ReferenceEntry } from './reference';

/**
 * Field Manual entries for the Phase 5 worlds: R, spreadsheets, Git and the statistics modules of Python.
 * Every example is executed by reference.pro.test.ts (R in webR, formulas in the spreadsheet engine against
 * MANUAL_WORKBOOK, Git commands in the Git simulator against MANUAL_REPO, Python in Pyodide), so the documentation cannot rot.
 */
const mk = (language: ReferenceEntry['language']) => (id: string, group: string, title: string, signature: string, summary: string, details: string, example: string, keywords: string[] = []): ReferenceEntry => ({ id, language, group, title, signature, summary, details, example, keywords });
const r = mk('r');
const xl = mk('sheet');
const git = mk('git');
const py = mk('python');

/** The workbook every spreadsheet example is evaluated against. Sheet1 is a sales list; H1:I4 a rate table; K1:K6 some numbers. */
export const MANUAL_WORKBOOK = {
  sheets: {
    Sheet1: {
      A1: 'Region', B1: 'Rep', C1: 'Product', D1: 'Amount',
      A2: 'East', B2: 'ana lopez', C2: 'Tools', D2: 120, A3: 'West', B3: ' Ben  Reed ', C3: 'Paint', D3: 80, A4: 'East', B4: 'Caz Dunn', C4: 'Paint', D4: 60,
      A5: 'North', B5: 'Dev Shah', C5: 'Tools', D5: 200, A6: 'West', B6: 'Eli Park', C6: 'Tools', D6: 40, A7: 'East', B7: 'Fay Wu', C7: 'Tools', D7: 15,
      F1: 'Code', G1: 'Text', F2: 'NYC-2024-0042', G2: '2024-03-09',
      H1: 'From', I1: 'Rate', H2: 0, I2: 0.1, H3: 10000, I3: 0.2, H4: 40000, I4: 0.3,
      K1: 4, K2: 8, K3: 6, K4: 5, K5: 3, K6: 50, L1: 0.2,
    },
  },
} as const;

/** The repository every Git example runs against: main with two commits, a feature branch and a tracked file. */
export const MANUAL_REPO = {
  files: { 'notes.txt': 'line one\nline two\n' },
  commits: [
    { id: 'c1', branch: 'main', message: 'Start notes', files: { 'notes.txt': 'line one\n' } },
    { id: 'c2', branch: 'main', message: 'Add second line', files: { 'notes.txt': 'line one\nline two\n' } },
    { id: 'c3', branch: 'feature', parent: 'c2', message: 'Try a new idea', files: { 'notes.txt': 'line one\nline two\nidea\n' } },
  ],
  branches: { main: 'c2', feature: 'c3' },
  head: 'main',
  remote: 'https://example.org/team/notes.git',
  origin: { main: 'c2' },
};

export const proReference: ReferenceEntry[] = [
  // ------------------------------------------------------------------ R
  r('r-assign-print', 'basics', 'Assign, print and cat', 'x <- 5   ·   print(x)   ·   cat("a", x, "\\n")', 'Name a value, show it with its index, or print plain text.', '`<-` assigns. `print(x)` shows `[1] 5` (the index is normal). `cat` joins its arguments with a space and prints plain text without quotes; add `"\\n"` for a new line. `sprintf("%.2f", x)` formats a number.', 'x <- 12.3456\nprint(x)\ncat("Value:", round(x, 2), "\\n")\ncat(sprintf("%.1f%%\\n", 45.67))', ['show', 'output', 'format number', 'decimals']),
  r('r-read-lines', 'input', 'readLines and as.numeric', 'readLines("file.txt")   ·   as.numeric(text)', 'Read a text file into a character vector, one element per line, and convert text to numbers.', 'Everything from a file is text until you convert it. `readLines(file, n = 1)` reads only the first lines. Non-numeric text becomes `NA` with a warning.', 'writeLines(c("150", "2.5"), "trip.txt")\nv <- as.numeric(readLines("trip.txt"))\nprint(v[1] / v[2])', ['read file', 'text to number', 'convert']),
  r('r-vector', 'vectors', 'Vectors: c, index, filter', 'c(1, 2, 3)   ·   x[2]   ·   x[x > 5]   ·   x[-1]', 'Create a vector, pick elements by position or by a condition.', 'Positions start at 1. A logical vector picks the TRUE positions. A negative index drops an element. Operations (`x * 2`, `x > 5`) apply to every element.', 'x <- c(4, 8, 6, 5, 3, 50)\nprint(x[x > 5])\nprint(x[2:3])\nprint(x[-1])\nprint(sum(x > 5))', ['filter', 'subset', 'select elements', 'logical index']),
  r('r-summary', 'vectors', 'sum, mean, median, sd, min, max', 'sum(x)   ·   mean(x)   ·   median(x)   ·   sd(x)   ·   range(x)', 'Summaries of a numeric vector.', '`sd` is the sample standard deviation (n − 1). Missing values (`NA`) make a summary `NA`: pass `na.rm = TRUE` to ignore them. `quantile(x, 0.9)` gives a percentile; `summary(x)` prints the five-number summary.', 'x <- c(4, 8, 6, 5, 3, NA)\nprint(mean(x, na.rm = TRUE))\nprint(sd(c(4, 8, 6, 5, 3)))\nprint(quantile(c(1, 2, 3, 4, 5), 0.9))', ['average', 'standard deviation', 'percentile', 'missing']),
  r('r-sort-order', 'vectors', 'sort, order, rev, head', 'sort(x, decreasing = TRUE)   ·   order(x)   ·   rev(x)   ·   head(x, n)', 'Sort values, get the order that sorts them, reverse, take the first n.', '`order` returns positions, which is what you need to sort a whole data frame by one column. `head(x, -1)` drops the last element.', 'x <- c(30, 10, 20)\nprint(sort(x))\nprint(order(x))\nprint(head(sort(x, decreasing = TRUE), 2))\nprint(rev(x))', ['top n', 'ascending', 'descending', 'rank']),
  r('r-running', 'vectors', 'cumsum, diff, which, cumprod', 'cumsum(x)   ·   diff(x)   ·   which(cond)   ·   which.max(x)', 'Running totals, differences between neighbours, and positions.', '`cumsum` gives a running total, `diff` the change from one element to the next (one shorter). `which(x > 5)` gives positions; `which.max(x)` the position of the first maximum.', 'x <- c(3, 5, 4, 10)\nprint(cumsum(x))\nprint(diff(x))\nprint(which(x > 4))\nprint(which.max(x))', ['running total', 'change', 'position of maximum', 'cumulative']),
  r('r-ifelse', 'control flow', 'if/else and ifelse', 'if (cond) a else b   ·   ifelse(cond, yes, no)', 'Decide for one value with if, for a whole vector with ifelse.', '`if` needs a single TRUE/FALSE and fails on a vector. `ifelse` returns a vector of the same length as `cond`; nest it for more than two outcomes. `cut` turns numbers into labelled bands.', 'score <- c(35, 50, 80)\nprint(ifelse(score >= 50, "pass", "fail"))\nprint(as.character(cut(score, c(-Inf, 40, 70, Inf), labels = c("low", "mid", "high"), right = FALSE)))', ['vectorised', 'classify', 'bands', 'conditional']),
  r('r-function', 'functions', 'function, return, default arguments', 'f <- function(x, rate = 0.2) { ... }', 'Package a calculation; the last value is returned.', 'Arguments can have defaults. `stopifnot(cond)` stops with an error if a condition is false, which is how you check inputs and write small tests. `rle(x)` returns run lengths: `max(rle(x)$lengths)` is the longest streak.', 'with_tax <- function(price, rate = 0.2) round(price * (1 + rate), 2)\nprint(with_tax(100))\nprint(with_tax(c(10, 20), 0.1))\nstopifnot(with_tax(100) == 120)\nprint(max(rle(c(1, 1, 2, 2, 2))$lengths))', ['define function', 'default value', 'test', 'streak', 'run length']),
  r('r-read-csv', 'data frames', 'read.csv and inspecting a data frame', 'read.csv("f.csv")   ·   nrow(d)   ·   names(d)   ·   head(d)   ·   str(d)   ·   d$col', 'Load a CSV into a data frame and look at it.', 'Quoted values with commas are handled. Always look first: `str(d)` shows each column and its type. `d$col` is a column (a vector); `d[rows, cols]` picks rows and columns.', 'writeLines(c("name,dept,salary", "Ana,Ops,48000", "Ben,Eng,72000"), "staff.csv")\nd <- read.csv("staff.csv")\nprint(nrow(d))\nprint(names(d))\nprint(mean(d$salary))', ['import csv', 'table', 'columns', 'rows']),
  r('r-filter-rows', 'data frames', 'Filter rows and add a column', 'd[d$x > 5 & d$y == "a", ]   ·   subset(d, x > 5)   ·   d$new <- d$a * d$b', 'Keep the rows that meet conditions; derive a new column.', 'Rows come before the comma, columns after; an empty slot means all. Combine conditions with `&` and `|`. `subset(d, cond)` is a shorter form for interactive use.', 'd <- data.frame(item = c("a", "b", "c"), qty = c(3, 10, 7), price = c(2, 1.5, 4))\nd$total <- d$qty * d$price\nprint(d[d$qty > 5 & d$price < 4, ])\nprint(subset(d, total > 15)$item)', ['where', 'select rows', 'derived column', 'mutate']),
  r('r-aggregate', 'data frames', 'aggregate and tapply: per-group summaries', 'aggregate(y ~ g, data = d, FUN = mean)   ·   tapply(d$y, d$g, sum)', 'Summarise a column for each group.', '`aggregate` returns a data frame with one row per group (sorted by group). `tapply` returns a named vector. `table(d$g)` counts rows per group.', 'd <- data.frame(dept = c("A", "B", "A"), pay = c(10, 20, 30))\nprint(aggregate(pay ~ dept, data = d, FUN = mean))\nprint(tapply(d$pay, d$dept, sum))\nprint(table(d$dept))', ['group by', 'summary per group', 'count by', 'pivot']),
  r('r-merge', 'data frames', 'merge: join two tables', 'merge(a, b, by = "key", all.x = TRUE)', 'Combine two data frames on a shared column.', 'By default only matching keys are kept (inner join). `all.x = TRUE` keeps every row of the first table (missing values become `NA`); `all = TRUE` keeps both. The result is sorted by the key: re-sort with `order`.', 'emp <- data.frame(name = c("Ana", "Ben"), dept = c("OPS", "ZZ"))\ndepts <- data.frame(dept = "OPS", boss = "Kim")\nprint(merge(emp, depts, by = "dept", all.x = TRUE))', ['join', 'left join', 'lookup', 'vlookup']),
  r('r-tests', 'statistics', 'cor, lm, t.test, prop.test', 'cor(x, y)   ·   coef(lm(y ~ x))   ·   t.test(y ~ g, data = d)   ·   prop.test(c(x1, x2), c(n1, n2))', 'Correlation, a best-fit line, and tests for a difference between groups.', 'Each test returns a list: take `$p.value`, `$estimate`, `$conf.int`. `t.test` without `var.equal = TRUE` is Welch’s test. A small p-value (below 0.05 is the usual bar) means the difference is unlikely to be chance; it says nothing about whether it matters.', 'x <- c(1, 2, 3, 4, 5, 6)\ny <- c(2.1, 3.9, 6.2, 8.1, 9.8, 12.2)\nprint(round(cor(x, y), 3))\nprint(round(coef(lm(y ~ x))[2], 2))\nprint(round(t.test(y, x)$p.value, 4))\nprint(round(prop.test(c(30, 45), c(100, 100))$p.value, 4))', ['p-value', 'significance', 'regression', 'compare groups', 'slope']),

  // ------------------------------------------------------------------ Spreadsheets (examples are formulas evaluated against MANUAL_WORKBOOK)
  xl('xl-sum', 'basics', 'SUM, AVERAGE, MIN, MAX, COUNT, MEDIAN', '=SUM(range)   ·   =AVERAGE(range)   ·   =COUNT(range)', 'Summaries of a range of cells.', '`COUNT` counts numbers, `COUNTA` counts non-empty cells, `COUNTBLANK` empty ones. Ranges ignore text. `LARGE(range, 2)` is the second largest, `SMALL` the smallest; `ROUND(x, 2)` rounds.', '=SUM(K1:K6)\n=ROUND(AVERAGE(K1:K6), 1)\n=MEDIAN(K1:K6)\n=LARGE(K1:K6, 2)', ['total', 'average', 'largest', 'smallest', 'count']),
  xl('xl-reference', 'basics', 'Cell references: relative and absolute', '=B2*$L$1   ·   $A1   ·   A$1', 'Lock a reference with $ so it does not move when the formula is copied.', 'A relative reference (`B2`) shifts when copied; `$L$1` always points at L1. Keep assumptions (rates, limits) in labelled cells and refer to them: never type them into a formula.', '=D2*(1+$L$1)\n=D3*(1+$L$1)', ['absolute', 'dollar sign', 'lock', 'copy down', 'assumption']),
  xl('xl-if', 'logic', 'IF, IFS, AND, OR, IFERROR', '=IF(test, yes, no)   ·   =IF(AND(a, b), ...)   ·   =IFERROR(formula, fallback)', 'Formulas that decide, and formulas that survive errors.', 'Nest IFs for more than two outcomes, checking the boundary you mean (`>=` vs `>`). `AND` needs all tests true, `OR` any. `IFERROR` replaces an error such as `#DIV/0!` with a fallback: use it for expected gaps, not to hide mistakes.', '=IF(D2>=100,"big","small")\n=IF(AND(D2>50,C2="Tools"),"yes","no")\n=IFERROR(D2/0,"n/a")', ['conditional', 'nested if', 'tiers', 'error', 'divide by zero']),
  xl('xl-vlookup', 'lookups', 'VLOOKUP and approximate match', '=VLOOKUP(key, table, column, FALSE)   ·   =VLOOKUP(key, table, column, TRUE)', 'Find a value in the first column of a table and return another column.', '`FALSE` is exact match. `TRUE` (approximate) needs the first column sorted ascending and returns the row of the largest value not above the key: use it for bands (tax brackets, shipping tiers). The key must be in the LEFT column.', '=VLOOKUP(25000,H2:I4,2,TRUE)\n=VLOOKUP(10000,H2:I4,2,FALSE)', ['lookup', 'bands', 'brackets', 'find in table']),
  xl('xl-index-match', 'lookups', 'INDEX / MATCH and XLOOKUP', '=INDEX(return_range, MATCH(key, lookup_range, 0))   ·   =XLOOKUP(key, lookup_range, return_range)', 'Look up in any column, including one to the left of the key.', '`MATCH(key, range, 0)` gives the position of an exact match; `INDEX(range, n)` takes the nth cell. Wrap in `IFERROR` for keys that may be missing. `XLOOKUP` does both in one call.', '=INDEX(D2:D7,MATCH("Caz Dunn",B2:B7,0))\n=IFERROR(INDEX(A2:A7,MATCH("Nobody",B2:B7,0)),"not found")\n=XLOOKUP("Eli Park",B2:B7,D2:D7)', ['reverse lookup', 'left lookup', 'find position']),
  xl('xl-sumifs', 'conditional totals', 'SUMIF, SUMIFS, COUNTIF(S), AVERAGEIF(S)', '=SUMIFS(sum_range, range1, test1, range2, test2)   ·   =COUNTIFS(range, test)   ·   =AVERAGEIF(range, test, avg_range)', 'Totals, counts and averages of only the rows that match.', 'In `SUMIFS` the **sum range comes first**. Tests are text: `"East"`, `">100"`, `"<>North"`; a test built from a cell is `">="&L1`. All tests must hold.', '=SUMIFS(D2:D7,A2:A7,"East",C2:C7,"Tools")\n=COUNTIFS(A2:A7,"East",D2:D7,">=100")\n=AVERAGEIF(A2:A7,"West",D2:D7)\n=SUMIF(D2:D7,">"&K1)', ['conditional sum', 'count if', 'group total', 'filter and add']),
  xl('xl-text', 'cleaning', 'Text: TRIM, PROPER, LEFT, MID, FIND, SUBSTITUTE, TEXT', '=TRIM(t)   ·   =MID(t, start, length)   ·   =FIND(small, big)   ·   =VALUE(t)', 'Clean and split text.', '`FIND("-", t, start)` gives the position of a dash (the optional third argument starts the search later, which finds the second dash). `VALUE("42")` turns text into a number. `TEXT(7,"000")` formats a number as `007`. `&` joins text.', '=PROPER(TRIM(B3))\n=VALUE(MID(F2,FIND("-",F2)+1,4))\n=SUBSTITUTE(F2,"-","/")\n=TEXT(7,"000")&"-"&UPPER(LEFT(B2,1))', ['clean data', 'split code', 'extract', 'capitalise', 'spaces']),
  xl('xl-rank-join', 'analysis', 'RANK, SUMPRODUCT, TEXTJOIN', '=RANK(value, range, 0)   ·   =SUMPRODUCT(a_range, b_range)   ·   =TEXTJOIN(sep, ignore_empty, range)', 'Positions, weighted sums and joined text without helper columns.', '`RANK` gives a position: order 0 puts the largest first, 1 the smallest first; lock the range with `$` when copying down. `SUMPRODUCT` multiplies two ranges cell by cell and adds the products, so divide by the total weight for a weighted average. `TEXTJOIN` joins a whole range with a separator; its second argument says whether to skip empty cells.', '=RANK(K2,$K$1:$K$6,0)\n=SUMPRODUCT(K1:K3,K4:K6)/SUM(K4:K6)\n=TEXTJOIN(", ",TRUE,A2:A4)', ['position', 'weighted average', 'join text', 'concatenate', 'ranking']),
  xl('xl-dates', 'cleaning', 'Dates: DATE, MONTH, YEAR, DAY, WEEKDAY', '=DATE(y, m, d)   ·   =MONTH(date)   ·   =WEEKDAY(date, 2)', 'Build real dates from parts and ask calendar questions.', '`WEEKDAY(date, 2)` numbers Monday = 1 to Sunday = 7, so weekends are 6 and 7. A quarter is `ROUNDUP(MONTH(d)/3, 0)`. Dates are numbers: subtracting two dates gives days between.', '=DATE(2024,3,9)\n=WEEKDAY(DATE(2024,3,9),2)\n=ROUNDUP(MONTH(DATE(2024,8,17))/3,0)', ['quarter', 'weekend', 'calendar', 'text to date']),
  xl('xl-pivot', 'analysis', 'Pivot tables and choosing a chart', 'Pivot builder: source range (with header), group-by field, value field, how to aggregate, optional filter', 'Summarise many rows by group without formulas, then chart the summary.', 'The source range includes the header row and every data row. Choose sum, count, average, min or max to match the question. Chart type: **line** for change over time, **column/bar** to compare categories, **pie** only for the parts of a whole, **scatter** for two measurements.', '=SUMIFS(D2:D7,A2:A7,"East")', ['group by', 'summary table', 'chart', 'trend']),

  // ------------------------------------------------------------------ Git (examples are run in the Git simulator against MANUAL_REPO)
  git('git-status-diff', 'basics', 'git status, diff and log', 'git status   ·   git diff   ·   git log --oneline', 'See what changed, and what has already been committed.', '`status` lists changed and staged files. `diff` shows unstaged changes (`diff --staged` the staged ones). `log --oneline` lists commits, newest first. Run `status` before every commit.', 'git status\ngit log --oneline', ['what changed', 'history', 'inspect', 'changes']),
  git('git-commit', 'basics', 'git add and git commit', 'git add <file>   ·   git commit -m "message"', 'Stage changes, then record them as a commit.', 'Stage only what belongs in the commit, then write the message in the imperative (“Add alarm threshold”). `git commit -am` stages tracked files too. A commit needs at least one staged change.', 'echo "a third line" >> notes.txt\ngit add notes.txt\ngit commit -m "Add third line"', ['save', 'snapshot', 'stage', 'message']),
  git('git-undo', 'history', 'Undo: restore, reset and revert', 'git restore <file>   ·   git restore --staged <file>   ·   git reset --hard <commit>   ·   git revert <commit>', 'Throw away changes, unstage, move the branch back, or undo a commit safely.', '`restore` discards working changes (they are gone). `reset --hard` moves the branch and erases later commits from it: never on commits others have. `revert` adds a NEW commit that undoes an old one, which is safe on shared history.', 'echo "oops" >> notes.txt\ngit restore notes.txt\ngit revert HEAD --no-edit', ['undo', 'mistake', 'go back', 'discard changes']),
  git('git-branch', 'branches', 'git branch and git switch', 'git branch   ·   git switch -c <name>   ·   git switch <name>', 'List, create and change branches.', 'A branch is a movable label on a commit. Always know which branch HEAD is on before committing. `switch -c` creates and moves in one step.', 'git branch\ngit switch -c experiment\ngit branch', ['checkout', 'new branch', 'switch branch', 'parallel']),
  git('git-merge', 'branches', 'git merge and conflicts', 'git merge <branch>   ·   git merge --abort', 'Bring another branch’s work into the current branch.', 'A fast-forward just moves the label. When both sides changed the same lines you get a **conflict**: the file contains `<<<<<<<`, `=======`, `>>>>>>>` markers. Edit the file to say what it should say, remove every marker, `git add` it and `git commit`. `--abort` returns to before the merge.', 'git merge feature', ['combine', 'conflict', 'integrate', 'fast-forward']),
  git('git-remote', 'collaboration', 'git remote, push, fetch and pull', 'git remote -v   ·   git push -u origin <branch>   ·   git fetch   ·   git pull', 'Share work with a server and get other people’s work.', '`push -u origin <branch>` uploads and remembers the upstream. `fetch` downloads without changing your branch; `pull` fetches then merges. If a push is rejected, someone else pushed first: pull, resolve, push again. Never force-push a shared branch.', 'git remote -v\ngit fetch', ['origin', 'upload', 'download', 'rejected', 'share']),
  git('git-stash-tag', 'workflow', 'git stash and git tag', 'git stash   ·   git stash pop   ·   git tag <name>', 'Put unfinished work aside; label a release.', '`stash` saves uncommitted changes and cleans the working tree so you can switch branches; `stash pop` brings them back. A tag is a permanent name for a commit, such as a release.', 'echo "draft" >> notes.txt\ngit stash\ngit stash pop\ngit tag v1.0', ['set aside', 'shelve', 'release', 'label']),

  // ------------------------------------------------------------------ Python: statistics and randomness
  py('py-statistics-spread', 'statistics', 'statistics: stdev, pstdev, quantiles', 'statistics.stdev(data)   ·   statistics.pstdev(data)   ·   statistics.quantiles(data, n=4)', 'Spread of a list of numbers.', '`stdev` divides by n − 1 (a sample), `pstdev` by n (a whole population). `quantiles(data, n=4)` returns the three quartile cut points using its own method, which can differ from the “median of halves” rule: state the method you use.', 'import statistics\ndata = [4, 8, 6, 5, 3]\nprint(round(statistics.stdev(data), 3), round(statistics.pstdev(data), 3))\nprint(statistics.quantiles(data, n=4))', ['standard deviation', 'variance', 'quartile', 'spread']),
  py('py-statistics-correlation', 'statistics', 'statistics.correlation and linear_regression', 'statistics.correlation(x, y)   ·   statistics.linear_regression(x, y)', 'Pearson’s r and the best-fit line.', '`correlation` raises `StatisticsError` when an input has no variation. `linear_regression` returns `(slope, intercept)`.', 'import statistics\nx = [1, 2, 3, 4, 5]\ny = [2, 4, 5, 4, 5]\nprint(round(statistics.correlation(x, y), 3))\nprint(statistics.linear_regression(x, y))', ['r', 'relationship', 'best fit', 'slope']),
  py('py-random-rng', 'random', 'random.Random(seed): reproducible randomness', 'rng = random.Random(seed)   ·   rng.sample(items, k)   ·   rng.random()   ·   rng.choice(items)', 'A random generator you can repeat exactly.', 'The same seed gives the same sequence, which makes a simulation or a sample auditable. `sample` picks distinct items; `choice` may repeat; `random()` is a float in [0, 1). Create ONE generator and reuse it.', 'import random\nrng = random.Random(42)\nprint(rng.sample(range(100), 3))\nprint(round(rng.random(), 4))\nprint(random.Random(42).sample(range(100), 3))', ['seed', 'simulation', 'sample', 'shuffle', 'repeatable']),
  py('py-math-stats', 'math', 'math: sqrt, ceil, comb, isclose', 'math.sqrt(x)   ·   math.ceil(x)   ·   math.comb(n, k)   ·   math.isclose(a, b)', 'Square roots, rounding up, combinations, and safe float comparison.', 'Compare floats with `math.isclose`, not `==`. `math.ceil` rounds up: useful for percentile ranks and bin counts.', 'import math\nprint(math.sqrt(16), math.ceil(2.1), math.comb(5, 2))\nprint(math.isclose(0.1 + 0.2, 0.3))', ['square root', 'round up', 'combinations', 'float equal']),
  py('py-itertools-combinations', 'itertools', 'itertools.combinations', 'itertools.combinations(items, r)', 'Every way to choose r items, each set once, in order.', 'Order inside a combination follows the input order, so sort the input first when you need alphabetical pairs.', 'import itertools\nprint(list(itertools.combinations(["a", "b", "c"], 2)))', ['pairs', 'all pairs', 'choose']),
];
