/**
 * The Field Manual: the game's built-in documentation. It exists so the player practises what professionals
 * do when they meet something new: SEARCH the documentation, read the signature and example, form a hypothesis,
 * test it. Challenges are deliberately posed so some need tools that were never taught; the manual is where
 * to find them. Entries are short, accurate and runnable: reference.test.ts executes every example in real
 * Python/SQLite so the documentation cannot rot.
 *
 * Opening an entry while working on a challenge is recorded as `lookups` in the evidence (research behaviour);
 * it does not lower the reward: looking things up is a professional skill, not a crutch.
 */
export interface ReferenceEntry {
  id: string;
  /** 'python' | 'sql' */
  language: 'python' | 'sql' | 'web' | 'r' | 'sheet' | 'git';
  /** Module or topic group, e.g. 'statistics', 'str', 'SELECT'. */
  group: string;
  title: string;
  /** How it is written, e.g. `statistics.median(data)`. */
  signature: string;
  summary: string;
  /** What it returns / important behaviour, edge cases. */
  details: string;
  example: string;
  /** For SQL examples: the database the example runs against. */
  db?: string;
  /** Extra search words (synonyms a learner might type). */
  keywords: string[];
  /** Web entries: a tiny page that exercises the example, run in real Chromium by web.test.ts. */
  run?: import('./schema').WebFiles;
}

import { webReference } from './reference.web';
import { proReference } from './reference.pro';

const py = (id: string, group: string, title: string, signature: string, summary: string, details: string, example: string, keywords: string[] = []): ReferenceEntry => ({ id, language: 'python', group, title, signature, summary, details, example, keywords });
const sql = (id: string, group: string, title: string, signature: string, summary: string, details: string, example: string, db: string, keywords: string[] = []): ReferenceEntry => ({ id, language: 'sql', group, title, signature, summary, details, example, db, keywords });

const core: ReferenceEntry[] = [
  // ------------------------------------------------------------------ Python built-ins
  py('py-len', 'built-ins', 'len', 'len(x)', 'The number of items in a list, string, dict, set or tuple.', 'Returns an int. `len("")` and `len([])` are 0.', 'print(len([4, 5, 6]), len("hello"))', ['length', 'count items', 'size']),
  py('py-sum', 'built-ins', 'sum', 'sum(numbers, start=0)', 'Adds up the numbers in a list (or any iterable).', 'An empty list gives `start` (0). Only for numbers; to join strings use `"".join(...)`.', 'print(sum([1, 2, 3]), sum([]), sum([0.5, 0.25]))', ['total', 'add up']),
  py('py-min-max', 'built-ins', 'min and max', 'min(items, key=None)  /  max(items, key=None)', 'The smallest / largest item. `key` is a function that says what to compare.', 'An empty list raises `ValueError` (give `default=...` to avoid it). With ties, the first item wins.', 'orders = [{"n": "a", "v": 3}, {"n": "b", "v": 9}]\nprint(max(orders, key=lambda o: o["v"])["n"])\nprint(min([4, 2, 8]), max([], default=None))', ['largest', 'smallest', 'biggest', 'lowest', 'highest']),
  py('py-sorted', 'built-ins', 'sorted', 'sorted(items, key=None, reverse=False)', 'Returns a NEW sorted list. The original is unchanged.', '`key` chooses what to sort by; `reverse=True` sorts largest first. The sort is stable: equal items keep their order. `list.sort()` sorts in place and returns None.', 'print(sorted([3, 1, 2], reverse=True))\nprint(sorted(["bb", "a", "ccc"], key=len))', ['sort', 'order', 'rank', 'descending']),
  py('py-enumerate', 'built-ins', 'enumerate', 'enumerate(items, start=0)', 'Gives (position, item) pairs, so a loop can know where it is.', 'Use `for i, item in enumerate(items):`.', 'for i, name in enumerate(["a", "b", "c"], start=1):\n    print(i, name)', ['index', 'position', 'counter']),
  py('py-zip', 'built-ins', 'zip', 'zip(a, b, ...)', 'Walks several lists in step, giving tuples of matching items.', 'Stops at the shortest list.', 'names = ["a", "b"]\nscores = [90, 80]\nprint(list(zip(names, scores)))\nprint(dict(zip(names, scores)))', ['pair', 'combine lists', 'parallel']),
  py('py-round', 'built-ins', 'round', 'round(x, ndigits=None)', 'Rounds a number.', '`round(2.5)` is 2 and `round(3.5)` is 4 (ties go to the even number). Because floats are approximate, prefer formatting for display: `f"{x:.2f}"`.', 'print(round(3.14159, 2), round(2.5), f"{2.0:.2f}")', ['decimal places', 'round off']),
  py('py-isinstance', 'built-ins', 'isinstance', 'isinstance(value, kind)', 'True if the value is of that type (or one of several).', 'Note that `True` counts as an int. Pass a tuple for several kinds: `isinstance(x, (int, float))`.', 'print(isinstance(5, int), isinstance("5", int), isinstance(2.5, (int, float)))', ['type check']),
  py('py-any-all', 'built-ins', 'any and all', 'any(items)  /  all(items)', '`any` is True if at least one item is true; `all` is True if every item is true.', 'Both work well with a generator: `any(x > 5 for x in xs)`. `all([])` is True; `any([])` is False.', 'xs = [3, 8, 1]\nprint(any(x > 5 for x in xs), all(x > 0 for x in xs))', ['exists', 'every']),
  // ------------------------------------------------------------------ str / list / dict methods
  py('py-str-methods', 'str', 'String methods', 'text.strip() / .lower() / .upper() / .title() / .replace(a, b) / .startswith(x)', 'Common ways to clean and change text. Each returns a NEW string.', '`strip()` removes spaces (and newlines) at both ends; `replace` changes every occurrence; `startswith`/`endswith` test the ends.', 'print("  Hello, World  ".strip().lower().replace(",", ""))', ['strip', 'clean', 'trim', 'case', 'replace']),
  py('py-split-join', 'str', 'split and join', 'text.split(sep=None)  /  sep.join(items)', '`split` cuts text into a list; `join` glues a list of strings together.', '`split()` with no argument splits on any run of whitespace. `",".join(["a", "b"])` is `"a,b"`. Items given to `join` must be strings.', 'print("a b  c".split())\nprint("2024-03-01".split("-"))\nprint("-".join(["x", "y"]))', ['words', 'separate', 'tokens']),
  py('py-list-methods', 'list', 'List methods', 'items.append(x) / .extend(more) / .remove(x) / .pop(i) / .count(x) / .sort() / .reverse()', 'Change a list in place. Most return None.', '`append` adds one item; `extend` adds many; `pop()` removes and returns the last item. `.index(x)` finds a position but raises `ValueError` if absent.', 'xs = [3, 1]\nxs.append(2)\nxs.sort()\nprint(xs, xs.count(2))', ['append', 'add to list', 'remove']),
  py('py-dict-methods', 'dict', 'Dictionary methods', 'd.get(key, default) / d.items() / d.keys() / d.values() / d.setdefault(key, default) / d.pop(key) / d.update(other)', 'Read, loop over and change dictionaries.', '`get` avoids `KeyError`. `setdefault` inserts the default if the key is missing and returns the value, handy for grouping: `d.setdefault(k, []).append(x)`.', 'd = {"a": 1}\nd.setdefault("b", []).append(5)\nprint(d.get("z", 0), d, list(d.items()))', ['lookup', 'key', 'group', 'default']),
  // ------------------------------------------------------------------ statistics
  py('py-statistics-mean', 'statistics', 'statistics.mean', 'statistics.mean(data)', 'The arithmetic mean (average) of numbers.', 'Needs at least one value: an empty list raises `StatisticsError`. Returns a float for float input.', 'import statistics\nprint(statistics.mean([2, 4, 9]))', ['average']),
  py('py-statistics-median', 'statistics', 'statistics.median', 'statistics.median(data)', 'The middle value of sorted numbers. With an even count it is the mean of the two middle values.', 'Does not modify the list. An empty list raises `StatisticsError`. Less affected by extreme values than the mean.', 'import statistics\nprint(statistics.median([9, 1, 5]))\nprint(statistics.median([1, 2, 3, 10]))', ['middle', 'median', 'typical value']),
  py('py-statistics-stdev', 'statistics', 'statistics.stdev / pstdev', 'statistics.stdev(data)  /  statistics.pstdev(data)', 'How spread out the numbers are (sample and population standard deviation).', '`stdev` needs at least two values.', 'import statistics\nprint(round(statistics.pstdev([2, 4, 4, 4, 5, 5, 7, 9]), 2))', ['spread', 'standard deviation', 'variance']),
  py('py-statistics-mode', 'statistics', 'statistics.mode', 'statistics.mode(data)', 'The most common value.', 'With several equally common values it returns the first one encountered. Works on strings too. Empty data raises `StatisticsError`.', 'import statistics\nprint(statistics.mode(["a", "b", "a"]))', ['most common', 'most frequent']),
  // ------------------------------------------------------------------ collections
  py('py-collections-counter', 'collections', 'collections.Counter', 'Counter(items)  /  counter.most_common(n)', 'Counts how often each item occurs, in one line.', '`Counter(["a", "b", "a"])` behaves like a dict of counts. `.most_common(1)` gives `[(item, count)]` for the top item; equal counts keep the order in which items were first seen. Missing keys count as 0.', 'from collections import Counter\nc = Counter(["a", "b", "a", "c", "a"])\nprint(c["a"], c["zzz"], c.most_common(2))', ['count', 'frequency', 'tally', 'most common', 'occurrences']),
  py('py-collections-defaultdict', 'collections', 'collections.defaultdict', 'defaultdict(factory)', 'A dictionary that creates missing entries for you.', '`defaultdict(list)` gives an empty list for a new key; `defaultdict(int)` gives 0. Great for grouping and counting.', 'from collections import defaultdict\ngroups = defaultdict(list)\nfor k, v in [("a", 1), ("b", 2), ("a", 3)]:\n    groups[k].append(v)\nprint(dict(groups))', ['group', 'default value']),
  // ------------------------------------------------------------------ datetime & math
  py('py-datetime-date', 'datetime', 'datetime.date', 'date.fromisoformat("YYYY-MM-DD")  /  date(y, m, d)', 'A calendar date. Subtracting two dates gives a `timedelta`.', '`(d2 - d1).days` is the number of days between (negative if d2 is earlier). `d.weekday()` is 0 for Monday. `d + timedelta(days=7)` adds a week. Bad dates raise `ValueError`.', 'from datetime import date, timedelta\nd1 = date.fromisoformat("2024-03-01")\nd2 = date(2024, 3, 15)\nprint((d2 - d1).days, d1 + timedelta(days=7))', ['day', 'days between', 'calendar', 'difference between dates', 'schedule']),
  py('py-datetime-strftime', 'datetime', 'date.strftime', 'date.strftime(format)', 'Turns a date into text using format codes.', '`%A` full weekday name, `%a` short, `%B` month name, `%d` day, `%m` month number, `%Y` four-digit year.', 'from datetime import date\nd = date.fromisoformat("2024-03-01")\nprint(d.strftime("%A"), d.strftime("%d %B %Y"))', ['weekday', 'monday', 'format date', 'day name']),
  py('py-math', 'math', 'math module', 'math.sqrt(x) / math.floor(x) / math.ceil(x) / math.isclose(a, b) / math.pi', 'Mathematical functions.', '`floor` rounds down, `ceil` up. Use `math.isclose(a, b)` to compare floats instead of `==`.', 'import math\nprint(math.sqrt(16), math.ceil(2.1), math.isclose(0.1 + 0.2, 0.3))', ['square root', 'round up', 'round down', 'float compare']),
  py('py-random', 'random', 'random module', 'random.choice(items) / random.randint(a, b) / random.shuffle(items) / random.seed(n)', 'Random numbers and choices.', 'Results differ every run unless you call `random.seed(n)` first (useful for reproducible tests).', 'import random\nrandom.seed(1)\nprint(random.choice(["a", "b", "c"]) in "abc")', ['dice', 'shuffle', 'random']),
  // ------------------------------------------------------------------ files, csv, json, sqlite3
  py('py-open', 'files', 'open', 'open(path, mode="r", newline=None)  /  with open(...) as f:', 'Open a text file. Use `with` so it is closed for you.', 'Modes: `"r"` read, `"w"` write (erases), `"a"` append. `f.read()`, `f.readlines()`, `for line in f`, `f.write(text)`. For CSV pass `newline=""`.', 'with open("note.txt", "w") as f:\n    f.write("hi\\n")\nprint(open("note.txt").read())', ['read file', 'write file', 'text file']),
  py('py-csv', 'csv', 'csv module', 'csv.reader(f)  /  csv.DictReader(f)  /  csv.writer(f).writerow(row)', 'Read and write CSV files, including quoted commas.', '`DictReader` gives one dictionary per row using the header. Everything read is text. Never split a CSV line on commas yourself.', 'import csv, io\nrows = list(csv.DictReader(io.StringIO("a,b\\n1,\\"x, y\\"\\n")))\nprint(rows)', ['comma separated', 'spreadsheet', 'table']),
  py('py-json', 'json', 'json module', 'json.load(f)  /  json.dump(data, f)  /  json.loads(text)  /  json.dumps(data)', 'Convert between JSON and Python lists/dicts/numbers/strings/None.', '`load`/`dump` work on files; `loads`/`dumps` on strings. `None` becomes `null`. Dictionary keys become strings.', 'import json\ntext = json.dumps({"a": [1, 2], "ok": True, "x": None})\nprint(text, json.loads(text)["a"])', ['parse', 'api response', 'serialise']),
  py('py-sqlite3', 'sqlite3', 'sqlite3: connect and query', 'con = sqlite3.connect(path)\ncon.execute(sql, params).fetchall()', 'Use a SQLite database from Python.', '`execute` runs one statement; `fetchall()` returns a list of tuples, `fetchone()` one tuple. Use `?` placeholders and pass values separately: `execute("... WHERE id = ?", (5,))`. After INSERT/UPDATE/DELETE call `con.commit()`.', 'import sqlite3\ncon = sqlite3.connect(":memory:")\ncon.execute("CREATE TABLE t(id INTEGER, name TEXT)")\ncon.execute("INSERT INTO t VALUES (?, ?)", (1, "Ada"))\nprint(con.execute("SELECT * FROM t WHERE id = ?", (1,)).fetchall())', ['database', 'query', 'sql from python', 'parameters']),
  py('py-sqlite3-rows', 'sqlite3', 'sqlite3: rows as dictionaries', 'con.row_factory = sqlite3.Row', 'Makes each row behave like a dictionary, so you can read columns by name.', 'Set it before running queries. `dict(row)` gives a plain dictionary. `cursor.description` lists the column names.', 'import sqlite3\ncon = sqlite3.connect(":memory:")\ncon.row_factory = sqlite3.Row\ncon.execute("CREATE TABLE t(id INTEGER, name TEXT)")\ncon.execute("INSERT INTO t VALUES (1, \'Ada\')")\nrow = con.execute("SELECT * FROM t").fetchone()\nprint(row["name"], dict(row))', ['column names', 'dict']),
  py('py-logging', 'logging', 'logging module', 'logging.basicConfig(level=...)  /  logging.info(msg)  /  logging.warning(msg)', 'Record what a program does, without using print.', 'Levels from low to high: DEBUG, INFO, WARNING, ERROR, CRITICAL. In pipelines, log what was accepted, rejected and why.', 'import logging\nlogging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")\nlogging.info("loaded %d rows", 3)\nlogging.warning("rejected row %d", 7)', ['log', 'debug', 'audit trail']),
  // ------------------------------------------------------------------ SQL
  sql('sql-select', 'SELECT', 'SELECT ... FROM ... WHERE', 'SELECT columns FROM table WHERE condition', 'Choose columns and rows from a table.', '`*` means all columns. Combine conditions with `AND`, `OR`, `NOT`; test lists with `IN (...)`, ranges with `BETWEEN a AND b`, text patterns with `LIKE "A%"`. You can compute columns and name them with `AS`.', 'SELECT name, price * stock AS stock_value FROM products WHERE category IN (\'Tools\', \'Safety\') AND price < 50;', 'market', ['filter', 'columns', 'where']),
  sql('sql-order-limit', 'SELECT', 'ORDER BY, LIMIT, DISTINCT', 'ORDER BY column [ASC|DESC]  LIMIT n  SELECT DISTINCT column', 'Sort, keep the first few, remove duplicates.', 'Rows have no guaranteed order without `ORDER BY`. `DESC` is largest first. Sort by several columns with commas. `LIMIT 3` keeps the first three rows after sorting.', 'SELECT DISTINCT city FROM customers WHERE city IS NOT NULL ORDER BY city;\nSELECT name, price FROM products ORDER BY price DESC LIMIT 3;', 'market', ['top', 'highest', 'sort', 'unique']),
  sql('sql-null', 'NULL', 'NULL: missing values', 'column IS NULL  /  column IS NOT NULL  /  COALESCE(a, b)', 'NULL means “unknown”. It is not zero and not an empty string.', '`= NULL` and `<> NULL` never match anything; use `IS NULL` / `IS NOT NULL`. Any comparison with NULL is unknown, so `city <> \'Leeds\'` leaves out rows where city is NULL. `COALESCE(x, default)` replaces NULL. `COUNT(column)` skips NULLs; `COUNT(*)` counts rows.', 'SELECT name, COALESCE(city, \'unknown\') FROM customers WHERE city IS NULL OR city <> \'Leeds\';', 'market', ['missing', 'unknown', 'empty']),
  sql('sql-aggregates', 'aggregation', 'COUNT, SUM, AVG, MIN, MAX', 'SELECT COUNT(*), SUM(x), AVG(x), MIN(x), MAX(x) FROM table', 'Summarise many rows into one.', 'Aggregates ignore NULLs (except `COUNT(*)`). `ROUND(x, 2)` rounds. Aggregates cannot be used in `WHERE` (see HAVING).', 'SELECT COUNT(*), SUM(stock), ROUND(AVG(price), 2), MIN(price), MAX(price) FROM products;', 'market', ['total', 'average', 'how many']),
  sql('sql-group-by', 'aggregation', 'GROUP BY and HAVING', 'SELECT key, AGG(x) FROM t GROUP BY key HAVING AGG(x) > n', 'One result row per group; HAVING filters groups.', '`WHERE` filters rows BEFORE grouping; `HAVING` filters groups AFTER. Every selected column must be grouped or aggregated.', 'SELECT status, COUNT(*) AS n FROM orders GROUP BY status HAVING COUNT(*) > 5 ORDER BY n DESC;', 'market', ['per', 'each', 'by category', 'group']),
  sql('sql-join', 'joins', 'JOIN', 'FROM a JOIN b ON a.key = b.key', 'Combine rows of two tables that are related by a key.', 'A foreign key in one table holds the primary key of another. Always write the `ON` condition; forgetting it pairs every row with every row. Use table aliases (`FROM orders o JOIN customers c ...`) and join more tables by repeating `JOIN ... ON ...`.', 'SELECT c.name, o.id, o.status FROM orders o JOIN customers c ON c.id = o.customer_id ORDER BY o.id LIMIT 5;', 'market', ['relationship', 'foreign key', 'combine tables', 'inner join']),
  sql('sql-left-join', 'joins', 'LEFT JOIN', 'FROM a LEFT JOIN b ON a.key = b.key', 'Keep every row of the left table, even when nothing matches on the right.', 'Unmatched rows get NULLs for the right table’s columns, so `WHERE b.id IS NULL` finds rows with NO match. `COUNT(b.id)` counts only real matches, so groups with none give 0.', 'SELECT c.name, COUNT(o.id) AS orders FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id ORDER BY orders, c.name LIMIT 5;', 'market', ['no match', 'never', 'without', 'anti join']),
  sql('sql-case', 'expressions', 'CASE', 'CASE WHEN cond THEN x WHEN cond THEN y ELSE z END', 'An if/else inside a query.', 'Conditions are tested top to bottom; the first true one wins. Inside an aggregate it counts or sums conditionally: `SUM(CASE WHEN status = \'paid\' THEN 1 ELSE 0 END)`.', 'SELECT name, CASE WHEN price < 10 THEN \'cheap\' WHEN price < 50 THEN \'mid\' ELSE \'premium\' END AS band FROM products LIMIT 5;', 'market', ['if', 'bucket', 'band', 'category', 'label']),
  sql('sql-subquery', 'subqueries', 'Subqueries and CTEs', '(SELECT ...) in WHERE / FROM   ·   WITH name AS (SELECT ...) SELECT ...', 'A query used inside another query.', 'A subquery in `WHERE` can compare to one value (`> (SELECT AVG(price) FROM products)`) or a list (`IN (SELECT ...)`). A CTE (`WITH`) names a step so a complicated query reads top to bottom.', 'WITH per_customer AS (SELECT customer_id, COUNT(*) AS n FROM orders GROUP BY customer_id)\nSELECT AVG(n) FROM per_customer;', 'market', ['nested', 'with', 'step', 'temporary table']),
  sql('sql-window', 'window functions', 'Window functions', 'fn() OVER (PARTITION BY x ORDER BY y)', 'Calculate across related rows without collapsing them.', '`ROW_NUMBER()`, `RANK()` number rows within each partition; `SUM(x) OVER (ORDER BY d)` is a running total; `LAG(x)` reads the previous row. Filter on a window result by putting the query in a subquery or CTE.', 'SELECT name, category, price, RANK() OVER (PARTITION BY category ORDER BY price DESC) AS rk FROM products ORDER BY category, rk LIMIT 6;', 'market', ['rank', 'running total', 'previous row', 'row number', 'partition']),
  sql('sql-dates', 'expressions', 'Dates and text functions', 'strftime(format, date)  /  date(x, modifier)  /  LENGTH(x)  /  UPPER(x)  /  SUBSTR(x, start, n)  /  ROUND(x, n)', 'Work with dates stored as text `YYYY-MM-DD`, and with text.', '`strftime(\'%Y-%m\', ordered_on)` gives the month; `%w` weekday number; `julianday(a) - julianday(b)` is days between. `||` joins text.', 'SELECT strftime(\'%Y-%m\', ordered_on) AS month, COUNT(*) FROM orders GROUP BY month ORDER BY month LIMIT 3;', 'market', ['month', 'year', 'days between', 'text']),
  sql('sql-insert-update-delete', 'modifying data', 'INSERT, UPDATE, DELETE', 'INSERT INTO t (cols) VALUES (...)   ·   UPDATE t SET col = x WHERE ...   ·   DELETE FROM t WHERE ...', 'Add, change and remove rows.', '**Always** write a `WHERE` for UPDATE and DELETE, and test it with a SELECT first: without one, every row changes. Foreign keys stop you deleting a row that others still refer to. `INSERT INTO t SELECT ...` copies rows.', 'INSERT INTO customers (name, city, joined_on) VALUES (\'Test\', \'Ely\', \'2024-01-01\');\nUPDATE products SET price = price * 1.1 WHERE category = \'Tools\';\nDELETE FROM customers WHERE name = \'Test\';', 'market', ['add', 'change', 'remove', 'modify']),
  sql('sql-create-table', 'schema', 'CREATE TABLE and constraints', 'CREATE TABLE t (col TYPE [PRIMARY KEY] [NOT NULL] [UNIQUE] [CHECK (...)] [REFERENCES other(col)])', 'Define a table and the rules its data must obey.', 'A **primary key** identifies each row. A **foreign key** (`REFERENCES`) links to another table’s key. `NOT NULL`, `UNIQUE` and `CHECK (price >= 0)` make the database refuse bad data. Types: INTEGER, REAL, TEXT.', 'CREATE TABLE ships (\n  id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL UNIQUE,\n  crew INTEGER CHECK (crew >= 0)\n);\nINSERT INTO ships (name, crew) VALUES (\'Otter\', 12);\nSELECT * FROM ships;', 'blank', ['schema', 'primary key', 'foreign key', 'constraint', 'design']),
  sql('sql-index-plan', 'performance', 'CREATE INDEX and EXPLAIN QUERY PLAN', 'CREATE INDEX name ON table(column)  ·  EXPLAIN QUERY PLAN SELECT ...', 'Make lookups faster, and see how the database will run a query.', 'Without an index the database SCANs every row; with one it can SEARCH directly. Indexes cost space and slow writes, so add them for columns used often in WHERE/JOIN. `EXPLAIN QUERY PLAN` shows `SCAN` (slow) or `SEARCH ... USING INDEX` (fast).', 'CREATE INDEX idx_orders_customer ON orders(customer_id);\nEXPLAIN QUERY PLAN SELECT * FROM orders WHERE customer_id = 5;', 'market', ['fast', 'slow', 'performance', 'scan', 'search']),
  sql('sql-transactions', 'integrity', 'Transactions', 'BEGIN;  ...statements...  COMMIT;   (or ROLLBACK;)', 'Group changes so they all happen or none do.', 'Use a transaction for multi-step changes such as moving money between accounts: if step two fails, `ROLLBACK` undoes step one. Until `COMMIT`, other users do not see your changes.', 'BEGIN;\nUPDATE products SET stock = stock - 1 WHERE id = 1;\nROLLBACK;\nSELECT stock FROM products WHERE id = 1;', 'market', ['all or nothing', 'rollback', 'commit', 'atomic']),
  // ------------------------------------------------------------------ Phase 4: tools worth knowing (never taught; found by reading)
  py('py-itertools-groupby', 'itertools', 'itertools.groupby', 'itertools.groupby(iterable, key=None)', 'Splits a sequence into runs of consecutive items that share the same key.', 'Yields `(key, group)` pairs. It only groups **consecutive** items: `[1, 1, 2, 1]` gives three runs (1, 2, 1). To group everything with the same key, `sorted` first. Each `group` is a one-shot iterator: use it (`list(group)`) before moving to the next pair.', 'from itertools import groupby\nfor key, group in groupby([1, 1, 2, 1]):\n    print(key, len(list(group)))', ['runs', 'consecutive', 'group', 'repeat', 'adjacent']),
  py('py-bisect', 'bisect', 'bisect.bisect_left / bisect_right', 'bisect.bisect_left(sorted_list, x)   ·   bisect.bisect_right(sorted_list, x)', 'Binary search: where would x go in a sorted list?', '`bisect_left` gives the leftmost insertion point (everything before it is `< x`); `bisect_right` the rightmost (everything before it is `<= x`). The list must already be sorted. Takes about log₂(n) steps.', 'from bisect import bisect_left, bisect_right\na = [1, 3, 3, 5]\nprint(bisect_left(a, 3), bisect_right(a, 3), bisect_left(a, 4))', ['binary search', 'sorted', 'insertion point', 'find position', 'halving']),
  py('py-heapq', 'heapq', 'heapq.nlargest / nsmallest', 'heapq.nlargest(n, iterable, key=None)   ·   heapq.nsmallest(n, iterable, key=None)', 'The n biggest (or smallest) items, without sorting everything.', 'Returns a new list, biggest first for `nlargest`. `key` works like in `sorted`. For ties the earlier item comes first. If `n` is larger than the data you just get all of it.', 'import heapq\nprint(heapq.nlargest(2, [5, 1, 9, 3]))\nprint(heapq.nsmallest(2, [("b", 2), ("a", 2), ("c", 1)], key=lambda p: p[1]))', ['top n', 'largest', 'smallest', 'leaderboard', 'best']),
  py('py-re', 're', 're: regular expressions', 're.match(pattern, text)   ·   re.search(...)   ·   re.sub(pattern, replacement, text)   ·   re.findall(...)', 'Describe the shape of text with a pattern and pull pieces out of it.', '`match` tests the start of the text (use `^...$` for the whole text) and returns a match object or `None`; `m.group(1)` is the first `( )` capture. `\\d` a digit, `\\w` a word character, `+` one or more, `?` optional, `.+?` a shortest chunk, `[^a-z]` anything except a–z. `re.sub(r"[^a-z0-9]+", "-", s)` replaces every run. Use raw strings (`r"..."`) so backslashes survive.', 'import re\nm = re.match(r"^(\\d{4})-(\\d{2})$", "2024-03")\nprint(m.group(1), m.group(2))\nprint(re.sub(r"\\s+", " ", "a   b    c"))', ['regex', 'pattern', 'match', 'extract', 'replace runs']),
  py('py-datetime-strptime', 'datetime', 'datetime.strptime', 'datetime.strptime(text, format)', 'Read a date or time from text, and reject impossible ones.', 'Raises `ValueError` when the text does not fit the format or is not a real date (`2024-02-30`). Codes: `%Y` year, `%m` month, `%d` day, `%H` hour, `%M` minute, `%S` second. Subtracting two datetimes gives a `timedelta` (`.days`, `.total_seconds()`).', 'from datetime import datetime\nprint(datetime.strptime("2024-03-05 14:22:07", "%Y-%m-%d %H:%M:%S"))\ntry:\n    datetime.strptime("2024-02-30", "%Y-%m-%d")\nexcept ValueError as e:\n    print("invalid:", e)', ['parse date', 'valid date', 'timestamp', 'time difference']),
];

export const reference: ReferenceEntry[] = [...core, ...webReference, ...proReference];

const byId = new Map(reference.map((e) => [e.id, e]));
export const getReference = (id: string): ReferenceEntry | undefined => byId.get(id);

/** Simple, predictable search: every word must appear in the title, group, keywords, or summary. */
export function searchReference(query: string, language?: ReferenceEntry['language']): ReferenceEntry[] {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean);
  return reference.filter((e) => {
    if (language && e.language !== language) return false;
    if (!words.length) return true;
    const hay = `${e.title} ${e.group} ${e.signature} ${e.keywords.join(' ')} ${e.summary}`.toLowerCase();
    return words.every((w) => hay.includes(w));
  });
}
