import { chromium } from 'playwright-core';
import { spawn } from 'node:child_process';
import { readdirSync } from 'node:fs';
const root = '/opt/pw-browsers'; const dir = readdirSync(root).find((d) => d.startsWith('chromium-'));
const PORT = 4433;
const srv = spawn('npx', ['vite', 'preview', '--port', String(PORT), '--strictPort'], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 2500));
const b = await chromium.launch({ executablePath: `${root}/${dir}/chrome-linux/chrome`, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const errs = []; p.on('pageerror', (e) => errs.push(String(e)));
await p.addInitScript(() => { try { localStorage.setItem('codequest.e2e', '1'); } catch {} });
await p.goto(`http://localhost:${PORT}/`);
await p.getByTestId('name-input').fill('Ada'); await p.getByTestId('begin').click();
await p.locator('[data-testid=play][data-ready="1"]').waitFor({ timeout: 60000 });
if (await p.getByTestId('welcome-start').count()) await p.getByTestId('welcome-start').click();
await p.evaluate(() => { window.__cq3d.stage.timeScale = 4; window.__cq3d.travel('garage'); });
await p.waitForTimeout(800);
await p.evaluate(() => window.__cq3d.teleport(0, 3, 0));
await p.keyboard.press('e').catch(() => {});
await p.evaluate(() => window.__cq3d.drive());
await p.getByTestId('drive-hud').waitFor();
const pos = () => p.evaluate(() => ({ ...window.__cq3d.state(), hud: window.__cq3dHud && { kmh: window.__cq3dHud.kmh, rev: window.__cq3dHud.reversing, phase: window.__cq3dHud.phase } }));
console.log('start', JSON.stringify(await pos()));
await p.screenshot({ path: '/tmp/claude-0/shots/dr-0.png' });
await p.keyboard.down('s');
for (let i = 1; i <= 6; i++) { await p.waitForTimeout(2500); const s = await pos(); console.log('rev', i, s.x.toFixed(1), s.z.toFixed(1), JSON.stringify(s.hud)); if (i === 2 || i === 5) await p.screenshot({ path: `/tmp/claude-0/shots/dr-${i}.png` }); }
await p.keyboard.down('a'); await p.waitForTimeout(2500); await p.screenshot({ path: '/tmp/claude-0/shots/dr-steer.png' }); console.log('steer', JSON.stringify(await pos()));
await p.keyboard.up('a'); await p.keyboard.up('s');
console.log('errors', errs.join('|') || 'none');
await b.close(); srv.kill();
