/**
 * TEST-ONLY DATA (never imported by the app): reference solutions and plausible wrong attempts for the statistics lessons.
 * No imports (the e2e runner loads it under plain Node). Every `valid` must pass and every `wrong` must fail.
 */
export const solutionsStats: Record<string, { valid: string[]; wrong: string[] }> = {
  'st-01-mean': {
    valid: ['def mean(values):\n    if not values:\n        return None\n    return round(sum(values) / len(values), 2)', 'def mean(values):\n    total = 0\n    for v in values:\n        total += v\n    if len(values) == 0:\n        return None\n    return round(total / len(values), 2)'],
    wrong: ['def mean(values):\n    return round(sum(values) / len(values), 2)', 'def mean(values):\n    if not values:\n        return None\n    return sum(values) / len(values)', 'def mean(values):\n    if not values:\n        return 0\n    return round(sum(values) / len(values), 2)', 'def mean(values):\n    if not values:\n        return None\n    return round(sum(values) // len(values), 2)', 'def mean(values):\n    if not values:\n        return None\n    return round(sum(values) / (len(values) - 1), 2)'],
  },
  'st-01-median': {
    valid: ['def typical_time(minutes):\n    s = sorted(minutes)\n    n = len(s)\n    if n == 0:\n        return None\n    if n % 2:\n        return s[n // 2]\n    return (s[n // 2 - 1] + s[n // 2]) / 2', 'import statistics\ndef typical_time(minutes):\n    return statistics.median(minutes) if minutes else None'],
    wrong: ['def typical_time(minutes):\n    s = sorted(minutes)\n    return s[len(s) // 2] if s else None', 'def typical_time(minutes):\n    minutes.sort()\n    n = len(minutes)\n    if n == 0:\n        return None\n    return minutes[n // 2] if n % 2 else (minutes[n // 2 - 1] + minutes[n // 2]) / 2', 'def typical_time(minutes):\n    n = len(minutes)\n    if n == 0:\n        return None\n    return minutes[n // 2] if n % 2 else (minutes[n // 2 - 1] + minutes[n // 2]) / 2', 'def typical_time(minutes):\n    return sum(minutes) / len(minutes) if minutes else None', 'def typical_time(minutes):\n    s = sorted(minutes)\n    n = len(s)\n    if n == 0:\n        return None\n    return s[n // 2] if n % 2 else s[n // 2 - 1]'],
  },
  'st-01-median-b': {
    valid: ['def typical_price(prices):\n    s = sorted(p for p in prices if p is not None)\n    n = len(s)\n    if n == 0:\n        return None\n    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2'],
    wrong: ['def typical_price(prices):\n    s = sorted(p or 0 for p in prices)\n    n = len(s)\n    if n == 0:\n        return None\n    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2', 'def typical_price(prices):\n    s = [p for p in prices if p is not None]\n    n = len(s)\n    if n == 0:\n        return None\n    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2', 'def typical_price(prices):\n    s = sorted(p for p in prices if p is not None)\n    return s[len(s) // 2]', 'def typical_price(prices):\n    s = [p for p in prices if p is not None]\n    return sum(s) / len(s) if s else None'],
  },
  'st-01-modes': {
    valid: ['def most_common(codes):\n    counts = {}\n    for c in codes:\n        counts[c] = counts.get(c, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return sorted(c for c in counts if counts[c] == top)', 'from collections import Counter\ndef most_common(codes):\n    c = Counter(codes)\n    if not c:\n        return []\n    top = max(c.values())\n    return sorted(k for k, v in c.items() if v == top)'],
    wrong: ['from collections import Counter\ndef most_common(codes):\n    c = Counter(codes).most_common(1)\n    return [c[0][0]] if c else []', 'def most_common(codes):\n    counts = {}\n    for c in codes:\n        counts[c] = counts.get(c, 0) + 1\n    return max(counts, key=counts.get) if counts else []', 'def most_common(codes):\n    counts = {}\n    for c in codes:\n        counts[c] = counts.get(c, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return [c for c in counts if counts[c] == top]', 'def most_common(codes):\n    return sorted(set(codes))'],
  },
  'st-01-modes-b': {
    valid: ['def busiest_hours(times):\n    counts = {}\n    for t in times:\n        h = t.split(":")[0]\n        counts[h] = counts.get(h, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return sorted(h for h in counts if counts[h] == top)'],
    wrong: ['def busiest_hours(times):\n    counts = {}\n    for t in times:\n        counts[t] = counts.get(t, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return sorted(h for h in counts if counts[h] == top)', 'def busiest_hours(times):\n    counts = {}\n    for t in times:\n        h = int(t.split(":")[0])\n        counts[h] = counts.get(h, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return sorted(h for h in counts if counts[h] == top)', 'def busiest_hours(times):\n    counts = {}\n    for t in times:\n        h = t.split(":")[0]\n        counts[h] = counts.get(h, 0) + 1\n    return [max(counts, key=counts.get)] if counts else []', 'def busiest_hours(times):\n    counts = {}\n    for t in times:\n        h = t.split(":")[1]\n        counts[h] = counts.get(h, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return sorted(h for h in counts if counts[h] == top)'],
  },

  'st-02-range': {
    valid: ['def swing(temperatures):\n    if not temperatures:\n        return None\n    return max(temperatures) - min(temperatures)'],
    wrong: ['def swing(temperatures):\n    return max(temperatures) - min(temperatures)', 'def swing(temperatures):\n    if not temperatures:\n        return None\n    return max(temperatures)', 'def swing(temperatures):\n    if not temperatures:\n        return 0\n    return max(temperatures) - min(temperatures)', 'def swing(temperatures):\n    if not temperatures:\n        return None\n    return temperatures[-1] - temperatures[0]'],
  },
  'st-02-std': {
    valid: ['import math\ndef fill_std(volumes):\n    n = len(volumes)\n    if n == 0:\n        return None\n    m = sum(volumes) / n\n    return round(math.sqrt(sum((v - m) ** 2 for v in volumes) / n), 3)', 'import statistics\ndef fill_std(volumes):\n    return round(statistics.pstdev(volumes), 3) if volumes else None'],
    wrong: ['import math\ndef fill_std(volumes):\n    n = len(volumes)\n    if n < 2:\n        return None\n    m = sum(volumes) / n\n    return round(math.sqrt(sum((v - m) ** 2 for v in volumes) / (n - 1)), 3)', 'import math\ndef fill_std(volumes):\n    n = len(volumes)\n    if n == 0:\n        return None\n    m = sum(volumes) / n\n    return round(sum((v - m) ** 2 for v in volumes) / n, 3)', 'import math\ndef fill_std(volumes):\n    n = len(volumes)\n    if n == 0:\n        return None\n    m = sum(volumes) / n\n    return round(math.sqrt(sum(abs(v - m) for v in volumes) / n), 3)', 'import math\ndef fill_std(volumes):\n    n = len(volumes)\n    if n == 0:\n        return None\n    m = sum(volumes) / n\n    return math.sqrt(sum((v - m) ** 2 for v in volumes) / n)'],
  },
  'st-02-std-b': {
    valid: ['import math\ndef volatility(returns):\n    n = len(returns)\n    if n < 2:\n        return None\n    m = sum(returns) / n\n    return round(math.sqrt(sum((r - m) ** 2 for r in returns) / (n - 1)), 3)', 'import statistics\ndef volatility(returns):\n    return round(statistics.stdev(returns), 3) if len(returns) > 1 else None'],
    wrong: ['import math\ndef volatility(returns):\n    n = len(returns)\n    if n == 0:\n        return None\n    m = sum(returns) / n\n    return round(math.sqrt(sum((r - m) ** 2 for r in returns) / n), 3)', 'import math\ndef volatility(returns):\n    n = len(returns)\n    if n < 2:\n        return None\n    m = sum(returns) / n\n    return round(math.sqrt(sum((r - m) ** 2 for r in returns) / (n - 1)), 2)', 'import math\ndef volatility(returns):\n    n = len(returns)\n    if n < 2:\n        return None\n    m = sum(returns) / n\n    return math.sqrt(sum((r - m) ** 2 for r in returns) / (n - 1))', 'def volatility(returns):\n    return None if len(returns) < 2 else round(max(returns) - min(returns), 3)'],
  },
  'st-02-outliers': {
    valid: ['def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    s = sorted(amounts)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in s if v < lo or v > hi]'],
    wrong: ['def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    s = sorted(amounts)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in s if v <= lo or v >= hi]', 'def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    s = sorted(amounts)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in s if v < lo or v > hi]', 'def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    s = sorted(amounts)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in amounts if v < lo or v > hi]', 'def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    m = sum(amounts) / len(amounts)\n    sd = (sum((v - m) ** 2 for v in amounts) / len(amounts)) ** 0.5\n    return sorted(v for v in amounts if abs(v - m) > 2 * sd)', 'def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    s = sorted(amounts)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in s if v < lo or v > hi][:1]'],
  },
  'st-02-outliers-b': {
    valid: ['def odd_positions(readings):\n    if len(readings) < 4:\n        return []\n    s = sorted(readings)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [i for i, v in enumerate(readings) if v < lo or v > hi]'],
    wrong: ['def odd_positions(readings):\n    if len(readings) < 4:\n        return []\n    s = sorted(readings)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in readings if v < lo or v > hi]', 'def odd_positions(readings):\n    if len(readings) < 4:\n        return []\n    readings.sort()\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(readings)\n    q1 = med(readings[:n // 2])\n    q3 = med(readings[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [i for i, v in enumerate(readings) if v < lo or v > hi]', 'def odd_positions(readings):\n    if len(readings) < 4:\n        return []\n    s = sorted(readings)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [i for i, v in enumerate(readings) if v < lo or v > hi]', 'def odd_positions(readings):\n    if len(readings) < 4:\n        return []\n    s = sorted(readings)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [i for i, v in enumerate(readings) if v <= lo or v >= hi]'],
  },
};
