/**
 * TEST-ONLY DATA (never imported by the app): reference solutions and plausible wrong attempts for the statistics lessons.
 * No imports (the e2e runner loads it under plain Node). Every `valid` must pass and every `wrong` must fail.
 */
export const solutionsStats: Record<string, { valid: string[]; wrong: string[] }> = {
  'st-01-mean': {
    valid: ['def mean(values):\n    if not values:\n        return None\n    return round(sum(values) / len(values), 2)', 'def mean(values):\n    total = 0\n    for v in values:\n        total += v\n    if len(values) == 0:\n        return None\n    return round(total / len(values), 2)'],
    wrong: ['def mean(values):\n    return round(sum(values) / len(values), 2)', 'def mean(values):\n    if not values:\n        return None\n    return sum(values) / len(values)', 'def mean(values):\n    if not values:\n        return 0\n    return round(sum(values) / len(values), 2)', 'def mean(values):\n    if not values:\n        return None\n    return round(sum(values) // len(values), 2)', 'def mean(values):\n    if not values:\n        return None\n    return round(sum(values) / (len(values) - 1), 2)'],
  },
  'st-01-median': {
    valid: ['def typical_time(minutes):\n    s = sorted(minutes)\n    n = len(s)\n    if n == 0:\n        return None\n    if n % 2:\n        return s[n // 2]\n    return (s[n // 2 - 1] + s[n // 2]) / 2', 'import statistics\ndef typical_time(minutes):\n    return statistics.median(minutes) if minutes else None'],
    wrong: ['def typical_time(minutes):\n    s = sorted(minutes)\n    return s[len(s) // 2] if s else None', 'def typical_time(minutes):\n    minutes.sort()\n    n = len(minutes)\n    if n == 0:\n        return None\n    return minutes[n // 2] if n % 2 else (minutes[n // 2 - 1] + minutes[n // 2]) / 2', 'def typical_time(minutes):\n    n = len(minutes)\n    if n == 0:\n        return None\n    return minutes[n // 2] if n % 2 else (minutes[n // 2 - 1] + minutes[n // 2]) / 2', 'def typical_time(minutes):\n    return sum(minutes) / len(minutes) if minutes else None', 'def typical_time(minutes):\n    s = sorted(minutes)\n    n = len(s)\n    if n == 0:\n        return None\n    return s[n // 2] if n % 2 else s[n // 2 - 1]'],
  },
  'st-01-median-b': {
    valid: ['def typical_price(prices):\n    s = sorted(p for p in prices if p is not None)\n    n = len(s)\n    if n == 0:\n        return None\n    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2'],
    wrong: ['def typical_price(prices):\n    s = sorted(p or 0 for p in prices)\n    n = len(s)\n    if n == 0:\n        return None\n    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2', 'def typical_price(prices):\n    s = [p for p in prices if p is not None]\n    n = len(s)\n    if n == 0:\n        return None\n    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2', 'def typical_price(prices):\n    s = sorted(p for p in prices if p is not None)\n    return s[len(s) // 2]', 'def typical_price(prices):\n    s = [p for p in prices if p is not None]\n    return sum(s) / len(s) if s else None'],
  },
  'st-01-modes': {
    valid: ['def most_common(codes):\n    counts = {}\n    for c in codes:\n        counts[c] = counts.get(c, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return sorted(c for c in counts if counts[c] == top)', 'from collections import Counter\ndef most_common(codes):\n    c = Counter(codes)\n    if not c:\n        return []\n    top = max(c.values())\n    return sorted(k for k, v in c.items() if v == top)'],
    wrong: ['from collections import Counter\ndef most_common(codes):\n    c = Counter(codes).most_common(1)\n    return [c[0][0]] if c else []', 'def most_common(codes):\n    counts = {}\n    for c in codes:\n        counts[c] = counts.get(c, 0) + 1\n    return max(counts, key=counts.get) if counts else []', 'def most_common(codes):\n    counts = {}\n    for c in codes:\n        counts[c] = counts.get(c, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return [c for c in counts if counts[c] == top]', 'def most_common(codes):\n    return sorted(set(codes))'],
  },
  'st-01-modes-b': {
    valid: ['def busiest_hours(times):\n    counts = {}\n    for t in times:\n        h = t.split(":")[0]\n        counts[h] = counts.get(h, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return sorted(h for h in counts if counts[h] == top)'],
    wrong: ['def busiest_hours(times):\n    counts = {}\n    for t in times:\n        counts[t] = counts.get(t, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return sorted(h for h in counts if counts[h] == top)', 'def busiest_hours(times):\n    counts = {}\n    for t in times:\n        h = int(t.split(":")[0])\n        counts[h] = counts.get(h, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return sorted(h for h in counts if counts[h] == top)', 'def busiest_hours(times):\n    counts = {}\n    for t in times:\n        h = t.split(":")[0]\n        counts[h] = counts.get(h, 0) + 1\n    return [max(counts, key=counts.get)] if counts else []', 'def busiest_hours(times):\n    counts = {}\n    for t in times:\n        h = t.split(":")[1]\n        counts[h] = counts.get(h, 0) + 1\n    if not counts:\n        return []\n    top = max(counts.values())\n    return sorted(h for h in counts if counts[h] == top)'],
  },

  'st-02-range': {
    valid: ['def swing(temperatures):\n    if not temperatures:\n        return None\n    return max(temperatures) - min(temperatures)'],
    wrong: ['def swing(temperatures):\n    return max(temperatures) - min(temperatures)', 'def swing(temperatures):\n    if not temperatures:\n        return None\n    return max(temperatures)', 'def swing(temperatures):\n    if not temperatures:\n        return 0\n    return max(temperatures) - min(temperatures)', 'def swing(temperatures):\n    if not temperatures:\n        return None\n    return temperatures[-1] - temperatures[0]'],
  },
  'st-02-std': {
    valid: ['import math\ndef fill_std(volumes):\n    n = len(volumes)\n    if n == 0:\n        return None\n    m = sum(volumes) / n\n    return round(math.sqrt(sum((v - m) ** 2 for v in volumes) / n), 3)', 'import statistics\ndef fill_std(volumes):\n    return round(statistics.pstdev(volumes), 3) if volumes else None'],
    wrong: ['import math\ndef fill_std(volumes):\n    n = len(volumes)\n    if n < 2:\n        return None\n    m = sum(volumes) / n\n    return round(math.sqrt(sum((v - m) ** 2 for v in volumes) / (n - 1)), 3)', 'import math\ndef fill_std(volumes):\n    n = len(volumes)\n    if n == 0:\n        return None\n    m = sum(volumes) / n\n    return round(sum((v - m) ** 2 for v in volumes) / n, 3)', 'import math\ndef fill_std(volumes):\n    n = len(volumes)\n    if n == 0:\n        return None\n    m = sum(volumes) / n\n    return round(math.sqrt(sum(abs(v - m) for v in volumes) / n), 3)', 'import math\ndef fill_std(volumes):\n    n = len(volumes)\n    if n == 0:\n        return None\n    m = sum(volumes) / n\n    return math.sqrt(sum((v - m) ** 2 for v in volumes) / n)'],
  },
  'st-02-std-b': {
    valid: ['import math\ndef volatility(returns):\n    n = len(returns)\n    if n < 2:\n        return None\n    m = sum(returns) / n\n    return round(math.sqrt(sum((r - m) ** 2 for r in returns) / (n - 1)), 3)', 'import statistics\ndef volatility(returns):\n    return round(statistics.stdev(returns), 3) if len(returns) > 1 else None'],
    wrong: ['import math\ndef volatility(returns):\n    n = len(returns)\n    if n == 0:\n        return None\n    m = sum(returns) / n\n    return round(math.sqrt(sum((r - m) ** 2 for r in returns) / n), 3)', 'import math\ndef volatility(returns):\n    n = len(returns)\n    if n < 2:\n        return None\n    m = sum(returns) / n\n    return round(math.sqrt(sum((r - m) ** 2 for r in returns) / (n - 1)), 2)', 'import math\ndef volatility(returns):\n    n = len(returns)\n    if n < 2:\n        return None\n    m = sum(returns) / n\n    return math.sqrt(sum((r - m) ** 2 for r in returns) / (n - 1))', 'def volatility(returns):\n    return None if len(returns) < 2 else round(max(returns) - min(returns), 3)'],
  },
  'st-02-outliers': {
    valid: ['def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    s = sorted(amounts)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in s if v < lo or v > hi]'],
    wrong: ['def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    s = sorted(amounts)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in s if v <= lo or v >= hi]', 'def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    s = sorted(amounts)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in s if v < lo or v > hi]', 'def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    s = sorted(amounts)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in amounts if v < lo or v > hi]', 'def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    m = sum(amounts) / len(amounts)\n    sd = (sum((v - m) ** 2 for v in amounts) / len(amounts)) ** 0.5\n    return sorted(v for v in amounts if abs(v - m) > 2 * sd)', 'def unusual(amounts):\n    if len(amounts) < 4:\n        return []\n    s = sorted(amounts)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in s if v < lo or v > hi][:1]'],
  },
  'st-02-outliers-b': {
    valid: ['def odd_positions(readings):\n    if len(readings) < 4:\n        return []\n    s = sorted(readings)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [i for i, v in enumerate(readings) if v < lo or v > hi]'],
    wrong: ['def odd_positions(readings):\n    if len(readings) < 4:\n        return []\n    s = sorted(readings)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [v for v in readings if v < lo or v > hi]', 'def odd_positions(readings):\n    if len(readings) < 4:\n        return []\n    readings.sort()\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(readings)\n    q1 = med(readings[:n // 2])\n    q3 = med(readings[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [i for i, v in enumerate(readings) if v < lo or v > hi]', 'def odd_positions(readings):\n    if len(readings) < 4:\n        return []\n    s = sorted(readings)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [i for i, v in enumerate(readings) if v < lo or v > hi]', 'def odd_positions(readings):\n    if len(readings) < 4:\n        return []\n    s = sorted(readings)\n    def med(x):\n        n = len(x)\n        return x[n // 2] if n % 2 else (x[n // 2 - 1] + x[n // 2]) / 2\n    n = len(s)\n    q1 = med(s[:n // 2])\n    q3 = med(s[n // 2 + n % 2:])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n    return [i for i, v in enumerate(readings) if v <= lo or v >= hi]'],
  },

  'st-03-frequency': {
    valid: ['def frequencies(values):\n    counts = {}\n    for v in values:\n        counts[v] = counts.get(v, 0) + 1\n    return counts', 'from collections import Counter\ndef frequencies(values):\n    return dict(Counter(values))'],
    wrong: ['def frequencies(values):\n    return {v: 1 for v in values}', 'def frequencies(values):\n    return set(values)', 'def frequencies(values):\n    counts = {}\n    for v in values:\n        counts[v] = counts.get(v, 0) + 1\n    return list(counts.values())', 'def frequencies(values):\n    return {v: values.count(v) + 1 for v in values}'],
  },
  'st-03-bins': {
    valid: ['def score_histogram(scores, width):\n    if not scores:\n        return []\n    counts = [0] * (int(max(scores) // width) + 1)\n    for s in scores:\n        counts[int(s // width)] += 1\n    return counts'],
    wrong: ['def score_histogram(scores, width):\n    if not scores:\n        return []\n    counts = [0] * (int(max(scores) // width))\n    for s in scores:\n        if s // width < len(counts):\n            counts[int(s // width)] += 1\n    return counts', 'def score_histogram(scores, width):\n    counts = {}\n    for s in scores:\n        counts[int(s // width)] = counts.get(int(s // width), 0) + 1\n    return [counts[k] for k in sorted(counts)]', 'def score_histogram(scores, width):\n    if not scores:\n        return []\n    counts = [0] * (int(max(scores) // width) + 1)\n    for s in scores:\n        counts[int(round(s / width))] += 1 if round(s / width) < len(counts) else 0\n    return counts', 'def score_histogram(scores, width):\n    if not scores:\n        return []\n    counts = [0] * (int(max(scores) / width) + 2)\n    for s in scores:\n        counts[int(s // width)] += 1\n    return counts'],
  },
  'st-03-bins-b': {
    valid: ['def latency_buckets(times, size):\n    if not times:\n        return []\n    counts = [0] * (int(max(times) // size) + 1)\n    for t in times:\n        counts[int(t // size)] += 1\n    return counts'],
    wrong: ['def latency_buckets(times, size):\n    counts = {}\n    for t in times:\n        counts[int(t // size)] = counts.get(int(t // size), 0) + 1\n    return [counts[k] for k in sorted(counts)]', 'def latency_buckets(times, size):\n    if not times:\n        return []\n    counts = [0] * (int(max(times) // size) + 1)\n    for t in times:\n        counts[int((t - 1) // size)] += 1\n    return counts', 'def latency_buckets(times, size):\n    if not times:\n        return []\n    counts = [0] * (int(max(times) // size))\n    for t in times:\n        counts[min(int(t // size), len(counts) - 1)] += 1\n    return counts'],
  },
  'st-03-percentile': {
    valid: ['import math\ndef cutoff(scores, p):\n    if not scores:\n        return None\n    s = sorted(scores)\n    rank = max(1, math.ceil(p / 100 * len(s)))\n    return s[rank - 1]'],
    wrong: ['def cutoff(scores, p):\n    if not scores:\n        return None\n    s = sorted(scores)\n    return s[int(p / 100 * len(s)) - 1]', 'import math\ndef cutoff(scores, p):\n    if not scores:\n        return None\n    s = sorted(scores)\n    rank = math.ceil(p / 100 * len(s))\n    return s[rank - 1]', 'import math\ndef cutoff(scores, p):\n    if not scores:\n        return None\n    rank = max(1, math.ceil(p / 100 * len(scores)))\n    return scores[rank - 1]', 'import math\ndef cutoff(scores, p):\n    if not scores:\n        return None\n    scores.sort()\n    rank = max(1, math.ceil(p / 100 * len(scores)))\n    return scores[rank - 1]', 'def cutoff(scores, p):\n    if not scores:\n        return None\n    s = sorted(scores)\n    return s[min(len(s) - 1, int(p / 100 * len(s)))]'],
  },
  'st-03-percentile-b': {
    valid: ['import math\ndef latency_at(times, p):\n    if not times:\n        return None\n    s = sorted(times)\n    return s[max(1, math.ceil(p / 100 * len(s))) - 1]'],
    wrong: ['def latency_at(times, p):\n    if not times:\n        return None\n    s = sorted(times)\n    return s[int(p / 100 * len(s)) - 1]', 'import math\ndef latency_at(times, p):\n    if not times:\n        return None\n    return sorted(times)[math.floor(p / 100 * len(times))]', 'import math\ndef latency_at(times, p):\n    if not times:\n        return None\n    return sorted(times)[math.ceil(p / 100 * len(times)) - 1]', 'def latency_at(times, p):\n    if not times:\n        return None\n    return max(times) if p >= 50 else min(times)'],
  },

  'st-04-axis': {
    valid: ['import math\ndef bar_axis(values):\n    top = max(values) if values else 0\n    return (0, max(10, math.ceil(top / 10) * 10))'],
    wrong: ['def bar_axis(values):\n    return (min(values), max(values))', 'import math\ndef bar_axis(values):\n    top = max(values) if values else 0\n    return (0, math.ceil(top / 10) * 10)', 'def bar_axis(values):\n    top = max(values) if values else 0\n    return (0, (int(top) // 10 + 1) * 10)', 'import math\ndef bar_axis(values):\n    top = max(values) if values else 0\n    return (0, max(10, math.floor(top / 10) * 10))', 'import math\ndef bar_axis(values):\n    top = max(values) if values else 0\n    return (5, max(10, math.ceil(top / 10) * 10))'],
  },
  'st-04-bar-problems': {
    valid: ['def review_chart(spec):\n    found = []\n    if not spec.get("title", "").strip():\n        found.append("no-title")\n    if spec["type"] != "pie" and not spec.get("y_label", "").strip():\n        found.append("no-units")\n    if spec["type"] == "bar" and spec.get("y_min", 0) != 0:\n        found.append("truncated-axis")\n    if spec["type"] == "pie" and spec.get("slices", 0) > 5:\n        found.append("too-many-slices")\n    return sorted(found)'],
    wrong: ['def review_chart(spec):\n    found = []\n    if not spec.get("title", "").strip():\n        found.append("no-title")\n    if not spec.get("y_label", "").strip():\n        found.append("no-units")\n    if spec["type"] == "bar" and spec.get("y_min", 0) != 0:\n        found.append("truncated-axis")\n    if spec["type"] == "pie" and spec.get("slices", 0) > 5:\n        found.append("too-many-slices")\n    return sorted(found)', 'def review_chart(spec):\n    found = []\n    if not spec.get("title", "").strip():\n        found.append("no-title")\n    if spec["type"] != "pie" and not spec.get("y_label", "").strip():\n        found.append("no-units")\n    if spec.get("y_min", 0) != 0:\n        found.append("truncated-axis")\n    if spec["type"] == "pie" and spec.get("slices", 0) > 5:\n        found.append("too-many-slices")\n    return sorted(found)', 'def review_chart(spec):\n    found = []\n    if not spec.get("title", "").strip():\n        found.append("no-title")\n    if spec["type"] != "pie" and not spec.get("y_label", "").strip():\n        found.append("no-units")\n    if spec["type"] == "bar" and spec.get("y_min", 0) != 0:\n        found.append("truncated-axis")\n    if spec["type"] == "pie" and spec.get("slices", 0) >= 5:\n        found.append("too-many-slices")\n    return sorted(found)', 'def review_chart(spec):\n    found = []\n    if not spec.get("title"):\n        found.append("no-title")\n    if spec["type"] != "pie" and not spec.get("y_label"):\n        found.append("no-units")\n    if spec["type"] == "bar" and spec.get("y_min", 0) != 0:\n        found.append("truncated-axis")\n    if spec["type"] == "pie" and spec.get("slices", 0) > 5:\n        found.append("too-many-slices")\n    return sorted(found)', 'def review_chart(spec):\n    found = []\n    if not spec["title"].strip():\n        found.append("no-title")\n    if spec["type"] != "pie" and not spec["y_label"].strip():\n        found.append("no-units")\n    if spec["type"] == "bar" and spec["y_min"] != 0:\n        found.append("truncated-axis")\n    if spec["type"] == "pie" and spec["slices"] > 5:\n        found.append("too-many-slices")\n    return sorted(found)', 'def review_chart(spec):\n    found = []\n    if not spec.get("title", "").strip():\n        found.append("no-title")\n    if spec["type"] != "pie" and not spec.get("y_label", "").strip():\n        found.append("no-units")\n    if spec["type"] == "bar" and spec.get("y_min", 0) != 0:\n        found.append("truncated-axis")\n    if spec["type"] == "pie" and spec.get("slices", 0) > 5:\n        found.append("too-many-slices")\n    return found[::-1]'],
  },
  'st-04-line-problems': {
    valid: ['def gate(spec):\n    found = []\n    if not spec.get("title", "").strip():\n        found.append("no-title")\n    if not spec.get("y_label", "").strip():\n        found.append("no-units")\n    if not spec.get("x_label", "").strip():\n        found.append("no-x-label")\n    pts = spec.get("points", 0)\n    if pts < 3:\n        found.append("too-few-points")\n    if spec.get("trendline") and pts < 10:\n        found.append("trendline-on-few-points")\n    if spec.get("dual_axis"):\n        found.append("dual-axis-misleads")\n    return sorted(found)'],
    wrong: ['def gate(spec):\n    found = []\n    if not spec.get("title", "").strip():\n        found.append("no-title")\n    if not spec.get("y_label", "").strip():\n        found.append("no-units")\n    if not spec.get("x_label", "").strip():\n        found.append("no-x-label")\n    pts = spec.get("points", 0)\n    if pts < 3:\n        found.append("too-few-points")\n    if spec.get("trendline") and pts <= 10:\n        found.append("trendline-on-few-points")\n    if spec.get("dual_axis"):\n        found.append("dual-axis-misleads")\n    return sorted(found)', 'def gate(spec):\n    found = []\n    if not spec.get("title", "").strip():\n        found.append("no-title")\n    if not spec.get("y_label", "").strip():\n        found.append("no-units")\n    if not spec.get("x_label", "").strip():\n        found.append("no-x-label")\n    pts = spec.get("points", 0)\n    if pts <= 3:\n        found.append("too-few-points")\n    if spec.get("trendline") and pts < 10:\n        found.append("trendline-on-few-points")\n    if spec.get("dual_axis"):\n        found.append("dual-axis-misleads")\n    return sorted(found)', 'def gate(spec):\n    found = []\n    if not spec.get("title", "").strip():\n        found.append("no-title")\n    if not spec.get("y_label", "").strip():\n        found.append("no-units")\n    pts = spec.get("points", 0)\n    if pts < 3:\n        found.append("too-few-points")\n    if spec.get("trendline") and pts < 10:\n        found.append("trendline-on-few-points")\n    if spec.get("dual_axis"):\n        found.append("dual-axis-misleads")\n    return sorted(found)', 'def gate(spec):\n    found = []\n    if not spec.get("title", "").strip():\n        found.append("no-title")\n    if not spec.get("y_label", "").strip():\n        found.append("no-units")\n    if not spec.get("x_label", "").strip():\n        found.append("no-x-label")\n    pts = spec.get("points", 0)\n    if pts < 3:\n        found.append("too-few-points")\n    if spec.get("trendline") and pts < 10:\n        found.append("trendline-on-few-points")\n    return sorted(found)', 'def gate(spec):\n    found = []\n    if not spec["title"].strip():\n        found.append("no-title")\n    if not spec["y_label"].strip():\n        found.append("no-units")\n    if not spec["x_label"].strip():\n        found.append("no-x-label")\n    if spec["points"] < 3:\n        found.append("too-few-points")\n    if spec["trendline"] and spec["points"] < 10:\n        found.append("trendline-on-few-points")\n    if spec["dual_axis"]:\n        found.append("dual-axis-misleads")\n    return sorted(found)'],
  },
  'st-05-pearson': {
    valid: ['import math\ndef correlation(xs, ys):\n    n = len(xs)\n    if n < 2 or n != len(ys):\n        return None\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    if sx == 0 or sy == 0:\n        return None\n    return round(sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy), 3)'],
    wrong: ['import math\ndef correlation(xs, ys):\n    n = len(xs)\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    return round(sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy), 3)', 'import math\ndef correlation(xs, ys):\n    n = len(xs)\n    if n < 2 or n != len(ys):\n        return None\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    if sx == 0 or sy == 0:\n        return None\n    return round(abs(sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)), 3)', 'import math\ndef correlation(xs, ys):\n    n = len(xs)\n    if n < 2 or n != len(ys):\n        return None\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    if sx == 0 or sy == 0:\n        return None\n    return round(sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy), 2)', 'import math\ndef correlation(xs, ys):\n    n = len(xs)\n    if n < 2 or n != len(ys):\n        return None\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs) / n)\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys) / n)\n    if sx == 0 or sy == 0:\n        return None\n    return round(sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy), 3)', 'def correlation(xs, ys):\n    n = len(xs)\n    if n < 2 or n != len(ys):\n        return None\n    return round(1.0 if ys[-1] > ys[0] else -1.0, 3)'],
  },
  'st-05-strongest': {
    valid: ['import math, itertools\ndef _r(xs, ys):\n    n = len(xs)\n    if n < 2 or n != len(ys):\n        return None\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    if sx == 0 or sy == 0:\n        return None\n    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)\ndef strongest_pair(table):\n    best = None\n    for a, b in itertools.combinations(sorted(table), 2):\n        r = _r(table[a], table[b])\n        if r is None:\n            continue\n        if best is None or abs(r) > best[0] + 1e-12:\n            best = (abs(r), (a, b))\n    return best[1] if best else None'],
    wrong: ['import math, itertools\ndef _r(xs, ys):\n    n = len(xs)\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    if sx == 0 or sy == 0:\n        return None\n    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)\ndef strongest_pair(table):\n    best = None\n    for a, b in itertools.combinations(sorted(table), 2):\n        r = _r(table[a], table[b])\n        if r is None:\n            continue\n        if best is None or r > best[0]:\n            best = (r, (a, b))\n    return best[1] if best else None', 'import math, itertools\ndef _r(xs, ys):\n    n = len(xs)\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    if sx == 0 or sy == 0:\n        return None\n    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)\ndef strongest_pair(table):\n    best = None\n    for a, b in itertools.combinations(table, 2):\n        r = _r(table[a], table[b])\n        if r is None:\n            continue\n        if best is None or abs(r) > best[0] + 1e-12:\n            best = (abs(r), (a, b))\n    return best[1] if best else None', 'import math, itertools\ndef _r(xs, ys):\n    n = len(xs)\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)\ndef strongest_pair(table):\n    best = None\n    for a, b in itertools.combinations(sorted(table), 2):\n        r = _r(table[a], table[b])\n        if best is None or abs(r) > best[0] + 1e-12:\n            best = (abs(r), (a, b))\n    return best[1] if best else None', 'import math, itertools\ndef _r(xs, ys):\n    n = len(xs)\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    if sx == 0 or sy == 0:\n        return None\n    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)\ndef strongest_pair(table):\n    best = None\n    for a, b in itertools.combinations(sorted(table), 2):\n        r = _r(table[a], table[b])\n        if r is None:\n            continue\n        if best is None or abs(r) >= best[0]:\n            best = (abs(r), (a, b))\n    return best[1] if best else None'],
  },
  'st-05-strongest-b': {
    valid: ['import math, itertools\ndef _r(xs, ys):\n    n = len(xs)\n    if n < 2 or n != len(ys):\n        return None\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    if sx == 0 or sy == 0:\n        return None\n    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)\ndef best_related(table):\n    best = None\n    for a, b in itertools.combinations(sorted(table), 2):\n        r = _r(table[a], table[b])\n        if r is None:\n            continue\n        if best is None or abs(r) > best[0] + 1e-12:\n            best = (abs(r), (a, b))\n    return best[1] if best else None'],
    wrong: ['import math, itertools\ndef _r(xs, ys):\n    n = len(xs)\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    if sx == 0 or sy == 0:\n        return None\n    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)\ndef best_related(table):\n    best = None\n    for a, b in itertools.combinations(sorted(table), 2):\n        r = _r(table[a], table[b])\n        if r is None:\n            continue\n        if best is None or r > best[0]:\n            best = (r, (a, b))\n    return best[1] if best else None', 'import math, itertools\ndef _r(xs, ys):\n    n = len(xs)\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)\ndef best_related(table):\n    best = None\n    for a, b in itertools.combinations(sorted(table), 2):\n        r = _r(table[a], table[b])\n        if best is None or abs(r) > best[0] + 1e-12:\n            best = (abs(r), (a, b))\n    return best[1] if best else None', 'import math, itertools\ndef _r(xs, ys):\n    n = len(xs)\n    mx, my = sum(xs) / n, sum(ys) / n\n    sx = math.sqrt(sum((x - mx) ** 2 for x in xs))\n    sy = math.sqrt(sum((y - my) ** 2 for y in ys))\n    if sx == 0 or sy == 0:\n        return None\n    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / (sx * sy)\ndef best_related(table):\n    best = None\n    for a, b in itertools.combinations(sorted(table), 2):\n        r = _r(table[a], table[b])\n        if r is None:\n            continue\n        if best is None or abs(r) > best[0] + 1e-12:\n            best = (abs(r), (b, a))\n    return best[1] if best else None'],
  },

  'st-06-sample': {
    valid: ['import random\ndef audit_sample(invoices, k, seed):\n    items = list(invoices)\n    if k >= len(items):\n        return items\n    return random.Random(seed).sample(items, k)', 'import random\ndef audit_sample(invoices, k, seed):\n    random.seed(seed)\n    if k >= len(invoices):\n        return list(invoices)\n    return random.sample(list(invoices), k)'],
    wrong: ['import random\ndef audit_sample(invoices, k, seed):\n    return random.Random(seed).sample(invoices, k)', 'def audit_sample(invoices, k, seed):\n    return list(invoices)[:k]', 'import random\ndef audit_sample(invoices, k, seed):\n    items = list(invoices)\n    if k >= len(items):\n        return items\n    return random.sample(items, k)', 'import random\ndef audit_sample(invoices, k, seed):\n    items = list(invoices)\n    if k >= len(items):\n        return items\n    rng = random.Random(seed)\n    return [rng.choice(items) for _ in range(k)]', 'import random\ndef audit_sample(invoices, k, seed):\n    items = list(invoices)\n    random.Random(seed).shuffle(items)\n    return items[:k]'],
  },
  'st-06-stratified': {
    valid: ['import random\ndef region_sample(records, field, per_group, seed):\n    rng = random.Random(seed)\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    out = []\n    for g in sorted(groups, key=str):\n        members = groups[g]\n        out.extend(members if len(members) <= per_group else rng.sample(members, per_group))\n    return out', 'import random\ndef region_sample(records, field, per_group, seed):\n    rng = random.Random(seed)\n    out = []\n    for g in sorted({r[field] for r in records}, key=str):\n        members = [r for r in records if r[field] == g]\n        k = min(per_group, len(members))\n        out += rng.sample(members, k)\n    return out'],
    wrong: ['def region_sample(records, field, per_group, seed):\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    out = []\n    for g in sorted(groups, key=str):\n        out.extend(groups[g][:per_group])\n    return out', 'import random\ndef region_sample(records, field, per_group, seed):\n    return random.Random(seed).sample(records, min(per_group, len(records)))', 'import random\ndef region_sample(records, field, per_group, seed):\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    out = []\n    for g in sorted(groups, key=str):\n        out.extend(random.sample(groups[g], min(per_group, len(groups[g]))))\n    return out', 'import random\ndef region_sample(records, field, per_group, seed):\n    rng = random.Random(seed)\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    out = []\n    for g in sorted(groups, key=str):\n        out.extend(rng.sample(groups[g], per_group))\n    return out', 'import random\ndef region_sample(records, field, per_group, seed):\n    rng = random.Random(seed)\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    out = []\n    for g in sorted(groups, key=str):\n        groups[g].sort(key=lambda r: rng.random())\n        out.extend(groups[g][:per_group])\n        out.extend(groups[g][:1])\n    return out', 'import random\ndef region_sample(records, field, per_group, seed):\n    rng = random.Random(seed)\n    records.sort(key=lambda r: rng.random())\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    return [r for g in groups for r in groups[g][:per_group]]'],
  },
  'st-06-stratified-b': {
    valid: ['import random\ndef inspect_units(records, field, per_group, seed):\n    rng = random.Random(seed)\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    out = []\n    for g in sorted(groups, key=str):\n        members = groups[g]\n        out.extend(members if len(members) <= per_group else rng.sample(members, per_group))\n    return out', 'import random\ndef inspect_units(records, field, per_group, seed):\n    rng = random.Random(seed)\n    out = []\n    for g in sorted({r[field] for r in records}, key=str):\n        members = [r for r in records if r[field] == g]\n        k = min(per_group, len(members))\n        out += rng.sample(members, k)\n    return out'],
    wrong: ['def inspect_units(records, field, per_group, seed):\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    out = []\n    for g in sorted(groups, key=str):\n        out.extend(groups[g][:per_group])\n    return out', 'import random\ndef inspect_units(records, field, per_group, seed):\n    return random.Random(seed).sample(records, min(per_group, len(records)))', 'import random\ndef inspect_units(records, field, per_group, seed):\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    out = []\n    for g in sorted(groups, key=str):\n        out.extend(random.sample(groups[g], min(per_group, len(groups[g]))))\n    return out', 'import random\ndef inspect_units(records, field, per_group, seed):\n    rng = random.Random(seed)\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    out = []\n    for g in sorted(groups, key=str):\n        out.extend(rng.sample(groups[g], per_group))\n    return out', 'import random\ndef inspect_units(records, field, per_group, seed):\n    rng = random.Random(seed)\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    out = []\n    for g in sorted(groups, key=str):\n        groups[g].sort(key=lambda r: rng.random())\n        out.extend(groups[g][:per_group])\n        out.extend(groups[g][:1])\n    return out', 'import random\ndef inspect_units(records, field, per_group, seed):\n    rng = random.Random(seed)\n    records.sort(key=lambda r: rng.random())\n    groups = {}\n    for r in records:\n        groups.setdefault(r[field], []).append(r)\n    return [r for g in groups for r in groups[g][:per_group]]'],
  },
  'st-06-margin': {
    valid: ['import math\ndef poll_margin(p, n):\n    if n <= 0:\n        return None\n    return round(1.96 * math.sqrt(p * (1 - p) / n), 4)'],
    wrong: ['import math\ndef poll_margin(p, n):\n    if n <= 0:\n        return None\n    return round(1.96 * p * (1 - p) / math.sqrt(n), 4)', 'import math\ndef poll_margin(p, n):\n    if n <= 0:\n        return None\n    return round(1.96 * math.sqrt(p * (1 - p) / n), 3)', 'import math\ndef poll_margin(p, n):\n    return round(1.96 * math.sqrt(p * (1 - p) / n), 4)', 'import math\ndef poll_margin(p, n):\n    if n <= 0:\n        return None\n    return round(1.96 * math.sqrt(p * (1 - p)) / n, 4)', 'import math\ndef poll_margin(p, n):\n    if n <= 0:\n        return None\n    return round(2 * math.sqrt(p * (1 - p) / n), 4)'],
  },
  'st-06-margin-b': {
    valid: ['import math\ndef defect_margin(rate, n):\n    if n <= 0:\n        return None\n    return round(1.96 * math.sqrt(rate * (1 - rate) / n), 4)'],
    wrong: ['import math\ndef defect_margin(rate, n):\n    if n <= 0:\n        return None\n    return round(1.96 * math.sqrt(rate / n), 4)', 'import math\ndef defect_margin(rate, n):\n    if n <= 0:\n        return None\n    return round(1.96 * math.sqrt(rate * (1 - rate) / n), 2)', 'import math\ndef defect_margin(rate, n):\n    if n < 0:\n        return None\n    return round(1.96 * math.sqrt(rate * (1 - rate) / n), 4)', 'import math\ndef defect_margin(rate, n):\n    if n <= 0:\n        return None\n    return round(1.96 * math.sqrt(rate * (1 - rate) / (n - 1)), 4)'],
  },

  'st-07-expected': {
    valid: ['def expected_value(outcomes):\n    if abs(sum(p for _, p in outcomes) - 1) > 1e-9:\n        raise ValueError("probabilities must sum to 1")\n    return round(sum(v * p for v, p in outcomes), 4)', 'def expected_value(outcomes):\n    total = 0\n    weight = 0\n    for value, p in outcomes:\n        total += value * p\n        weight += p\n    if abs(weight - 1) > 1e-9:\n        raise ValueError("probabilities must sum to 1")\n    return round(total, 4)'],
    wrong: ['def expected_value(outcomes):\n    return round(sum(v * p for v, p in outcomes), 4)', 'def expected_value(outcomes):\n    weight = 0\n    for _, p in outcomes:\n        weight += p\n    if weight != 1:\n        raise ValueError("probabilities must sum to 1")\n    return round(sum(v * p for v, p in outcomes), 4)', 'def expected_value(outcomes):\n    if abs(sum(p for _, p in outcomes) - 1) > 1e-9:\n        raise ValueError("probabilities must sum to 1")\n    return round(sum(v for v, _ in outcomes) / len(outcomes), 4)', 'def expected_value(outcomes):\n    if abs(sum(p for _, p in outcomes) - 1) > 1e-9:\n        return None\n    return round(sum(v * p for v, p in outcomes), 4)', 'def expected_value(outcomes):\n    if abs(sum(p for _, p in outcomes) - 1) > 1e-9:\n        raise ValueError("probabilities must sum to 1")\n    return sum(v * p for v, p in outcomes)'],
  },
  'st-07-at-least': {
    valid: ['def batch_has_defect(p, n):\n    return round(1 - (1 - p) ** n, 4)', 'def batch_has_defect(p, n):\n    none = 1.0\n    for _ in range(n):\n        none *= 1 - p\n    return round(1 - none, 4)'],
    wrong: ['def batch_has_defect(p, n):\n    return round(min(1, p * n), 4)', 'def batch_has_defect(p, n):\n    return round((1 - p) ** n, 4)', 'def batch_has_defect(p, n):\n    return round(1 - p ** n, 4)', 'def batch_has_defect(p, n):\n    return 1 - (1 - p) ** n', 'def batch_has_defect(p, n):\n    return round(1 - (1 - p) ** (n - 1), 4)'],
  },
  'st-07-at-least-b': {
    valid: ['def any_outage(p, days):\n    return round(1 - (1 - p) ** days, 4)'],
    wrong: ['def any_outage(p, days):\n    return round(p * days, 4)', 'def any_outage(p, days):\n    return round((1 - p) ** days, 4)', 'def any_outage(p, days):\n    return round(1 - (1 - p) ** days, 2)', 'def any_outage(p, days):\n    return round(1 - (1 - p * days), 4) if days else 0.0'],
  },
  'st-07-simulate': {
    valid: ['import random\ndef estimate_double_six(trials, seed):\n    if trials <= 0:\n        return 0.0\n    rng = random.Random(seed)\n    hits = 0\n    for _ in range(trials):\n        if rng.randint(1, 6) == 6 and rng.randint(1, 6) == 6:\n            hits += 1\n    return hits / trials', 'import random\ndef estimate_double_six(trials, seed):\n    rng = random.Random(seed)\n    hits = sum(1 for _ in range(trials) if (rng.randint(1, 6), rng.randint(1, 6)) == (6, 6))\n    return hits / trials if trials else 0.0'],
    wrong: ['import random\ndef estimate_double_six(trials, seed):\n    rng = random.Random(seed)\n    hits = sum(1 for _ in range(trials) if rng.randint(1, 6) == 6)\n    return hits / trials if trials else 0.0', 'import random\ndef estimate_double_six(trials, seed):\n    rng = random.Random(seed)\n    hits = sum(1 for _ in range(trials) if rng.randint(1, 6) + rng.randint(1, 6) == 12 or rng.randint(1, 6) == 6)\n    return hits / trials if trials else 0.0', 'import random\ndef estimate_double_six(trials, seed):\n    hits = sum(1 for _ in range(trials) if random.randint(1, 6) == 6 and random.randint(1, 6) == 6)\n    return hits / trials if trials else 0.0', 'import random\ndef estimate_double_six(trials, seed):\n    rng = random.Random(seed)\n    hits = sum(1 for _ in range(trials) if rng.randint(1, 6) == 6 and rng.randint(1, 6) == 6)\n    return hits', 'import random\ndef estimate_double_six(trials, seed):\n    rng = random.Random(seed)\n    hits = sum(1 for _ in range(trials) if rng.randint(1, 5) == 6 and rng.randint(1, 6) == 6)\n    return hits / trials if trials else 0.0'],
  },
  'st-07-simulate-b': {
    valid: ['import random\ndef estimate_two_defects(trials, seed):\n    if trials <= 0:\n        return 0.0\n    rng = random.Random(seed)\n    hits = 0\n    for _ in range(trials):\n        defects = sum(1 for _ in range(10) if rng.random() < 0.05)\n        if defects >= 2:\n            hits += 1\n    return hits / trials'],
    wrong: ['import random\ndef estimate_two_defects(trials, seed):\n    if trials <= 0:\n        return 0.0\n    rng = random.Random(seed)\n    hits = 0\n    for _ in range(trials):\n        defects = sum(1 for _ in range(10) if rng.random() < 0.05)\n        if defects >= 1:\n            hits += 1\n    return hits / trials', 'import random\ndef estimate_two_defects(trials, seed):\n    if trials <= 0:\n        return 0.0\n    rng = random.Random(seed)\n    hits = 0\n    for _ in range(trials):\n        defects = sum(1 for _ in range(10) if rng.random() < 0.05)\n        if defects == 2:\n            hits += 1\n    return hits / trials', 'import random\ndef estimate_two_defects(trials, seed):\n    if trials <= 0:\n        return 0.0\n    rng = random.Random(seed)\n    hits = 0\n    for _ in range(trials):\n        defects = sum(1 for _ in range(10) if rng.random() < 0.5)\n        if defects >= 2:\n            hits += 1\n    return hits / trials', 'import random\ndef estimate_two_defects(trials, seed):\n    if trials <= 0:\n        return 0.0\n    hits = 0\n    for _ in range(trials):\n        defects = sum(1 for _ in range(10) if random.random() < 0.05)\n        if defects >= 2:\n            hits += 1\n    return hits / trials', 'import random\ndef estimate_two_defects(trials, seed):\n    return 0.0861'],
  },
  'st-08-se': {
    valid: ['import math\ndef standard_error(values):\n    n = len(values)\n    if n < 2:\n        return None\n    m = sum(values) / n\n    s = math.sqrt(sum((v - m) ** 2 for v in values) / (n - 1))\n    return round(s / math.sqrt(n), 4)', 'import statistics, math\ndef standard_error(values):\n    if len(values) < 2:\n        return None\n    return round(statistics.stdev(values) / math.sqrt(len(values)), 4)'],
    wrong: ['import math\ndef standard_error(values):\n    n = len(values)\n    if n < 2:\n        return None\n    m = sum(values) / n\n    s = math.sqrt(sum((v - m) ** 2 for v in values) / n)\n    return round(s / math.sqrt(n), 4)', 'import math\ndef standard_error(values):\n    n = len(values)\n    if n < 2:\n        return None\n    m = sum(values) / n\n    s = math.sqrt(sum((v - m) ** 2 for v in values) / (n - 1))\n    return round(s / n, 4)', 'import math\ndef standard_error(values):\n    n = len(values)\n    if n < 2:\n        return None\n    m = sum(values) / n\n    s = math.sqrt(sum((v - m) ** 2 for v in values) / (n - 1))\n    return round(s, 4)', 'import math\ndef standard_error(values):\n    n = len(values)\n    m = sum(values) / n\n    s = math.sqrt(sum((v - m) ** 2 for v in values) / (n - 1))\n    return round(s / math.sqrt(n), 4)'],
  },
  'st-08-interval': {
    valid: ['import math\ndef yield_interval(yields):\n    n = len(yields)\n    if n < 2:\n        return None\n    m = sum(yields) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in yields) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return (round(m - h, 2), round(m + h, 2))', 'import statistics, math\ndef yield_interval(yields):\n    if len(yields) < 2:\n        return None\n    m = statistics.mean(yields)\n    h = 1.96 * statistics.stdev(yields) / math.sqrt(len(yields))\n    return (round(m - h, 2), round(m + h, 2))'],
    wrong: ['import math\ndef yield_interval(yields):\n    n = len(yields)\n    if n < 2:\n        return None\n    m = sum(yields) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in yields) / n)\n    h = 1.96 * sd / math.sqrt(n)\n    return (round(m - h, 2), round(m + h, 2))', 'import math\ndef yield_interval(yields):\n    n = len(yields)\n    if n < 2:\n        return None\n    m = sum(yields) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in yields) / (n - 1))\n    h = 2 * sd / math.sqrt(n)\n    return (round(m - h, 2), round(m + h, 2))', 'import math\ndef yield_interval(yields):\n    n = len(yields)\n    if n < 2:\n        return None\n    m = sum(yields) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in yields) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return (m - h, m + h)', 'import math\ndef yield_interval(yields):\n    n = len(yields)\n    if n < 2:\n        return None\n    m = sum(yields) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in yields) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return round(m, 2)', 'import math\ndef yield_interval(yields):\n    n = len(yields)\n    if n < 2:\n        return None\n    m = sum(yields) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in yields) / (n - 1))\n    h = 1.96 * sd\n    return (round(m - h, 2), round(m + h, 2))'],
  },
  'st-08-interval-b': {
    valid: ['import math\ndef load_interval(times):\n    n = len(times)\n    if n < 2:\n        return None\n    m = sum(times) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in times) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return (round(m - h, 2), round(m + h, 2))', 'import statistics, math\ndef load_interval(times):\n    if len(times) < 2:\n        return None\n    m = statistics.mean(times)\n    h = 1.96 * statistics.stdev(times) / math.sqrt(len(times))\n    return (round(m - h, 2), round(m + h, 2))'],
    wrong: ['import math\ndef load_interval(times):\n    n = len(times)\n    if n < 2:\n        return None\n    m = sum(times) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in times) / n)\n    h = 1.96 * sd / math.sqrt(n)\n    return (round(m - h, 2), round(m + h, 2))', 'import math\ndef load_interval(times):\n    n = len(times)\n    if n < 2:\n        return None\n    m = sum(times) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in times) / (n - 1))\n    h = 2 * sd / math.sqrt(n)\n    return (round(m - h, 2), round(m + h, 2))', 'import math\ndef load_interval(times):\n    n = len(times)\n    if n < 2:\n        return None\n    m = sum(times) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in times) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return (m - h, m + h)', 'import math\ndef load_interval(times):\n    n = len(times)\n    if n < 2:\n        return None\n    m = sum(times) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in times) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return round(m, 2)', 'import math\ndef load_interval(times):\n    n = len(times)\n    if n < 2:\n        return None\n    m = sum(times) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in times) / (n - 1))\n    h = 1.96 * sd\n    return (round(m - h, 2), round(m + h, 2))'],
  },
  'st-08-compare': {
    valid: ['import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clearly_different(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return ahi < blo or bhi < alo'],
    wrong: ['import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clearly_different(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return ahi <= blo or bhi <= alo', 'import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clearly_different(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return ahi < blo', 'import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clearly_different(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return sum(a) / len(a) != sum(b) / len(b)', 'import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clearly_different(a, b):\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return ahi < blo or bhi < alo', 'import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 2.58 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clearly_different(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return ahi < blo or bhi < alo', 'import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / n)\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clearly_different(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return ahi < blo or bhi < alo'],
  },
  'st-08-compare-b': {
    valid: ['import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clear_improvement(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return blo > ahi'],
    wrong: ['import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clear_improvement(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return blo >= ahi', 'import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clear_improvement(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return ahi < blo or bhi < alo', 'import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clear_improvement(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return sum(b) / len(b) > sum(a) / len(a)', 'import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clear_improvement(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return alo > bhi', 'import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clear_improvement(a, b):\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return blo > ahi', 'import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))\n    h = 2.58 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clear_improvement(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return blo > ahi', 'import math\ndef _ci(v):\n    n = len(v)\n    m = sum(v) / n\n    sd = math.sqrt(sum((x - m) ** 2 for x in v) / n)\n    h = 1.96 * sd / math.sqrt(n)\n    return m - h, m + h\ndef clear_improvement(a, b):\n    if len(a) < 2 or len(b) < 2:\n        return False\n    alo, ahi = _ci(a)\n    blo, bhi = _ci(b)\n    return blo > ahi'],
  },
};
