import { text } from '../helpers';
import type { LessonBundle } from '../schema';
import { S, files, wc, web } from './helpers';

const NOSCROLL = "h.assert(document.documentElement.scrollWidth <= h.viewport.w + 1, 'The page scrolls sideways on a ' + h.viewport.w + 'px screen.');";
const cap = (s: string) => `${s[0]!.toUpperCase()}${s.slice(1)}`;
void cap;

/* ---------------------------------------------------------------- A: machine dashboard */
const dashboardData = (extra = '') => `const all = h.api.get('/api/machines'); const count = (s) => s === 'all' ? all.length : all.filter((m) => m.status === s).length; const label = (s) => s[0].toUpperCase() + s.slice(1); const cards = () => h.$$('#machines li.machine'); ${extra}`;

const DASH_LOADED = `h.eq(h.text('#state'), 'Loading machines...', 'Say that data is loading'); await h.settle(); h.eq(h.text('#state'), '');
for (const s of ['all', 'running', 'idle', 'down']) h.eq(h.text('.filter[data-status=' + s + ']'), label(s) + ' (' + count(s) + ')', 'The count on the ' + s + ' button');
h.eq(cards().length, all.length, 'One card per machine'); h.eq(h.text('#summary'), 'Showing ' + all.length + ' of ' + all.length + ' machines');
h.eq(cards().map((c) => c.className.split(/\\s+/).filter((k) => k !== 'machine')[0]), all.map((m) => m.status), 'Each card has its status as a class');
h.eq(cards().map((c) => h.norm(c.textContent).startsWith(all[cards().indexOf(c)].name + ' — ' + all[cards().indexOf(c)].department)), all.map(() => true), 'Each card starts with the name, a dash and the department'); h.eq(cards().map((c) => h.norm(c.querySelector('.badge').textContent)), all.map((m) => m.status));`;

const DASH_FILTER = `await h.settle(); h.click('.filter[data-status=down]'); const down = all.filter((m) => m.status === 'down'); h.eq(cards().map((c) => h.norm(c.textContent).split(' — ')[0]), down.map((m) => m.name), 'Only down machines'); h.eq(h.text('#summary'), 'Showing ' + down.length + ' of ' + all.length + ' machines'); for (const s of ['all', 'running', 'idle', 'down']) h.eq(h.$('.filter[data-status=' + s + ']').getAttribute('aria-pressed'), String(s === 'down'), 'aria-pressed on ' + s); h.eq(h.storage.getItem('machine-filter'), 'down', 'The choice is saved under machine-filter'); h.click('.filter[data-status=all]'); h.eq(cards().length, all.length); h.eq(h.storage.getItem('machine-filter'), 'all');`;

/* ---------------------------------------------------------------- B: study planner */
const add = "const add = (t, p) => { h.type('#title', t); if (p) h.select('#priority', p); h.click('#task-form button[type=submit]'); }; const rows = () => h.$$('#tasks li.task').map((l) => h.norm(l.querySelector('.title').textContent) + '|' + l.dataset.priority + '|' + (l.classList.contains('done') ? 'done' : 'open')).join(', ');";
const seed = (v: unknown) => ({ tasks: JSON.stringify(v) });

/* ---------------------------------------------------------------- D: expense log */
const AMT = 'Amount must be a positive number with at most 2 decimals';
const EXP_ADD = `const AMT = ${JSON.stringify(AMT)}; const add = (a, n, c) => { h.type('#amount', a); if (c) h.select('#category', c); h.type('#note', n); h.click('#expense-form button[type=submit]'); }; const rows = () => h.$$('#entries tbody tr').map((r) => h.norm(r.querySelector('.note').textContent) + '|' + r.dataset.category + '|' + h.norm(r.querySelector('.amount').textContent)).join(', '); `;

/* ---------------------------------------------------------------- C: stats explorer */
const statsBase = "const players = h.api.get('/api/players'); const teams = h.api.get('/api/teams'); const avg = (n) => n.toFixed(3).replace(/^0/, ''); const row = (p) => [p.name, p.team, p.position, avg(p.batting_avg), String(p.home_runs)]; const table = () => h.$$('#players tbody tr').map((r) => [...r.children].map((c) => h.norm(c.textContent))); const sortBtn = (k) => h.$('#players button[data-sort=' + k + ']'); const ariaSort = () => h.$$('#players thead th').map((t) => t.getAttribute('aria-sort') || 'none').join(',');";

export const bundle: LessonBundle = {
  lesson: {
    id: 'web-25-web-projects', title: 'Projects: Real Web Apps', language: 'web', skillId: 'web.apps',
    blurb: 'HTML, CSS, JavaScript, storage and an API in one working application.', prerequisites: ['web-24-fetch-write'], xpReward: 120,
    reference: {
      title: 'Building a complete web app',
      body: text(
        'A finished page is a small system: **HTML** for structure and meaning, **CSS** for looks and layout, **JavaScript** for behaviour, **storage** for memory, an **API** for outside data. Build it in layers and test each one: (1) write the HTML so it makes sense with no styling or script; (2) style it; (3) load and show the data; (4) add interaction; (5) add persistence; (6) handle loading, empty and error states; (7) check keyboard use, labels and small screens.',
        'Keep one **state** object (`machines`, `filter`, `sort`) and one `render()` that draws the page from it. Events change the state and call `render()`. Anything you would have to remember to update in two places is a bug waiting to happen.',
      ),
      example: 'let state = { items: [], filter: "all" };\nfunction render() {\n  // draw everything from state\n}\nasync function start() {\n  const r = await fetch("/api/machines");\n  state.items = await r.json();\n  render();\n}',
    },
    steps: [
      { kind: 'teach', title: 'From exercises to applications', body: text('Each project below has a **brief**, not a recipe. Names the checks depend on (ids, classes, attributes) are given in the brief; how you build it is up to you. Work in layers and run after every layer. The checks look at the finished page in a real browser: its structure, its styles, its behaviour, and what happens when things go wrong.') },
      { kind: 'challenge', challengeId: 'web-25-machine-dashboard' },
      { kind: 'challenge', challengeId: 'web-25-study-planner' },
      { kind: 'challenge', challengeId: 'web-25-stats-explorer' },
    ],
  },
  objectives: [
    { id: 'web-obj-app-api', title: 'Build an API-driven page: structure, style, behaviour and failure', summary: 'A complete page that loads data, filters or sorts it, remembers choices, and handles loading and errors.' },
    { id: 'web-obj-app-storage', title: 'Build a stateful page that remembers its data', summary: 'A complete page with validated input, derived views and defensive persistence.' },
  ],
  challenges: [
    wc({
      id: 'web-25-machine-dashboard', objectiveId: 'web-obj-app-api', title: 'Project: The Machine Shop Dashboard', mode: 'challenge', skillIds: ['web.apps', 'web.http', 'js.dom'], concepts: ['html', 'css', 'fetch', 'state', 'accessibility'], difficulty: 4, context: 'manufacturing', project: true, api: true,
      prompt: text(
        'Build a dashboard for the machine shop from `/api/machines`.',
        '**Structure.** A `main` containing an `h1` `Machine Shop`; a `nav` with a non-empty `aria-label` holding four buttons with the class `filter` and `data-status` of `all`, `running`, `idle`, `down` (in that order); a paragraph `#summary`; a paragraph `#state` that screen readers announce when it changes (`role="status"` or `aria-live`); and a list `#machines`.',
        '**Behaviour.** While loading `#state` says `Loading machines...`; when done it is empty. Each machine is an `li` with the classes `machine` and its status (`running`, `idle` or `down`), containing `<name> — <department>` and a `span.badge` with the status. Each filter button reads `<Status> (<count>)` (`All (10)`, `Running (6)`, …, capitalised, counts from the data). Clicking a button shows only that status, sets `aria-pressed="true"` on it and `"false"` on the others, and saves the choice in localStorage under `machine-filter`. `#summary` says `Showing <shown> of <total> machines`. The saved choice is applied when the page loads (anything unrecognised means `all`). If the request fails, `#state` says `Could not load machines (status <code>)` and every count is 0.',
        '**Looks.** Badges: running `#1b7f3b`, idle `#b57600`, down `#b00020`, each with white text. The pressed filter button must look different from the others. Cards sit in as many columns as fit (at least 2 on a 900px-wide screen, exactly 1 on a 400px-wide screen) and the page never scrolls sideways.',
      ),
      starterFiles: files('', '', ''),
      hints: ['Build in layers: static HTML first, then styles, then load and render, then filters, then storage, then failure.', 'One `render()` that draws the buttons, the cards and the summary from the state (all machines and the current filter).', 'Grid with `repeat(auto-fill, minmax(...))` adapts to screen size without media queries; restore the saved filter defensively.'],
      checks: [
        web('The page structure', "h.assert(document.querySelector('main h1') && h.text('main h1') === 'Machine Shop', 'A main element with the h1 Machine Shop.'); const nav = document.querySelector('main nav[aria-label]'); h.assert(nav && nav.getAttribute('aria-label').trim(), 'A nav element with an aria-label.'); h.eq([...document.querySelectorAll('nav button.filter')].map((b) => b.dataset.status), ['all', 'running', 'idle', 'down']); const st = h.$('#state'); h.assert(st.getAttribute('role') === 'status' || st.hasAttribute('aria-live'), 'The state message is announced to screen readers.'); h.assert(document.querySelector('#summary') && document.querySelector('ul#machines'));"),
        web('Loading and showing machines', dashboardData(DASH_LOADED)),
        web('Filtering and remembering', dashboardData(DASH_FILTER), { visible: false }),
        web('Restoring the saved choice', dashboardData("await h.settle(); const idle = all.filter((m) => m.status === 'idle'); h.eq(cards().length, idle.length, 'Only idle machines are shown at start'); h.eq(h.$('.filter[data-status=idle]').getAttribute('aria-pressed'), 'true'); h.eq(h.$('.filter[data-status=all]').getAttribute('aria-pressed'), 'false'); h.eq(h.text('#summary'), 'Showing ' + idle.length + ' of ' + all.length + ' machines');"), { storage: { 'machine-filter': 'idle' }, visible: false }),
        web('An unrecognised saved choice', dashboardData("await h.settle(); h.eq(cards().length, all.length, 'Unknown saved values mean all'); h.eq(h.$('.filter[data-status=all]').getAttribute('aria-pressed'), 'true');"), { storage: { 'machine-filter': 'bogus' }, visible: false }),
        web('When the server fails', "h.api.failNext(1, 503); await h.settle(); h.eq(h.text('#state'), 'Could not load machines (status 503)'); h.eq(h.$$('#machines li').length, 0); h.eq(h.text('.filter[data-status=all]'), 'All (0)'); h.eq(h.text('#summary'), 'Showing 0 of 0 machines');", { visible: false }),
        web('The hidden data set', dashboardData(DASH_LOADED + ' ' + DASH_FILTER), { api: 'b', visible: false }),
        web('Badge colours', dashboardData("await h.settle(); const want = { running: 'rgb(27, 127, 59)', idle: 'rgb(181, 118, 0)', down: 'rgb(176, 0, 32)' }; for (const s of Object.keys(want)) { const b = document.querySelector('.machine.' + s + ' .badge'); if (!b) continue; const cs = getComputedStyle(b); h.eq(cs.backgroundColor, want[s], 'The ' + s + ' badge colour'); h.eq(cs.color, 'rgb(255, 255, 255)', 'White badge text'); }"), { visible: false }),
        web('The pressed button looks different', "await h.settle(); const pick = (b) => { const c = getComputedStyle(b); return [c.fontWeight, c.backgroundColor, c.color, c.outlineStyle + c.outlineColor + c.outlineWidth, c.borderTopColor + c.borderTopWidth, c.textDecorationLine].join('|'); }; h.assert(pick(h.$('.filter[aria-pressed=true]')) !== pick(h.$('.filter[aria-pressed=false]')), 'Make the pressed filter button visibly different (weight, colour, outline, ...).');", { visible: false }),
        web('Wide layout', "await h.settle(); const lefts = new Set(h.$$('#machines li.machine').map((l) => Math.round(l.getBoundingClientRect().left))); h.assert(lefts.size >= 2, 'At 900px the cards must sit in at least 2 columns (got ' + lefts.size + ').'); " + NOSCROLL, { viewport: { width: 900 }, visible: false }),
        web('Narrow layout', "await h.settle(); const lefts = new Set(h.$$('#machines li.machine').map((l) => Math.round(l.getBoundingClientRect().left))); h.eq(lefts.size, 1, 'At 400px the cards form one column'); " + NOSCROLL, { viewport: { width: 400 }, visible: false }),
        web('No script errors', S.noErrors, { visible: false }),
      ],
      xpReward: 180, coinReward: 28,
    }),
    wc({
      id: 'web-25-study-planner', objectiveId: 'web-obj-app-storage', title: 'Project: The Study Planner', mode: 'challenge', skillIds: ['web.apps', 'js.forms', 'js.dom'], concepts: ['html', 'css', 'forms', 'localStorage', 'state', 'accessibility'], difficulty: 4, context: 'education', project: true,
      prompt: text(
        'Build a study planner that remembers its tasks (no API).',
        '**Structure.** A `main` with `h1` `Study Planner`. A form `#task-form` with a text input `#title`, a select `#priority` (`low`, `medium`, `high`; medium chosen at first), a submit button, and a paragraph `#error` that assistive technology announces at once (`role="alert"`). A select `#view` (`all`, `open`, `done`), a paragraph `#summary` and a list `#tasks`. Every input and select has a visible label connected to it.',
        '**Behaviour.** Submitting never leaves the page. The title is trimmed; if empty `#error` says `Task needs a title`; if shorter than 3 characters `Title must be at least 3 characters`; if it equals an existing title ignoring capitals `That task already exists`. Otherwise the task is added, the title box is cleared, and `#error` is empty. Each task is an `li` with the class `task` and `data-priority`, containing a label that wraps a checkbox and a `span.title`, and a button `button.delete` whose accessible name is `Delete <title>`. Ticking the checkbox marks the task done (class `done` on the `li`); deleting removes it. Tasks are listed high, then medium, then low priority, and in the order added within a priority. `#view` shows all, only open or only done tasks. `#summary` always counts every task: `<n> open, <m> done`.',
        '**Memory.** Every change is saved in localStorage under `tasks` as a JSON array of objects with `title`, `priority` and `done`, and restored on load. Unusable storage means an empty list; entries with a missing title, unknown priority or a `done` that is not true/false are skipped.',
        '**Looks.** High-priority tasks have a `4px solid #b00020` left border. Done titles are struck through and coloured `#666666`. On screens narrower than 500px the title box, the priority select and the submit button are stacked one above another; on wider screens they share a line. No sideways scrolling.',
      ),
      starterFiles: files('', '', ''),
      hints: ['State is an array of task objects; the list, the summary and storage are all views of it.', 'Sort for display without changing the stored order; validate before adding, in the order the messages are listed.', 'A media query for the narrow layout; `label` wrapping a checkbox gives it a name; `aria-label` names the delete buttons.'],
      checks: [
        web('The page structure', "h.assert(document.querySelector('main h1') && h.text('main h1') === 'Study Planner'); h.eq(h.$('#error').getAttribute('role'), 'alert', 'The error paragraph is announced'); h.eq(h.$('#task-form').tagName, 'FORM'); h.eq(h.$$('#priority option').map((o) => o.value), ['low', 'medium', 'high']); h.eq(h.value('#priority'), 'medium'); h.eq(h.$$('#view option').map((o) => o.value), ['all', 'open', 'done']); for (const id of ['#title', '#priority', '#view']) h.assert(h.labelText(id).length > 0, 'The control ' + id + ' needs a label.');"),
        web('Validation messages', add + " let prevented = null; document.addEventListener('submit', (e) => { prevented = e.defaultPrevented; }); add('  ', 'low'); h.assert(prevented === true, 'Stop the browser sending the form.'); h.eq(h.text('#error'), 'Task needs a title'); add('ab'); h.eq(h.text('#error'), 'Title must be at least 3 characters'); add('Read chapter 4'); h.eq(h.text('#error'), ''); add('READ CHAPTER 4'); h.eq(h.text('#error'), 'That task already exists'); h.eq(h.$$('#tasks li').length, 1); add('  abc  '); h.eq(h.text('#error'), '', 'A 3-character title is fine (and trimmed)'); h.eq(h.value('#title'), '', 'The box is cleared after adding');"),
        web('Order, priority and structure', add + " add('Low one', 'low'); add('High one', 'high'); add('Medium one', 'medium'); add('High two', 'high'); h.eq(rows(), 'High one|high|open, High two|high|open, Medium one|medium|open, Low one|low|open'); const li = h.$('#tasks li'); h.assert(li.querySelector('label input[type=checkbox]'), 'A checkbox inside a label'); h.eq(li.querySelector('.delete').getAttribute('aria-label') || li.querySelector('.delete').textContent.trim(), 'Delete High one', 'A delete button named after its task');"),
        web('Completing, deleting and the summary', add + " add('Alpha', 'medium'); add('Beta', 'medium'); add('Gamma', 'medium'); h.eq(h.text('#summary'), '3 open, 0 done'); h.click('#tasks li:nth-child(2) input[type=checkbox]'); h.eq(rows(), 'Alpha|medium|open, Beta|medium|done, Gamma|medium|open'); h.eq(h.text('#summary'), '2 open, 1 done'); h.click('#tasks li:nth-child(1) .delete'); h.eq(rows(), 'Beta|medium|done, Gamma|medium|open'); h.eq(h.text('#summary'), '1 open, 1 done'); h.click('#tasks li:nth-child(1) input[type=checkbox]'); h.eq(h.text('#summary'), '2 open, 0 done', 'Unticking makes it open again');", { visible: false }),
        web('The view filter', add + " add('Alpha'); add('Beta'); h.click('#tasks li:nth-child(1) input[type=checkbox]'); h.select('#view', 'open'); h.eq(rows(), 'Beta|medium|open'); h.eq(h.text('#summary'), '1 open, 1 done', 'The summary counts every task, not just the visible ones'); h.select('#view', 'done'); h.eq(rows(), 'Alpha|medium|done'); h.eq(h.text('#summary'), '1 open, 1 done', 'The summary counts every task, not just the visible ones'); h.select('#view', 'all'); h.eq(h.$$('#tasks li').length, 2);", { visible: false }),
        web('Saving', add + " add('Alpha', 'high'); add('Beta', 'low'); h.click('#tasks li:nth-child(2) input[type=checkbox]'); const saved = JSON.parse(h.storage.getItem('tasks')); h.eq(saved.map((t) => t.title + '|' + t.priority + '|' + t.done).sort(), ['Alpha|high|false', 'Beta|low|true']); h.click('#tasks li:nth-child(1) .delete'); h.eq(JSON.parse(h.storage.getItem('tasks')).length, 1, 'Deleting is saved too');", { visible: false }),
        web('Restoring', add + " h.eq(rows(), 'Zed|high|open, Amy|medium|done, Bob|low|open'); h.eq(h.text('#summary'), '2 open, 1 done'); add('New'); h.eq(JSON.parse(h.storage.getItem('tasks')).length, 4);", { storage: seed([{ title: 'Bob', priority: 'low', done: false }, { title: 'Amy', priority: 'medium', done: true }, { title: 'Zed', priority: 'high', done: false }]), visible: false }),
        web('Unusable storage', add + " h.eq(h.$$('#tasks li').length, 0); h.eq(h.text('#summary'), '0 open, 0 done'); add('Fresh'); h.eq(rows(), 'Fresh|medium|open');", { storage: { tasks: '[{"title":' }, visible: false }),
        web('Bad entries are skipped', add + " h.eq(rows(), 'Good|medium|open'); h.eq(h.text('#summary'), '1 open, 0 done');", { storage: seed([{ title: '', priority: 'low', done: false }, { title: 'Odd', priority: 'urgent', done: false }, { title: 'Flag', priority: 'low', done: 'yes' }, null, 5, { title: 'Good', priority: 'medium', done: false }]), visible: false }),
        web('Looks', add + " add('Important', 'high'); add('Finished', 'low'); h.click('#tasks li:nth-child(2) input[type=checkbox]'); const hi = getComputedStyle(h.$('#tasks li[data-priority=high]')); h.eq(hi.borderLeftWidth, '4px'); h.eq(hi.borderLeftStyle, 'solid'); h.eq(hi.borderLeftColor, 'rgb(176, 0, 32)'); const done = getComputedStyle(h.$('#tasks li.done .title')); h.assert(done.textDecorationLine.includes('line-through'), 'Done titles are struck through.'); h.eq(done.color, 'rgb(102, 102, 102)');", { visible: false }),
        web('Wide layout', "const t = h.$('#title').getBoundingClientRect(); const b = h.$('#task-form button[type=submit]').getBoundingClientRect(); h.assert(Math.abs(t.top - b.top) < 30, 'On a wide screen the title box and the button share a line.'); " + NOSCROLL, { viewport: { width: 900 }, visible: false }),
        web('Narrow layout', "const t = h.$('#title').getBoundingClientRect(); const p = h.$('#priority').getBoundingClientRect(); const b = h.$('#task-form button[type=submit]').getBoundingClientRect(); h.assert(p.top >= t.bottom - 1 && b.top >= p.bottom - 1, 'On a narrow screen the title box, the priority select and the button are stacked one above another.'); " + NOSCROLL, { viewport: { width: 400 }, visible: false }),
        web('No script errors', S.noErrors, { visible: false }),
      ],
      xpReward: 180, coinReward: 28,
    }),
    wc({
      id: 'web-25-stats-explorer', objectiveId: 'web-obj-app-api', title: 'Project: The League Stats Explorer', mode: 'challenge', skillIds: ['web.apps', 'web.http', 'js.dom'], concepts: ['html', 'css', 'fetch', 'state', 'accessibility'], difficulty: 4, context: 'sports', project: true, api: true,
      prompt: text(
        'Build a league statistics explorer from `/api/teams` and `/api/players`.',
        '**Structure.** A `main` with `h1` `League Stats`; a select `#team` with a visible connected label; a status paragraph `#state` (`role="status"`); a paragraph `#count`; and a table `#players` with a `caption`, a header row whose cells are `th scope="col"`, and a `tbody`. The table has five columns: Name, Team, Pos, AVG, HR. The Name, AVG and HR headers each contain a `button` with `data-sort` of `name`, `batting_avg` and `home_runs`.',
        '**Behaviour.** While loading `#state` says `Loading...` and is empty afterwards. `#team` starts with `All teams` (empty value) followed by one option per team, teams A–Z. The table shows the players (API order at first): name, team, position, average written with three decimals and no leading zero (`.279`), and home runs. Choosing a team shows only that team’s players. `#count` says `<n> players` (`1 player` for one) or `No players for <team>` when nobody plays for it. Clicking a sort button sorts the shown rows ascending by that column (numbers compared as numbers); clicking the same button again sorts descending; clicking a different one starts ascending. The `th` of the active column has `aria-sort="ascending"` or `"descending"`; the other sortable headers have `aria-sort="none"`. Choosing a different team returns to API order and clears the sorting. If loading fails, `#state` says `Could not load data (status <code>)`.',
        '**Looks.** The header row is `#1a3a6b` with white text, rows alternate `#f2f5fa` and white (odd rows shaded), and numeric columns (AVG, HR) are right-aligned. The page never scrolls sideways, even on a 400px-wide screen.',
      ),
      starterFiles: files('', '', ''),
      hints: ['State: the loaded players, the chosen team, and the current sort (column and direction). Everything else is drawn from those.', 'Numbers must be compared as numbers; text as text; equal values keep API order.', '`:nth-child(odd)` shades rows; `text-align` aligns a column.'],
      checks: [
        web('The page structure', "const m = document.querySelector('main'); h.assert(m && m.querySelector('h1') && h.text('main h1') === 'League Stats'); h.assert(h.labelText('#team').length > 0, 'The team select needs a label.'); h.eq(h.$('#state').getAttribute('role'), 'status'); const t = h.$('#players'); h.assert(t.querySelector('caption'), 'The table needs a caption.'); h.eq([...t.querySelectorAll('thead th')].map((c) => c.getAttribute('scope')), ['col', 'col', 'col', 'col', 'col']); h.eq([...t.querySelectorAll('thead th')].map((c) => h.norm(c.textContent)), ['Name', 'Team', 'Pos', 'AVG', 'HR']); h.eq([...t.querySelectorAll('thead button')].map((b) => b.dataset.sort), ['name', 'batting_avg', 'home_runs']);"),
        web('Loading and showing players', statsBase + " h.eq(h.text('#state'), 'Loading...'); await h.settle(); h.eq(h.text('#state'), ''); h.eq(table(), players.map(row), 'One row per player, in API order'); h.eq(h.text('#count'), players.length + ' players'); h.eq(h.$$('#team option').map((o) => [o.value, h.norm(o.textContent)]), [['', 'All teams'], ...teams.map((t) => t.name).sort().map((n) => [n, n])], 'The team options');"),
        web('Choosing a team', statsBase + " await h.settle(); const t = teams.map((x) => x.name).sort().find((n) => players.filter((p) => p.team === n).length >= 2); h.select('#team', t); await h.settle(); const mine = players.filter((p) => p.team === t); h.eq(table(), mine.map(row)); h.eq(h.text('#count'), mine.length + ' players'); h.select('#team', ''); await h.settle(); h.eq(table().length, players.length);", { visible: false }),
        web('Singular and empty', statsBase + " await h.settle(); const one = teams.map((x) => x.name).find((n) => players.filter((p) => p.team === n).length === 1); if (one) { h.select('#team', one); await h.settle(); h.eq(h.text('#count'), '1 player'); } const none = teams.map((x) => x.name).find((n) => !players.some((p) => p.team === n)); if (none) { h.select('#team', none); await h.settle(); h.eq(h.text('#count'), 'No players for ' + none); h.eq(table().length, 0); } h.assert(one || none, 'internal: the data must contain a team with one or with no players');", { visible: false }),
        web('Sorting', statsBase + " await h.settle(); sortBtn('home_runs').click(); h.eq(table().map((r) => Number(r[4])), players.map((p) => p.home_runs).sort((a, b) => a - b), 'Ascending by home runs, as numbers'); h.eq(ariaSort(), 'none,none,none,none,ascending'); sortBtn('home_runs').click(); h.eq(table().map((r) => Number(r[4])), players.map((p) => p.home_runs).sort((a, b) => b - a), 'Descending on the second click'); h.eq(ariaSort().split(',')[4], 'descending'); sortBtn('name').click(); h.eq(table().map((r) => r[0]), players.map((p) => p.name).sort(), 'A new column starts ascending'); h.eq(ariaSort(), 'ascending,none,none,none,none'); sortBtn('batting_avg').click(); h.eq(table().map((r) => r[3]), players.map((p) => p.batting_avg).sort((a, b) => a - b).map(avg), 'By average, ascending'); h.eq(ariaSort(), 'none,none,none,ascending,none');", { visible: false }),
        web('Changing team resets the sort', statsBase + " await h.settle(); sortBtn('name').click(); const t = players[0].team; h.select('#team', t); await h.settle(); h.eq(table(), players.filter((p) => p.team === t).map(row), 'API order again'); h.eq(ariaSort(), 'none,none,none,none,none'); sortBtn('name').click(); h.eq(ariaSort().split(',')[0], 'ascending', 'The first click after a reset is ascending');", { visible: false }),
        web('When the server fails', "h.api.failNext(1, 503); await h.settle(); h.eq(h.text('#state'), 'Could not load data (status 503)'); h.eq(h.$$('#players tbody tr').length, 0);", { visible: false }),
        web('The hidden data set', statsBase + " await h.settle(); h.eq(table(), players.map(row)); sortBtn('home_runs').click(); sortBtn('home_runs').click(); h.eq(table().map((r) => Number(r[4])), players.map((p) => p.home_runs).sort((a, b) => b - a)); const t = teams[0].name; h.select('#team', t); await h.settle(); h.eq(table().length, players.filter((p) => p.team === t).length);", { api: 'b', visible: false }),
        web('Looks', "await h.settle(); const th = getComputedStyle(h.$('#players thead tr')); const cell = getComputedStyle(h.$('#players thead th')); h.assert(th.backgroundColor === 'rgb(26, 58, 107)' || cell.backgroundColor === 'rgb(26, 58, 107)', 'The header row is #1a3a6b.'); h.assert(cell.color === 'rgb(255, 255, 255)' || getComputedStyle(h.$('#players thead th button')).color === 'rgb(255, 255, 255)', 'White header text.'); const rows = h.$$('#players tbody tr'); h.eq(getComputedStyle(rows[0]).backgroundColor, 'rgb(242, 245, 250)', 'Odd rows are shaded'); h.assert(getComputedStyle(rows[1]).backgroundColor !== 'rgb(242, 245, 250)', 'Even rows are not shaded'); for (const i of [3, 4]) h.eq(getComputedStyle(rows[0].children[i]).textAlign, 'right', 'Numeric columns are right-aligned');", { visible: false }),
        web('Narrow screen', "await h.settle(); " + NOSCROLL, { viewport: { width: 400 }, visible: false }),
        web('No script errors', S.noErrors, { visible: false }),
      ],
      xpReward: 190, coinReward: 30,
    }),
    wc({
      id: 'web-25-expense-log', objectiveId: 'web-obj-app-storage', title: 'Project: The Expense Log', mode: 'challenge', skillIds: ['web.apps', 'js.forms', 'js.dom'], concepts: ['html', 'css', 'forms', 'localStorage', 'state', 'accessibility'], difficulty: 4, context: 'finance', project: true,
      prompt: text(
        'Build an expense log that remembers its entries (no API).',
        '**Structure.** A `main` with `h1` `Expense Log`. A form `#expense-form` with an amount box `#amount`, a select `#category` (`food`, `travel`, `tools`), a note box `#note`, a submit button, and a paragraph `#error` that assistive technology announces at once (`role="alert"`). A select `#view` (`all`, `food`, `travel`, `tools`), a paragraph `#summary`, and a table `#entries` with a `tbody`. Every input and select has a visible label connected to it.',
        '**Behaviour.** Submitting never leaves the page. The amount (spaces around it ignored) must be digits with an optional decimal part of one or two digits (`12`, `12.5`, `12.50`) and greater than zero, otherwise `#error` says `Amount must be a positive number with at most 2 decimals`. The note (trimmed) must not be empty (`Note is required`) and must be at most 40 characters (`Note must be 40 characters or fewer`); the amount is checked first. A valid entry is added at the **top** of the table as a `tr` with the class `entry` and `data-category`, holding `td.amount` (written like `£12.50`), `td.category`, `td.note`, and a button `button.delete` whose accessible name is `Delete <note>`; the amount and note boxes are cleared and `#error` is empty. Deleting removes the entry. `#view` shows all entries or only one category. `#summary` describes what is **shown**: `<n> entries, total £<sum to 2 decimals>` (`1 entry` for one, and `0 entries, total £0.00` for none).',
        '**Memory.** Every change is saved in localStorage under `expenses` as a JSON array of objects with `amount` (a number), `category` and `note`, and restored on load (newest first as before). Unusable storage means an empty log; entries with an amount that is not a positive number, an unknown category or an empty note are skipped.',
        '**Looks.** Entries over £100 (strictly) get the class `big`, written bold in `#b00020`. Amount cells are right-aligned. On screens narrower than 500px the amount box, the category select, the note box and the submit button are stacked one above another. No sideways scrolling.',
      ),
      starterFiles: files('', '', ''),
      hints: ['State is an array of entry objects; the table, the summary and storage are all views of it.', 'Validate in the order the messages are listed; keep money as numbers and format with `toFixed(2)` only when displaying.', 'Sum the visible entries for the summary; a media query stacks the form; `:nth-child` is not needed, a class is.'],
      checks: [
        web('The page structure', "h.assert(document.querySelector('main h1') && h.text('main h1') === 'Expense Log'); h.eq(h.$('#error').getAttribute('role'), 'alert'); h.eq(h.$('#expense-form').tagName, 'FORM'); h.eq(h.$$('#category option').map((o) => o.value), ['food', 'travel', 'tools']); h.eq(h.$$('#view option').map((o) => o.value), ['all', 'food', 'travel', 'tools']); h.assert(h.$('#entries tbody'), 'A table with a tbody.'); for (const id of ['#amount', '#category', '#note', '#view']) h.assert(h.labelText(id).length > 0, 'The control ' + id + ' needs a label.');"),
        web('Validation messages', EXP_ADD + " let prevented = null; document.addEventListener('submit', (e) => { prevented = e.defaultPrevented; }); add('', 'x'); h.assert(prevented === true, 'Stop the browser sending the form.'); h.eq(h.text('#error'), AMT); for (const bad of ['0', '0.00', '-5', 'abc', '12.345', '1e2', '1,5', '.']) { add(bad, 'ok'); h.eq(h.text('#error'), AMT, 'For \"' + bad + '\"'); } add('5', '   '); h.eq(h.text('#error'), 'Note is required'); add('5', 'x'.repeat(41)); h.eq(h.text('#error'), 'Note must be 40 characters or fewer'); add('abc', ''); h.eq(h.text('#error'), AMT, 'The amount is checked first'); h.eq(h.$$('#entries tbody tr').length, 0, 'Nothing was added'); add(' 12.5 ', 'x'.repeat(40)); h.eq(h.text('#error'), ''); h.eq(h.$$('#entries tbody tr').length, 1); add('7', 'b'); h.eq(h.text('#error'), '');"),
        web('Entries, newest first', EXP_ADD + " add('12.5', 'Lunch', 'food'); add('40', 'Train', 'travel'); add('3', 'Tape', 'tools'); h.eq(rows(), 'Tape|tools|£3.00, Train|travel|£40.00, Lunch|food|£12.50'); h.eq(h.value('#amount'), '', 'The amount box is cleared'); h.eq(h.value('#note'), '', 'The note box is cleared'); const del = h.$('#entries tbody tr .delete'); h.eq(del.getAttribute('aria-label') || del.textContent.trim(), 'Delete Tape', 'A delete button named after its entry'); h.assert(h.$('#entries tbody tr').classList.contains('entry') && h.$('#entries tbody tr').dataset.category === 'tools');", { visible: false }),
        web('The summary and the filter', EXP_ADD + " h.eq(h.text('#summary'), '0 entries, total £0.00'); add('10', 'a', 'food'); h.eq(h.text('#summary'), '1 entry, total £10.00'); add('20.25', 'b', 'travel'); add('0.1', 'c', 'food'); add('0.2', 'd', 'food'); h.eq(h.text('#summary'), '4 entries, total £30.55'); h.select('#view', 'food'); h.eq(rows(), 'd|food|£0.20, c|food|£0.10, a|food|£10.00'); h.eq(h.text('#summary'), '3 entries, total £10.30', 'The summary describes what is shown'); h.select('#view', 'travel'); h.eq(h.text('#summary'), '1 entry, total £20.25'); h.select('#view', 'tools'); h.eq(h.text('#summary'), '0 entries, total £0.00'); h.select('#view', 'all'); h.eq(h.$$('#entries tbody tr').length, 4);", { visible: false }),
        web('Deleting', EXP_ADD + " add('1', 'one', 'food'); add('2', 'two', 'food'); add('3', 'three', 'food'); h.click('#entries tbody tr:nth-child(2) .delete'); h.eq(rows(), 'three|food|£3.00, one|food|£1.00'); h.eq(h.text('#summary'), '2 entries, total £4.00'); h.eq(JSON.parse(h.storage.getItem('expenses')).length, 2, 'Deleting is saved too');", { visible: false }),
        web('Saving', EXP_ADD + " add('12.5', 'Lunch', 'food'); add('40', 'Train', 'travel'); const saved = JSON.parse(h.storage.getItem('expenses')); h.eq(saved.map((e) => e.category + '|' + e.note + '|' + e.amount).sort(), ['food|Lunch|12.5', 'travel|Train|40']); h.assert(saved.every((e) => typeof e.amount === 'number'), 'Amounts are stored as numbers.');", { visible: false }),
        web('Restoring', EXP_ADD + " h.eq(rows(), 'Top|tools|£5.00, Old|food|£1.50'); h.eq(h.text('#summary'), '2 entries, total £6.50'); add('2', 'New', 'food'); h.eq(JSON.parse(h.storage.getItem('expenses')).length, 3);", { storage: { expenses: JSON.stringify([{ amount: 5, category: 'tools', note: 'Top' }, { amount: 1.5, category: 'food', note: 'Old' }]) }, visible: false }),
        web('Unusable storage', EXP_ADD + " h.eq(h.$$('#entries tbody tr').length, 0); h.eq(h.text('#summary'), '0 entries, total £0.00'); add('3', 'Fresh', 'food'); h.eq(rows(), 'Fresh|food|£3.00');", { storage: { expenses: '[{"amount":' }, visible: false }),
        web('Bad entries are skipped', EXP_ADD + " h.eq(rows(), 'Fine|food|£2.00'); h.eq(h.text('#summary'), '1 entry, total £2.00');", { storage: { expenses: JSON.stringify([{ amount: -1, category: 'food', note: 'Neg' }, { amount: '5', category: 'food', note: 'Text' }, { amount: 4, category: 'fuel', note: 'Cat' }, { amount: 3, category: 'food', note: '' }, null, 8, { amount: 0, category: 'tools', note: 'Zero' }, { amount: 2, category: 'food', note: 'Fine' }]) }, visible: false }),
        web('Looks', EXP_ADD + " add('100', 'Exactly', 'tools'); add('100.01', 'Over', 'tools'); const big = h.$$('#entries tbody tr.big'); h.eq(big.length, 1, 'Only entries over 100 are big'); h.eq(h.norm(big[0].querySelector('.note').textContent), 'Over'); const c = getComputedStyle(big[0]); h.assert(c.color === 'rgb(176, 0, 32)' || getComputedStyle(big[0].querySelector('.amount')).color === 'rgb(176, 0, 32)', 'Big entries are #b00020.'); h.assert(parseInt(getComputedStyle(big[0].querySelector('.amount')).fontWeight, 10) >= 700 || parseInt(c.fontWeight, 10) >= 700, 'Big entries are bold.'); h.eq(getComputedStyle(h.$('#entries tbody tr .amount')).textAlign, 'right');", { visible: false }),
        web('Wide layout', "const a = h.$('#amount').getBoundingClientRect(); const b = h.$('#expense-form button[type=submit]').getBoundingClientRect(); h.assert(Math.abs(a.top - b.top) < 40, 'On a wide screen the amount box and the button share a line.'); " + NOSCROLL, { viewport: { width: 900 }, visible: false }),
        web('Narrow layout', "const r = ['#amount', '#category', '#note', '#expense-form button[type=submit]'].map((s) => h.$(s).getBoundingClientRect()); for (let i = 1; i < r.length; i++) h.assert(r[i].top >= r[i - 1].bottom - 1, 'On a narrow screen the controls are stacked one above another.'); " + NOSCROLL, { viewport: { width: 400 }, visible: false }),
        web('No script errors', S.noErrors, { visible: false }),
      ],
      xpReward: 180, coinReward: 28,
    }),
  ],
};
