import type { WebFiles } from '../schema';
import type { Sol } from './solutions.testdata';

/** JavaScript-only solutions: `js` strings; html is blank. */
export const fj = (js: string, html = '', css = ''): WebFiles => ({ html, css, js });

export const jsSolutions: Record<string, Sol> = {
  'web-15-console-hello': {
    valid: [fj('const machine = "M-7";\nconst status = "running";\nconst temp = 72.5;\nconsole.log(`Machine: ${machine}`);\nconsole.log(`Status: ${status}`);\nconsole.log("Temperature: " + temp + " C");')],
    wrong: [fj('console.log("Machine: M-7");\nconsole.log("Status: running");\nconsole.log("Temperature: 72.5 C");'), fj('const machine = "M-7";\nconst status = "running";\nconst temp = 72.5;\nconsole.log(`Status: ${status}`);\nconsole.log(`Machine: ${machine}`);\nconsole.log(`Temperature: ${temp} C`);'), fj('const machine = "M-7";\nconst status = "running";\nconst temp = 72.5;\nconsole.log(`Machine: ${machine}`);\nconsole.log(`Status: ${status}`);\nconsole.log(`Temperature: ${temp}`);'), fj('const machine = "M-7";\nconsole.log("Machine:", machine);')],
  },
  'web-15-parcel-class': {
    valid: [fj('function parcelClass(weightKg, fragile) {\n  if (weightKg <= 0) return "invalid";\n  if (weightKg >= 30) return "freight";\n  if (fragile) return "careful";\n  if (weightKg >= 5) return "standard";\n  return "letter";\n}'), fj('const parcelClass = (w, f) => w <= 0 ? "invalid" : w >= 30 ? "freight" : f ? "careful" : w >= 5 ? "standard" : "letter";')],
    wrong: [fj('function parcelClass(w, f) {\n  if (f) return "careful";\n  if (w >= 30) return "freight";\n  if (w >= 5) return "standard";\n  return "letter";\n}'), fj('function parcelClass(w, f) {\n  if (w <= 0) return "invalid";\n  if (w > 30) return "freight";\n  if (f) return "careful";\n  if (w > 5) return "standard";\n  return "letter";\n}'), fj('function parcelClass(w, f) {\n  if (w >= 30) return "freight";\n  if (f) return "careful";\n  if (w >= 5) return "standard";\n  return "letter";\n}'), fj('function parcelClass(w, f) {\n  if (w <= 0) return "invalid";\n  if (w >= 30) return "freight";\n  if (f == true) return "careful";\n  if (w >= 5) return "standard";\n}'), fj('function parcelClass(w, f) {\n  if (w <= 0) return "invalid";\n  if (w >= 30) console.log("freight");\n}')],
  },
  'web-15-letter-grade': {
    valid: [fj('function letterGrade(score) {\n  if (typeof score !== "number" || Number.isNaN(score) || score < 0 || score > 100) return "invalid";\n  if (score >= 90) return "A";\n  if (score >= 80) return "B";\n  if (score >= 70) return "C";\n  if (score >= 60) return "D";\n  return "F";\n}')],
    wrong: [fj('function letterGrade(s) {\n  if (s >= 90) return "A";\n  if (s >= 80) return "B";\n  if (s >= 70) return "C";\n  if (s >= 60) return "D";\n  return "F";\n}'), fj('function letterGrade(s) {\n  if (typeof s !== "number" || s < 0 || s > 100) return "invalid";\n  if (s > 90) return "A";\n  if (s >= 80) return "B";\n  if (s >= 70) return "C";\n  if (s >= 60) return "D";\n  return "F";\n}'), fj('function letterGrade(s) {\n  if (s < 0 || s > 100) return "invalid";\n  if (s >= 90) return "A";\n  if (s >= 80) return "B";\n  if (s >= 70) return "C";\n  if (s >= 60) return "D";\n  return "F";\n}'), fj('function letterGrade(s) {\n  if (typeof s !== "number" || Number.isNaN(s) || s < 0 || s > 100) return "invalid";\n  if (s >= 90) return "A";\n  if (s >= 80) return "B";\n  if (s >= 70) return "C";\n  if (s > 60) return "D";\n  return "F";\n}')],
  },
  'web-15-race-flag': {
    valid: [fj('function flagFor(speedKmh, limitKmh, raining) {\n  if (speedKmh <= 0) return "stopped";\n  if (speedKmh > limitKmh * 1.2) return "red";\n  if (speedKmh > limitKmh) return "yellow";\n  if (raining && speedKmh > limitKmh * 0.8) return "blue";\n  return "green";\n}')],
    wrong: [fj('function flagFor(s, l, r) {\n  if (s <= 0) return "stopped";\n  if (s > l) return "yellow";\n  if (s > l * 1.2) return "red";\n  if (r && s > l * 0.8) return "blue";\n  return "green";\n}'), fj('function flagFor(s, l, r) {\n  if (s <= 0) return "stopped";\n  if (s >= l * 1.2) return "red";\n  if (s > l) return "yellow";\n  if (r && s > l * 0.8) return "blue";\n  return "green";\n}'), fj('function flagFor(s, l, r) {\n  if (s <= 0) return "stopped";\n  if (s > l * 1.2) return "red";\n  if (s > l) return "yellow";\n  if (r) return "blue";\n  return "green";\n}'), fj('function flagFor(s, l, r) {\n  if (s > l * 1.2) return "red";\n  if (s > l) return "yellow";\n  if (r && s > l * 0.8) return "blue";\n  return "green";\n}')],
  },
  'web-15-count-above': {
    valid: [fj('function countAbove(readings, limit) {\n  let n = 0;\n  for (const r of readings) {\n    if (r > limit) n++;\n  }\n  return n;\n}'), fj('const countAbove = (r, l) => r.filter((x) => x > l).length;')],
    wrong: [fj('function countAbove(readings, limit) {\n  let n = 0;\n  for (const r of readings) if (r >= limit) n++;\n  return n;\n}'), fj('function countAbove(readings, limit) {\n  let n = 0;\n  for (const r of readings) if (r > limit) n = 1;\n  return n;\n}'), fj('function countAbove(readings, limit) {\n  readings.sort();\n  return readings.filter((x) => x > limit).length;\n}'), fj('function countAbove(readings, limit) {\n  let n = 0;\n  for (let i = 1; i < readings.length; i++) if (readings[i] > limit) n++;\n  return n;\n}')],
  },
  'web-15-average-lap': {
    valid: [fj('function averageLap(laps) {\n  if (laps.length === 0) return null;\n  let total = 0;\n  for (const t of laps) total += t;\n  return Math.round(total / laps.length * 1000) / 1000;\n}')],
    wrong: [fj('function averageLap(laps) {\n  let total = 0;\n  for (const t of laps) total += t;\n  return Math.round(total / laps.length * 1000) / 1000;\n}'), fj('function averageLap(laps) {\n  if (laps.length === 0) return null;\n  let total = 0;\n  for (const t of laps) total += t;\n  return total / laps.length;\n}'), fj('function averageLap(laps) {\n  if (laps.length === 0) return 0;\n  let total = 0;\n  for (const t of laps) total += t;\n  return Math.round(total / laps.length * 1000) / 1000;\n}'), fj('function averageLap(laps) {\n  if (laps.length === 0) return null;\n  let total = 0;\n  for (let i = 0; i < laps.length - 1; i++) total += laps[i];\n  return Math.round(total / laps.length * 1000) / 1000;\n}')],
  },
  'web-15-win-streak': {
    valid: [fj('function longestStreak(results) {\n  let best = 0;\n  let run = 0;\n  for (const r of results) {\n    if (r === "W") {\n      run++;\n      best = Math.max(best, run);\n    } else {\n      run = 0;\n    }\n  }\n  return best;\n}')],
    wrong: [fj('function longestStreak(results) {\n  return results.filter((r) => r === "W").length;\n}'), fj('function longestStreak(results) {\n  let best = 0, run = 0;\n  for (const r of results) {\n    if (r === "W") run++; else run = 0;\n  }\n  return run;\n}'), fj('function longestStreak(results) {\n  let best = 0, run = 0;\n  for (const r of results) {\n    if (r === "W") { run++; best = Math.max(best, run); } else if (r === "L") run = 0;\n  }\n  return best;\n}'), fj('function longestStreak(results) {\n  let best = 0, run = 0;\n  for (const r of results) {\n    if (r === "W") { run++; if (run > best) best = run; } else { run = 1; }\n  }\n  return best;\n}')],
  },
};

const M = '[{ id: 1, name: "Press", status: "running", hours: 4.5 }, { id: 2, name: "Lathe", status: "down", hours: 12 }]';
Object.assign(jsSolutions, {
  'web-16-down-machines': {
    valid: [fj('function downMachines(machines) {\n  return machines.filter((m) => m.status === "down").map((m) => m.name).sort();\n}'), fj('function downMachines(machines) {\n  const names = [];\n  for (const m of machines) if (m.status === "down") names.push(m.name);\n  return names.sort();\n}')],
    wrong: [fj('function downMachines(machines) {\n  return machines.filter((m) => m.status === "down").map((m) => m.name);\n}'), fj('function downMachines(machines) {\n  return machines.sort((a, b) => (a.name < b.name ? -1 : 1)).filter((m) => m.status === "down").map((m) => m.name);\n}'), fj('function downMachines(machines) {\n  return machines.filter((m) => m.status === "down").sort();\n}'), fj('function downMachines(machines) {\n  return machines.filter((m) => m.status == "down").map((m) => m.name).sort().reverse();\n}')],
  },
  'web-16-total-revenue': {
    valid: [fj('function totalRevenue(orders) {\n  const total = orders.filter((o) => o.status !== "returned").reduce((sum, o) => sum + o.qty * o.price, 0);\n  return Math.round(total * 100) / 100;\n}')],
    wrong: [fj('function totalRevenue(orders) {\n  return Math.round(orders.reduce((s, o) => s + o.qty * o.price, 0) * 100) / 100;\n}'), fj('function totalRevenue(orders) {\n  return orders.filter((o) => o.status !== "returned").reduce((s, o) => s + o.qty * o.price, 0);\n}'), fj('function totalRevenue(orders) {\n  return Math.round(orders.filter((o) => o.status !== "returned").reduce((s, o) => s + o.price, 0) * 100) / 100;\n}'), fj('function totalRevenue(orders) {\n  return orders.filter((o) => o.status !== "returned").reduce((s, o) => s + Math.round(o.qty * o.price * 100) / 100, 0);\n}')],
  },
  'web-16-top-scorers': {
    valid: [fj('function topScorers(players, n) {\n  return [...players].sort((a, b) => b.points - a.points || a.name.localeCompare(b.name)).slice(0, n).map((p) => p.name);\n}')],
    wrong: [fj('function topScorers(players, n) {\n  return players.sort((a, b) => b.points - a.points).slice(0, n).map((p) => p.name);\n}'), fj('function topScorers(players, n) {\n  return [...players].sort((a, b) => b.points - a.points).slice(0, n).map((p) => p.name);\n}'), fj('function topScorers(players, n) {\n  return [...players].sort((a, b) => a.points - b.points || a.name.localeCompare(b.name)).slice(0, n).map((p) => p.name);\n}'), fj('function topScorers(players, n) {\n  return [...players].sort((a, b) => b.points - a.points || a.name.localeCompare(b.name)).slice(0, n + 1).map((p) => p.name);\n}')],
  },
  'web-16-avg-by-dept': {
    valid: [fj('function averageByDepartment(employees) {\n  const groups = {};\n  for (const e of employees) {\n    if (!groups[e.department]) groups[e.department] = [];\n    groups[e.department].push(e.rate);\n  }\n  const result = {};\n  for (const [dept, rates] of Object.entries(groups)) {\n    const avg = rates.reduce((a, b) => a + b, 0) / rates.length;\n    result[dept] = Math.round(avg * 100) / 100;\n  }\n  return result;\n}')],
    wrong: [fj('function averageByDepartment(employees) {\n  const groups = {};\n  for (const e of employees) {\n    if (!groups[e.department]) groups[e.department] = [];\n    groups[e.department].push(e.rate);\n  }\n  const result = {};\n  for (const [dept, rates] of Object.entries(groups)) {\n    result[dept] = rates.reduce((a, b) => a + b, 0) / rates.length;\n  }\n  return result;\n}'), fj('function averageByDepartment(employees) {\n  const result = {};\n  for (const e of employees) result[e.department] = e.rate;\n  return result;\n}'), fj('function averageByDepartment(employees) {\n  const total = employees.reduce((s, e) => s + e.rate, 0);\n  return { all: Math.round(total / employees.length * 100) / 100 };\n}'), fj('function averageByDepartment(employees) {\n  const g = {};\n  for (const e of employees) g[e.department] = (g[e.department] || 0) + e.rate;\n  return g;\n}')],
  },
  'web-16-count-by': {
    valid: [fj('function countBy(items, key) {\n  const counts = {};\n  for (const item of items) {\n    const value = item[key] === undefined ? "unknown" : item[key];\n    counts[value] = (counts[value] || 0) + 1;\n  }\n  return counts;\n}')],
    wrong: [fj('function countBy(items, key) {\n  const counts = {};\n  for (const item of items) counts[item.key] = (counts[item.key] || 0) + 1;\n  return counts;\n}'), fj('function countBy(items, key) {\n  const counts = {};\n  for (const item of items) counts[item[key]] = (counts[item[key]] || 0) + 1;\n  return counts;\n}'), fj('function countBy(items, key) {\n  const counts = {};\n  for (const item of items) { const v = item[key] || "unknown"; counts[v] = 1; }\n  return counts;\n}'), fj('function countBy(items, key) {\n  return items.length;\n}')],
  },
  'web-16-index-by': {
    valid: [fj('function indexBy(products, key) {\n  const out = {};\n  for (const p of products) out[p[key]] = { ...p, indexed: true };\n  return out;\n}'), fj('const indexBy = (products, key) => Object.fromEntries(products.map((p) => [p[key], { ...p, indexed: true }]));')],
    wrong: [fj('function indexBy(products, key) {\n  const out = {};\n  for (const p of products) { p.indexed = true; out[p[key]] = p; }\n  return out;\n}'), fj('function indexBy(products, key) {\n  const out = {};\n  for (const p of products) if (!(p[key] in out)) out[p[key]] = { ...p, indexed: true };\n  return out;\n}'), fj('function indexBy(products, key) {\n  const out = {};\n  for (const p of products) out[p[key]] = { ...p };\n  return out;\n}'), fj('function indexBy(products, key) {\n  return products.map((p) => ({ ...p, indexed: true }));\n}')],
  },
  'web-16-summarise-laps': {
    valid: [fj('function summarise(entry) {\n  const { driver, laps } = entry;\n  if (laps.length === 0) return { driver, best: null, average: null, count: 0 };\n  const total = laps.reduce((a, b) => a + b, 0);\n  return { driver, best: Math.min(...laps), average: Math.round(total / laps.length * 100) / 100, count: laps.length };\n}')],
    wrong: [fj('function summarise({ driver, laps }) {\n  return { driver, best: Math.min(...laps), average: Math.round(laps.reduce((a, b) => a + b, 0) / laps.length * 100) / 100, count: laps.length };\n}'), fj('function summarise({ driver, laps }) {\n  if (laps.length === 0) return { driver, best: null, average: null, count: 0 };\n  return { driver, best: Math.max(...laps), average: Math.round(laps.reduce((a, b) => a + b, 0) / laps.length * 100) / 100, count: laps.length };\n}'), fj('function summarise({ driver, laps }) {\n  if (laps.length === 0) return { driver, best: null, average: null, count: 0 };\n  return { driver, best: Math.min(...laps), average: laps.reduce((a, b) => a + b, 0) / laps.length, count: laps.length };\n}'), fj('function summarise(e) {\n  e.laps.sort((a, b) => a - b);\n  if (e.laps.length === 0) return { driver: e.driver, best: null, average: null, count: 0 };\n  return { driver: e.driver, best: e.laps[0], average: Math.round(e.laps.reduce((a, b) => a + b, 0) / e.laps.length * 100) / 100, count: e.laps.length };\n}')],
  },
});
void M;

Object.assign(jsSolutions, {
  'web-17-safe-parse': {
    valid: [fj('function parseJson(text, fallback) {\n  try {\n    return JSON.parse(text);\n  } catch (e) {\n    return fallback;\n  }\n}')],
    wrong: [fj('function parseJson(text, fallback) {\n  return JSON.parse(text);\n}'), fj('function parseJson(text, fallback) {\n  try {\n    return JSON.parse(text);\n  } catch (e) {\n    return null;\n  }\n}'), fj('function parseJson(text, fallback) {\n  const v = JSON.parse(text);\n  return v || fallback;\n}'), fj('function parseJson(text, fallback) {\n  try {\n    JSON.parse(text);\n  } catch (e) {\n    return fallback;\n  }\n}')],
  },
  'web-17-validate-reading': {
    valid: [fj('function validateReading(x) {\n  if (typeof x !== "number" || Number.isNaN(x)) throw new TypeError("Reading must be a number");\n  if (x < -50 || x > 150) throw new RangeError("Reading out of range");\n  return Math.round(x * 10) / 10;\n}')],
    wrong: [fj('function validateReading(x) {\n  if (typeof x !== "number") throw new TypeError("Reading must be a number");\n  if (x < -50 || x > 150) throw new RangeError("Reading out of range");\n  return Math.round(x * 10) / 10;\n}'), fj('function validateReading(x) {\n  if (typeof x !== "number" || Number.isNaN(x)) throw new Error("Reading must be a number");\n  if (x < -50 || x > 150) throw new Error("Reading out of range");\n  return Math.round(x * 10) / 10;\n}'), fj('function validateReading(x) {\n  if (typeof x !== "number" || Number.isNaN(x)) throw new TypeError("bad");\n  if (x < -50 || x > 150) throw new RangeError("bad");\n  return Math.round(x * 10) / 10;\n}'), fj('function validateReading(x) {\n  if (typeof x !== "number" || Number.isNaN(x)) throw new TypeError("Reading must be a number");\n  if (x <= -50 || x >= 150) throw new RangeError("Reading out of range");\n  return Math.round(x * 10) / 10;\n}'), fj('function validateReading(x) {\n  if (typeof x !== "number" || Number.isNaN(x)) throw new TypeError("Reading must be a number");\n  if (x < -50 || x > 150) throw new RangeError("Reading out of range");\n  return Math.round(x);\n}'), fj('function validateReading(x) {\n  if (typeof x !== "number" || Number.isNaN(x)) return null;\n  if (x < -50 || x > 150) return null;\n  return Math.round(x * 10) / 10;\n}')],
  },
  'web-17-parse-entry': {
    valid: [fj('function parseLap(text) {\n  const m = /^(\\d+):(\\d{2})\\.(\\d{3})$/.exec(text);\n  if (!m) throw new SyntaxError("Lap time must be in m:ss.mmm format");\n  const seconds = Number(m[2]);\n  if (seconds >= 60) throw new RangeError("The seconds part must be below 60");\n  return Number(m[1]) * 60 + seconds + Number(m[3]) / 1000;\n}')],
    wrong: [fj('function parseLap(text) {\n  const m = /(\\d+):(\\d{2})\\.(\\d{3})/.exec(text);\n  if (!m) throw new SyntaxError("Lap time must be in m:ss.mmm format");\n  const seconds = Number(m[2]);\n  if (seconds >= 60) throw new RangeError("The seconds part must be below 60");\n  return Number(m[1]) * 60 + seconds + Number(m[3]) / 1000;\n}'), fj('function parseLap(text) {\n  const m = /^(\\d+):(\\d{2})\\.(\\d{3})$/.exec(text);\n  if (!m) throw new Error("Lap time must be in m:ss.mmm format");\n  const seconds = Number(m[2]);\n  if (seconds >= 60) throw new Error("The seconds part must be below 60");\n  return Number(m[1]) * 60 + seconds + Number(m[3]) / 1000;\n}'), fj('function parseLap(text) {\n  const m = /^(\\d+):(\\d{2})\\.(\\d{3})$/.exec(text);\n  if (!m) throw new SyntaxError("Lap time must be in m:ss.mmm format");\n  return Number(m[1]) * 60 + Number(m[2]) + Number(m[3]) / 1000;\n}'), fj('function parseLap(text) {\n  const m = /^(\\d+):(\\d{2})\\.(\\d{3})$/.exec(text);\n  if (!m) throw new SyntaxError("Lap time must be in m:ss.mmm format");\n  const seconds = Number(m[2]);\n  if (seconds > 60) throw new RangeError("The seconds part must be below 60");\n  return Number(m[1]) * 60 + seconds + Number(m[3]) / 1000;\n}'), fj('function parseLap(text) {\n  const [a, b] = text.split(":");\n  return Number(a) * 60 + Number(b);\n}')],
  },
  'web-17-safe-share': {
    valid: [fj('function perPerson(total, people) {\n  if (typeof total !== "number" || Number.isNaN(total) || total < 0) throw new TypeError("total must be a non-negative number");\n  if (!Number.isInteger(people) || people < 1) throw new RangeError("people must be a whole number of at least 1");\n  return Math.round(total / people * 100) / 100;\n}')],
    wrong: [fj('function perPerson(total, people) {\n  if (people < 1) throw new RangeError("people must be at least 1");\n  return Math.round(total / people * 100) / 100;\n}'), fj('function perPerson(total, people) {\n  if (typeof total !== "number" || total < 0) throw new TypeError("total must be a number");\n  if (!Number.isInteger(people) || people < 1) throw new RangeError("people must be a whole number");\n  return total / people;\n}'), fj('function perPerson(total, people) {\n  if (typeof total !== "number" || Number.isNaN(total) || total < 0) throw new RangeError("total must be a non-negative number");\n  if (!Number.isInteger(people) || people < 1) throw new RangeError("people must be a whole number of at least 1");\n  return Math.round(total / people * 100) / 100;\n}'), fj('function perPerson(total, people) {\n  if (typeof total !== "number" || Number.isNaN(total) || total < 0) throw new TypeError("total must be a non-negative number");\n  if (people < 1) throw new RangeError("people must be at least 1");\n  return Math.round(total / people * 100) / 100;\n}')],
  },
  'web-17-fix-average': {
    valid: [fj('function average(values) {\n  if (values.length === 0) return 0;\n  let total = 0;\n  for (const v of values) total += v;\n  return total / values.length;\n}')],
    wrong: [fj('function average(values) {\n  let total = 0;\n  for (let i = 0; i < values.length; i++) total += values[i];\n  return total / values.length;\n}'), fj('function average(values) {\n  if (values.length === 0) return 0;\n  let total = 0;\n  for (let i = 0; i < values.length; i++) total += values[i];\n  return total / values.length - 1;\n}'), fj('function average(values) {\n  if (values.length === 0) return 0;\n  let total = 0;\n  for (let i = 1; i < values.length; i++) total += values[i];\n  return total / values.length;\n}'), fj('function average(values) {\n  if (values.length === 0) return 0;\n  return values.reduce((a, b) => a + b) / (values.length + 1);\n}')],
  },
  'web-17-fix-dedupe': {
    valid: [fj('function uniqueSkus(list) {\n  const seen = new Set();\n  const out = [];\n  for (const sku of list) {\n    if (!seen.has(sku)) {\n      seen.add(sku);\n      out.push(sku);\n    }\n  }\n  return out;\n}'), fj('const uniqueSkus = (list) => list.filter((x, i) => list.indexOf(x) === i);')],
    wrong: [fj('function uniqueSkus(list) {\n  const out = [];\n  for (const x of list) if (out.length === 0 || out[out.length - 1] !== x) out.push(x);\n  return out;\n}'), fj('function uniqueSkus(list) {\n  return [...new Set(list.sort())];\n}'), fj('function uniqueSkus(list) {\n  const out = [];\n  for (const x of list) if (!out.includes(x)) out.push(x); else out.pop();\n  return out;\n}'), fj('function uniqueSkus(list) {\n  const seen = {};\n  const out = [];\n  for (const x of list) { if (!seen[x]) { seen[x] = true; out.push(x); } }\n  return out;\n}')],
  },
  'web-17-fix-clamp': {
    valid: [fj('function clampThrottle(value) {\n  if (typeof value !== "number" || Number.isNaN(value)) return 0;\n  if (value >= 100) return 100;\n  if (value <= 0) return 0;\n  return Math.round(value);\n}')],
    wrong: [fj('function clampThrottle(value) {\n  if (value === 100) return 100;\n  if (value < 0) return 0;\n  return Math.round(value);\n}'), fj('function clampThrottle(value) {\n  if (typeof value !== "number") return 0;\n  if (value > 100) return 100;\n  if (value < 0) return 0;\n  return Math.round(value);\n}'), fj('function clampThrottle(value) {\n  if (typeof value !== "number" || Number.isNaN(value)) return 0;\n  if (value > 100) return 100;\n  if (value < 0) return 0;\n  return Math.floor(value);\n}'), fj('function clampThrottle(value) {\n  if (typeof value !== "number" || Number.isNaN(value)) return 0;\n  return Math.round(value);\n}')],
  },
});

const H_STATUS = '<h1 id="title">Loading...</h1>\n<p id="status">unknown</p>\n<ul id="alerts"></ul>\n';
const H_MACH = '<h1>Machines</h1>\n<ul id="machines"></ul>\n';
const H_BOARD = '<table>\n  <thead><tr><th>#</th><th>Player</th><th>Score</th></tr></thead>\n  <tbody id="board"></tbody>\n</table>\n';
const H_CARDS = '<div id="cards"></div>\n';
const machJs = 'function renderMachines(machines) {\n  const list = document.querySelector("#machines");\n  list.replaceChildren();\n  if (machines.length === 0) {\n    const li = document.createElement("li");\n    li.className = "empty";\n    li.textContent = "No machines";\n    list.append(li);\n    return;\n  }\n  for (const m of machines) {\n    const li = document.createElement("li");\n    li.textContent = `${m.name}: ${m.status}`;\n    li.classList.add(m.status);\n    li.dataset.id = m.id;\n    list.append(li);\n  }\n}';
const boardJs = 'function renderLeaderboard(rows) {\n  const body = document.querySelector("#board");\n  body.replaceChildren();\n  if (rows.length === 0) {\n    const tr = document.createElement("tr");\n    const td = document.createElement("td");\n    td.colSpan = 3;\n    td.textContent = "No scores yet";\n    tr.append(td);\n    body.append(tr);\n    return;\n  }\n  const sorted = [...rows].sort((a, b) => b.score - a.score || a.name.localeCompare(b.name));\n  sorted.forEach((r, i) => {\n    const tr = document.createElement("tr");\n    if (i === 0) tr.classList.add("top");\n    for (const v of [i + 1, r.name, r.score]) {\n      const td = document.createElement("td");\n      td.textContent = v;\n      tr.append(td);\n    }\n    body.append(tr);\n  });\n}';
const cardsJs = 'function renderCards(products) {\n  const box = document.querySelector("#cards");\n  box.replaceChildren();\n  if (products.length === 0) {\n    const p = document.createElement("p");\n    p.className = "empty";\n    p.textContent = "Nothing to show";\n    box.append(p);\n    return;\n  }\n  for (const p of products) {\n    const card = document.createElement("article");\n    card.className = "card";\n    card.dataset.sku = p.sku;\n    const h3 = document.createElement("h3");\n    h3.textContent = p.name;\n    const price = document.createElement("p");\n    price.className = "price";\n    price.textContent = "£" + p.price.toFixed(2);\n    card.append(h3, price);\n    if (p.stock === 0) {\n      card.classList.add("sold-out");\n      const badge = document.createElement("span");\n      badge.className = "badge";\n      badge.textContent = "Sold out";\n      card.append(badge);\n    }\n    box.append(card);\n  }\n}';
Object.assign(jsSolutions, {
  'web-18-update-status': {
    valid: [fj('const title = document.querySelector("#title");\ntitle.textContent = "Machine M-7";\ntitle.setAttribute("data-machine", "M-7");\nconst status = document.querySelector("#status");\nstatus.textContent = "running";\nstatus.classList.add("ok");\nfor (const text of ["Oil low", "Door open"]) {\n  const li = document.createElement("li");\n  li.textContent = text;\n  document.querySelector("#alerts").append(li);\n}', H_STATUS, '.ok { color: #1b7f3b; }\n')],
    wrong: [fj('document.querySelector("#title").textContent = "Machine M-7";\ndocument.querySelector("#status").textContent = "running";\ndocument.querySelector("#alerts").innerHTML = "<li>Oil low</li>";', H_STATUS), fj('document.querySelector("#title").textContent = "Machine M-7";\ndocument.querySelector("#title").setAttribute("data-machine", "M-7");\ndocument.querySelector("#status").textContent = "running";\nfor (const t of ["Oil low", "Door open"]) { const li = document.createElement("li"); li.textContent = t; document.querySelector("#alerts").append(li); }', H_STATUS), fj('const t = document.querySelector("#title");\nt.textContent = "Machine M-7";\nt.dataset.machine = "M-8";\nconst s = document.querySelector("#status");\ns.textContent = "running";\ns.classList.add("ok");\nfor (const x of ["Oil low", "Door open"]) { const li = document.createElement("li"); li.textContent = x; document.querySelector("#alerts").append(li); }', H_STATUS), fj('document.querySelector("#title").textContent = "Machine M-7";\ndocument.querySelector("#title").setAttribute("data-machine", "M-7");\ndocument.querySelector("#status").textContent = "running";\ndocument.querySelector("#status").classList.add("ok");\nconst li = document.createElement("li");\nli.textContent = "Oil low, Door open";\ndocument.querySelector("#alerts").append(li);', H_STATUS)],
  },
  'web-18-render-machines': {
    valid: [fj(machJs, H_MACH), fj('function renderMachines(machines) {\n  const list = document.querySelector("#machines");\n  list.textContent = "";\n  if (!machines.length) { list.innerHTML = \'<li class="empty">No machines</li>\'; return; }\n  machines.forEach((m) => {\n    const li = list.appendChild(document.createElement("li"));\n    li.textContent = m.name + ": " + m.status;\n    li.setAttribute("class", m.status);\n    li.setAttribute("data-id", m.id);\n  });\n}', H_MACH)],
    wrong: [fj(machJs.replace('list.replaceChildren();', ''), H_MACH), fj(machJs.replace('li.textContent = `${m.name}: ${m.status}`;', 'li.innerHTML = `${m.name}: ${m.status}`;'), H_MACH), fj(machJs.replace(/  if \(machines.length === 0\) \{[\s\S]*?\n    return;\n  \}\n/, ''), H_MACH), fj(machJs.replace('li.dataset.id = m.id;', ''), H_MACH), fj(machJs.replace('li.classList.add(m.status);', ''), H_MACH), fj(machJs.replace('li.textContent = `${m.name}: ${m.status}`;', 'li.textContent = m.name;'), H_MACH)],
  },
  'web-18-render-leaderboard': {
    valid: [fj(boardJs, H_BOARD, '.top { font-weight: bold; }\n')],
    wrong: [fj(boardJs.replace('[...rows].sort', 'rows.sort'), H_BOARD), fj(boardJs.replace('body.replaceChildren();', ''), H_BOARD), fj(boardJs.replace('b.score - a.score || a.name.localeCompare(b.name)', 'b.score - a.score'), H_BOARD), fj(boardJs.replace('td.textContent = v;', 'td.innerHTML = v;'), H_BOARD), fj(boardJs.replace('if (i === 0) tr.classList.add("top");', ''), H_BOARD), fj(boardJs.replace('td.colSpan = 3;', ''), H_BOARD), fj(boardJs.replace('[i + 1, r.name, r.score]', '[i, r.name, r.score]'), H_BOARD)],
  },
  'web-18-render-cards': {
    valid: [fj(cardsJs, H_CARDS)],
    wrong: [fj(cardsJs.replace('box.replaceChildren();', ''), H_CARDS), fj(cardsJs.replace('h3.textContent = p.name;', 'h3.innerHTML = p.name;'), H_CARDS), fj(cardsJs.replace('p.price.toFixed(2)', 'p.price'), H_CARDS), fj(cardsJs.replace('card.classList.add("sold-out");', ''), H_CARDS), fj(cardsJs.replace('card.dataset.sku = p.sku;', ''), H_CARDS), fj(cardsJs.replace('if (p.stock === 0)', 'if (p.stock < 5)'), H_CARDS), fj(cardsJs.replace(/  if \(products.length === 0\) \{[\s\S]*?\n    return;\n  \}\n/, ''), H_CARDS)],
  },
});

const H_VISIT = '<button id="visit">Visit</button>\n<button id="reset">Reset</button>\n<p>Total: <span id="total">0</span></p>\n';
const H_STOCK = '<button id="minus">-</button>\n<span id="qty">?</span>\n<button id="plus">+</button>\n<p id="msg"></p>\n';
const H_TODO = '<input id="new" placeholder="New task">\n<button id="add">Add</button>\n<ul id="tasks"></ul>\n<p id="remaining">0 remaining</p>\n';
const H_FILTER = '<div id="filters">\n  <button class="filter" data-team="all">All</button>\n  <button class="filter" data-team="Owls">Owls</button>\n  <button class="filter" data-team="Cats">Cats</button>\n</div>\n<table>\n  <tbody>\n    <tr data-team="Owls"><td>Owls 5</td></tr>\n    <tr data-team="Cats"><td>Cats 2</td></tr>\n    <tr data-team="Owls"><td>Owls 3</td></tr>\n    <tr data-team="Cats"><td>Cats 4</td></tr>\n    <tr data-team="Cats"><td>Cats 1</td></tr>\n  </tbody>\n</table>\n<p id="count"></p>\n';
const stockJs = 'let qty = 5;\nconst out = document.querySelector("#qty");\nconst minus = document.querySelector("#minus");\nconst plus = document.querySelector("#plus");\nconst msg = document.querySelector("#msg");\nfunction render() {\n  out.textContent = qty;\n  minus.disabled = qty <= 0;\n  plus.disabled = qty >= 20;\n  msg.textContent = qty <= 0 ? "Minimum reached" : qty >= 20 ? "Maximum reached" : "";\n}\nminus.addEventListener("click", () => { if (qty > 0) qty--; render(); });\nplus.addEventListener("click", () => { if (qty < 20) qty++; render(); });\nrender();';
const todoJs = 'let tasks = [];\nconst list = document.querySelector("#tasks");\nconst input = document.querySelector("#new");\nfunction render() {\n  list.replaceChildren();\n  tasks.forEach((t, i) => {\n    const li = document.createElement("li");\n    if (t.done) li.classList.add("done");\n    li.dataset.index = i;\n    const span = document.createElement("span");\n    span.className = "text";\n    span.textContent = t.text;\n    const rm = document.createElement("button");\n    rm.className = "remove";\n    rm.textContent = "x";\n    li.append(span, rm);\n    list.append(li);\n  });\n  document.querySelector("#remaining").textContent = `${tasks.filter((t) => !t.done).length} remaining`;\n}\ndocument.querySelector("#add").addEventListener("click", () => {\n  const text = input.value.trim();\n  if (!text) return;\n  tasks.push({ text, done: false });\n  input.value = "";\n  render();\n});\nlist.addEventListener("click", (e) => {\n  const li = e.target.closest("li");\n  if (!li) return;\n  const i = Number(li.dataset.index);\n  if (e.target.classList.contains("remove")) tasks.splice(i, 1);\n  else tasks[i].done = !tasks[i].done;\n  render();\n});\nrender();';
const filterJs = 'let current = "all";\nconst buttons = document.querySelectorAll(".filter");\nconst rows = document.querySelectorAll("tbody tr");\nfunction render() {\n  let shown = 0;\n  for (const r of rows) {\n    const visible = current === "all" || r.dataset.team === current;\n    r.hidden = !visible;\n    if (visible) shown++;\n  }\n  for (const b of buttons) b.classList.toggle("active", b.dataset.team === current);\n  document.querySelector("#count").textContent = `${shown} shown`;\n}\ndocument.querySelector("#filters").addEventListener("click", (e) => {\n  const b = e.target.closest(".filter");\n  if (!b) return;\n  current = b.dataset.team;\n  render();\n});\nrender();';
Object.assign(jsSolutions, {
  'web-19-click-counter': {
    valid: [fj('let count = 0;\nconst total = document.querySelector("#total");\ndocument.querySelector("#visit").addEventListener("click", () => {\n  count++;\n  total.textContent = count;\n});\ndocument.querySelector("#reset").addEventListener("click", () => {\n  count = 0;\n  total.textContent = count;\n});', H_VISIT)],
    wrong: [fj('let count = 0;\ndocument.querySelector("#visit").addEventListener("click", () => {\n  count++;\n  document.querySelector("#total").textContent = count;\n});', H_VISIT), fj('let count = 0;\nconst total = document.querySelector("#total");\ndocument.querySelector("#visit").addEventListener("click", () => {\n  count++;\n  total.textContent = count;\n});\ndocument.querySelector("#reset").addEventListener("click", () => {\n  total.textContent = 0;\n});', H_VISIT), fj('document.querySelector("#visit").addEventListener("click", () => {\n  document.querySelector("#total").textContent = 1;\n});\ndocument.querySelector("#reset").addEventListener("click", () => {\n  document.querySelector("#total").textContent = 0;\n});', H_VISIT)],
  },
  'web-19-stock-counter': {
    valid: [fj(stockJs, H_STOCK)],
    wrong: [fj(stockJs.replace('render();\nminus', 'minus').replace('\nrender();', ''), H_STOCK), fj(stockJs.replace('plus.disabled = qty >= 20;', ''), H_STOCK), fj(stockJs.replace('qty >= 20 ? "Maximum reached"', 'qty > 20 ? "Maximum reached"'), H_STOCK), fj(stockJs.replace('minus.disabled = qty <= 0;', 'minus.disabled = qty < 0;'), H_STOCK)],
  },
  'web-19-todo-list': {
    valid: [fj(todoJs, H_TODO, '.done { text-decoration: line-through; }\n')],
    wrong: [fj(todoJs.replace('const text = input.value.trim();\n  if (!text) return;', 'const text = input.value;\n  if (!text) return;'), H_TODO), fj(todoJs.replace('if (!text) return;', ''), H_TODO), fj(todoJs.replace('input.value = "";\n', ''), H_TODO), fj(todoJs.replace('tasks.filter((t) => !t.done).length', 'tasks.length'), H_TODO), fj(todoJs.replace('list.addEventListener("click", (e) => {', 'list.addEventListener("dblclick", (e) => {'), H_TODO), fj(todoJs.replace('if (e.target.classList.contains("remove")) tasks.splice(i, 1);\n  else tasks[i].done = !tasks[i].done;', 'tasks[i].done = !tasks[i].done;'), H_TODO)],
  },
  'web-19-team-filter': {
    valid: [fj(filterJs, H_FILTER, '.active { font-weight: bold; }\n')],
    wrong: [fj(filterJs.replace('r.hidden = !visible;', 'if (!visible) r.remove();'), H_FILTER), fj(filterJs.replace('b.classList.toggle("active", b.dataset.team === current);', 'b.classList.add("active");'), H_FILTER), fj(filterJs.replace('${shown} shown', '${rows.length} shown'), H_FILTER), fj(filterJs.replace('\nrender();', ''), H_FILTER), fj(filterJs.replace('current === "all" || r.dataset.team === current', 'r.dataset.team === current'), H_FILTER)],
  },
});
